### ISSUE TITLE
Repo tranferred to a new organization - broken link

### ISSUE THREAD

**Issue by matteoettam09** [JuliaCon/proceedings-review#100]
To whom it might concern,

I have moved our repository from my personal github to the organization one. From here
https://github.com/matteoettam09/FTLE.jl

to here

https://github.com/PoincareTrajectories/FTLE.jl

I hope you won't have problems with this. If so, let me know.

**Comment by whedon** [comment]
:wave: This repository is only for review issues (`pre-review` and `review`) that have been created by our editorial infrastructure, and this issue appears not to be one of these.

As such, this issue will be closed. If you're opening an issue as part of a review, please open a new issue instead in the software repository associated with the submission that you are reviewing.

Many thanks!
