### ISSUE TITLE
[PRE REVIEW]: Tracking.jl: Accelerating multi-antenna GNSS receivers with CUDA

### ISSUE THREAD

**Issue by whedon** [JuliaCon/proceedings-review#102]
**Submitting author:** @ozmaden (<a href="http://orcid.org/0000-0003-0614-3988">Can Özmaden</a>)
**Repository:** <a href="https://github.com/ozmaden/GPUAcceleratedTracking" target ="_blank">https://github.com/ozmaden/GPUAcceleratedTracking</a>
**Version:** 
**Editor:** @vchuravy
**Reviewers:** @lucaferranti, @maleadt
**Managing EiC:** Valentin Churavy

**Author instructions**

Thanks for submitting your paper to JCON @ozmaden. **Currently, there isn't an JCON editor assigned** to your paper.

The author's suggestion for the handling editor is @vchuravy.

@ozmaden if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/jcon-reviewers) have already agreed to review for JCON and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JCON submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Failed to discover a `Statement of need` section in paper

**Comment by whedon** [comment]
Wordcount for `paper.tex` is 5545

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.22 s (187.5 files/s, 270863.5 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
SVG                              8              1              1          48211
Julia                           21            414            924           5980
TeX                              8            325            231           2734
TOML                             2            306              1           1418
Ruby                             1              8              4             45
Markdown                         1             13              0             35
YAML                             1              2              0             21
-------------------------------------------------------------------------------
SUM:                            42           1069           1161          58444
-------------------------------------------------------------------------------


Statistical information for the repository 'e2ef7bcc454b0a1556d674fe' was
gathered on 2022/10/27.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Can Ozmaden                      1            57              0          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Can Ozmaden                  57          100.0          0.0                7.02
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/JuliaCon/proceedings-papers/jcon.00102/jcon.00102/10.21105.jcon.00102.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/JuliaCon/proceedings-papers/blob/jcon.00102/jcon.00102/10.21105.jcon.00102.pdf) :page_facing_up: :point_left:

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1137/141000671 is OK
- 10.1287/opre.38.5.911 is OK
- 10.1109/ISSSTA.1992.665623 is OK
- 10.3390/s121013417 is OK
- 10.1109/TWC.2004.833467 is OK
- 10.1109/TPDS.2018.2872064 is OK
- 10.21105/joss.02673 is OK
- 10.5281/zenodo.5870363 is OK
- 10.1109/ICINIS.2008.99 is OK
- 10.21105/joss.03349 is OK
- 10.5281/zenodo.5933659 is OK
- 10.5281/zenodo.5933726 is OK

MISSING DOIs

- 10.1007/s10291-016-0516-2 may be a valid DOI for title: Correlation acceleration in GNSS software receivers using a CUDA-enabled GPU
- 10.1109/plans.1996.509077 may be a valid DOI for title: Adaptive antenna arrays for interference cancellation in GPS and GLONASS receivers
- 10.33012/2018.15873 may be a valid DOI for title: Estimation of antenna array manifolds based on sparse measurements
- 10.1186/s13638-018-1132-3 may be a valid DOI for title: Research on multi-constellation GNSS compatible acquisition strategy based on GPU high-performance operation
- 10.22457/jmi.v20a05192 may be a valid DOI for title: Satellite Navigation Simulation Signal Generation Method Based on GPU Acceleration
- 10.1109/globalsip.2015.7418431 may be a valid DOI for title: An accelerated signal tracking module using a heterogeneous multi-GPU platform for real-time GNSS software receiver
- 10.4018/ijghpc.2014070102 may be a valid DOI for title: Accelerating a cloud-based software GNSS receiver
- 10.33012/2016.14576 may be a valid DOI for title: Accelerating GNSS software receivers

INVALID DOIs

- https://doi.org/10.1002/navi.29 is INVALID because of 'https://doi.org/' prefix
```

**Comment by carstenbauer** [comment]
@whedon assign @vchuravy as editor

**Comment by whedon** [comment]
OK, the editor is @vchuravy

**Comment by vchuravy** [comment]
@ozmaden  Can you update the DOIs? Also do you have reviewers to suggest?

**Comment by lucaferranti** [comment]
@vchuravy if you havent found any reviewers, I could review this, I have some working experience with satellite positioning and receivers architecture, as well as Julia working experience ofc

**Comment by ozmaden** [comment]
@vchuravy I will fix the DOI asap, seems like I just need to remove the 'https://doi.org/' prefix.
 I do not have specific reviewers in mind. If @lucaferranti would like to review my work, I would be very happy to get his feedback

**Comment by vchuravy** [comment]
@whedon add @lucaferranti as reviewer

**Comment by whedon** [comment]
OK, @lucaferranti is now a reviewer

**Comment by vchuravy** [comment]
@whedon add @maleadt as reviewer

**Comment by whedon** [comment]
OK, @maleadt is now a reviewer

**Comment by vchuravy** [comment]
@whedon start review
