### ISSUE TITLE
[PRE REVIEW]: AstroImages.jl

### ISSUE THREAD

**Issue by whedon** [JuliaCon/proceedings-review#104]
**Submitting author:** @sefffal (<a href="http://orcid.org/0000-0001-5684-4593">William R. Thompson</a>)
**Repository:** <a href="https://github.com/JuliaAstro/AstroImages.jl.git" target ="_blank">https://github.com/JuliaAstro/AstroImages.jl.git</a>
**Version:** 
**Editor:** @carstenbauer
**Reviewers:** @oschulz, @lucaferranti
**Managing EiC:** Valentin Churavy

**Author instructions**

Thanks for submitting your paper to JCON @sefffal. **Currently, there isn't an JCON editor assigned** to your paper.

The author's suggestion for the handling editor is @carstenbauer.

@sefffal if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/jcon-reviewers) have already agreed to review for JCON and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JCON submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
PDF failed to compile for issue #104 with the following error: 
```
 Can't find any papers to compile :-(

```

**Comment by sefffal** [comment]
Not sure what the issue is. The paper is in the expected location paper.tex in the paper folder on the paper branch of the repo.

**Comment by vchuravy** [comment]
:warning: [An error happened when generating the pdf](https://github.com/JuliaCon/juliacon-proceedings-papers-testing/actions/runs/3338830833?check_suite_focus=true).

**Comment by sefffal** [comment]
The issue seems to be that the `paper` directory is not merged on the main branch. From the submission instructions, it seemed it possible to keep it on a separate `paper` branch. Is that still ok, or would I have to merge it?

**Comment by vchuravy** [comment]
:warning: [An error happened when generating the pdf](https://github.com/JuliaCon/juliacon-proceedings-papers-testing/actions/runs/3338830833?check_suite_focus=true).

**Comment by carstenbauer** [comment]
@whedon assign @carstenbauer as editor

**Comment by whedon** [comment]
OK, the editor is @carstenbauer

**Comment by whedon** [comment]
PDF failed to compile for issue #104 with the following error: 
```
 Can't find any papers to compile :-(

```

**Comment by carstenbauer** [comment]
@whedon generate pdf from branch paper

**Comment by sefffal** [comment]
I’m not sure what would cause this issue. I placed the template in the paper directory on the paper branch of the repo.
Any suggestions?

**Comment by whedon** [comment]
PDF failed to compile for issue #104 with the following error: 
```
 Latexmk: This is Latexmk, John Collins, 17 Jan. 2018, version: 4.55.
Rule 'pdflatex': Rules & subrules not known to be previously run:
   pdflatex
Rule 'pdflatex': The following rules & subrules became out-of-date:
      'pdflatex'
------------
Run number 1 of rule 'pdflatex'
------------
------------
Running 'pdflatex  -recorder  "paper.tex"'
------------
Rule 'pdflatex': File changes, etc:
   Changed files, or newly in use since previous run(s):
      'paper.aux'
------------
Run number 2 of rule 'pdflatex'
------------
------------
Running 'pdflatex  -recorder  "paper.tex"'
------------
Rule 'pdflatex': File changes, etc:
   Changed files, or newly in use since previous run(s):
      'paper.out'
------------
Run number 3 of rule 'pdflatex'
------------
------------
Running 'pdflatex  -recorder  "paper.tex"'
------------
Failure to make 'paper.pdf'
Collected error summary (may duplicate other messages):
  pdflatex: Command for 'pdflatex' gave return code 1
      Refer to 'paper.log' for details
Looks like we failed to compile the PDF

```

**Comment by carstenbauer** [comment]
@vchuravy Any idea what's going on here? Seems to be set up correctly (in subfolder `paper` in the branch `paper`).

**Comment by carstenbauer** [comment]
@sefffal While we resolve the technical issues, can you please recommend a few potential reviewers?

**Comment by sefffal** [comment]
Sure, thanks. Is there a list of possible reviewers listed somewhere?

**Comment by carstenbauer** [comment]
@whedon list reviewers

**Comment by carstenbauer** [comment]
There is this one ☝️ but it might not be very up to date, so feel free to suggest other people as well (can also be outside the Julia community if you think they might still be willing to review).

**Comment by carstenbauer** [comment]
@sefffal Quick reminder of the TODOs:

1) fix the `.latexmkrc` issue
2) suggest reviewers as soon as possible

Enjoy the rest of the holidays / the turn of the year!

**Comment by carstenbauer** [comment]
@whedon add @oschulz as reviewer

**Comment by whedon** [comment]
OK, @oschulz is now a reviewer

**Comment by sefffal** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
PDF failed to compile for issue #104 with the following error: 
```
 Can't find any papers to compile :-(

```

**Comment by sefffal** [comment]
Thanks for the reminder @carstenbauer .
I've added the missing latexmk file (sorry about that!). Maybe there is another issue.

Here are some suggested reviewers: lucaferranti, mauro3, bidhya, hameye

**Comment by carstenbauer** [comment]
@whedon generate pdf from branch paper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch paper. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #104 with the following error: 
```
 Latexmk: This is Latexmk, John Collins, 17 Jan. 2018, version: 4.55.
Rule 'pdflatex': Rules & subrules not known to be previously run:
   pdflatex
Rule 'pdflatex': The following rules & subrules became out-of-date:
      'pdflatex'
------------
Run number 1 of rule 'pdflatex'
------------
------------
Running 'pdflatex  -recorder  "paper.tex"'
------------
Latexmk: List of undefined refs and citations:
  Citation `bezanson2017julia' on page 1 undefined on input line 17
  Citation `fitsstandard' on page 1 undefined on input line 25
Latexmk: Summary of warnings:
  Latex failed to resolve 2 citation(s)
Rule 'pdflatex': File changes, etc:
   Changed files, or newly in use since previous run(s):
      'paper.aux'
------------
Run number 2 of rule 'pdflatex'
------------
------------
Running 'pdflatex  -recorder  "paper.tex"'
------------
Latexmk: List of undefined refs and citations:
  Citation `bezanson2017julia' on page 1 undefined on input line 17
  Citation `fitsstandard' on page 1 undefined on input line 25
Latexmk: Summary of warnings:
  Latex failed to resolve 2 citation(s)
Rule 'pdflatex': File changes, etc:
   Changed files, or newly in use since previous run(s):
      'paper.out'
------------
Run number 3 of rule 'pdflatex'
------------
------------
Running 'pdflatex  -recorder  "paper.tex"'
------------
Latexmk: List of undefined refs and citations:
  Citation `bezanson2017julia' on page 1 undefined on input line 17
  Citation `fitsstandard' on page 1 undefined on input line 25
Latexmk: Summary of warnings:
  Latex failed to resolve 2 citation(s)
Failure to make 'paper.pdf'
Collected error summary (may duplicate other messages):
  pdflatex: Command for 'pdflatex' gave return code 1
      Refer to 'paper.log' for details
Looks like we failed to compile the PDF

```

**Comment by carstenbauer** [comment]
@sefffal thanks for the suggestions. As for the compilation, please see above. There seems to be an issue with some references.

**Comment by carstenbauer** [comment]
@whedon add @lucaferranti as reviewer

**Comment by whedon** [comment]
OK, @lucaferranti is now a reviewer

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List Whedon's capabilities
@whedon commands

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

EDITORIAL TASKS

# Compile the paper
@whedon generate pdf

# Compile the paper from alternative branch
@whedon generate pdf from branch custom-branch-name

# Ask Whedon to check the references for missing DOIs
@whedon check references

# Ask Whedon to check repository statistics for the submitted software
@whedon check repository

```

**Comment by whedon** [comment]
I'm sorry human, I don't understand that. You can see what commands I support by typing:

```
@whedon commands
```

**Comment by carstenbauer** [comment]
@sefffal Would be great if you could fix the paper compilation so that we can move to review stage.

**Comment by sefffal** [comment]
Thanks all, I will try to sort out the issues by the end of the week (attending a conference atm)

**Comment by sefffal** [comment]
@whedon generate pdf from branch paper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch paper. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #104 with the following error: 
```
 Latexmk: This is Latexmk, John Collins, 17 Jan. 2018, version: 4.55.
Rule 'pdflatex': Rules & subrules not known to be previously run:
   pdflatex
Rule 'pdflatex': The following rules & subrules became out-of-date:
      'pdflatex'
------------
Run number 1 of rule 'pdflatex'
------------
------------
Running 'pdflatex  -recorder  "paper.tex"'
------------
Latexmk: List of undefined refs and citations:
  Citation `bezanson2017julia' on page 1 undefined on input line 17
  Citation `fitsstandard' on page 1 undefined on input line 25
Latexmk: Summary of warnings:
  Latex failed to resolve 2 citation(s)
Rule 'pdflatex': File changes, etc:
   Changed files, or newly in use since previous run(s):
      'paper.aux'
------------
Run number 2 of rule 'pdflatex'
------------
------------
Running 'pdflatex  -recorder  "paper.tex"'
------------
Latexmk: List of undefined refs and citations:
  Citation `bezanson2017julia' on page 1 undefined on input line 17
  Citation `fitsstandard' on page 1 undefined on input line 25
Latexmk: Summary of warnings:
  Latex failed to resolve 2 citation(s)
Rule 'pdflatex': File changes, etc:
   Changed files, or newly in use since previous run(s):
      'paper.out'
------------
Run number 3 of rule 'pdflatex'
------------
------------
Running 'pdflatex  -recorder  "paper.tex"'
------------
Latexmk: List of undefined refs and citations:
  Citation `bezanson2017julia' on page 1 undefined on input line 17
  Citation `fitsstandard' on page 1 undefined on input line 25
Latexmk: Summary of warnings:
  Latex failed to resolve 2 citation(s)
Failure to make 'paper.pdf'
Collected error summary (may duplicate other messages):
  pdflatex: Command for 'pdflatex' gave return code 1
      Refer to 'paper.log' for details
Looks like we failed to compile the PDF

```

**Comment by sefffal** [comment]
Appologies but I might need some help debugging this. My paper compiles locally using latexmk, and I'm following the template closely. For example, the `bezanson2017julia` citation is taken verbatim from https://github.com/JuliaCon/JuliaConSubmission.jl/

In the meantime I committed my locally compiled PDF to show what it should look like: 
https://github.com/JuliaAstro/AstroImages.jl/blob/paper/paper/paper.pdf

**Comment by carstenbauer** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/JuliaCon/proceedings-review/issues/126.
