### ISSUE TITLE
[PRE REVIEW]: Lyapunov Cycle Detector (LCD.jl): A new tool for the study of basins of attraction induced by rational maps

### ISSUE THREAD

**Issue by whedon** [JuliaCon/proceedings-review#105]
**Submitting author:** @valvarezapa (<a href="http://orcid.org/0000-0001-8232-1809">Víctor Álvarez</a>)
**Repository:** <a href="https://github.com/valvarezapa/LCD" target ="_blank">https://github.com/valvarezapa/LCD</a>
**Version:** 
**Editor:** @lucaferranti
**Reviewers:** @lbenet, @rpgowers
**Managing EiC:** Valentin Churavy

**Author instructions**

Thanks for submitting your paper to JCON @valvarezapa. **Currently, there isn't an JCON editor assigned** to your paper.

The author's suggestion for the handling editor is @ranjanan.

@valvarezapa if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/jcon-reviewers) have already agreed to review for JCON and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JCON submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Wordcount for `paper.tex` is 524

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.02 s (531.5 files/s, 194055.0 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
TeX                              8            221            167           2178
Julia                            1            168            448            996
Markdown                         1             35              0             56
Jupyter Notebook                 1              0            357             53
Ruby                             1              7              3             37
YAML                             1              0              0             20
-------------------------------------------------------------------------------
SUM:                            13            431            975           3340
-------------------------------------------------------------------------------


Statistical information for the repository '9a84bed82a806527b788aaa8' was
gathered on 2022/10/27.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Víctor Álvarez Apari             3            94             47          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Víctor Álvarez Apari         47           50.0          0.0                6.38
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- None

MISSING DOIs

- 10.1137/141000671 may be a valid DOI for title: Julia: A fresh approach to numerical computing
- 10.32513/tbilisi/1528768904 may be a valid DOI for title: Plotting basins of end points of rational maps with Sage

INVALID DOIs

- None
```

**Comment by whedon** [comment]
PDF failed to compile for issue #105 with the following error: 
```
 Latexmk: This is Latexmk, John Collins, 17 Jan. 2018, version: 4.55.
Rule 'pdflatex': Rules & subrules not known to be previously run:
   pdflatex
Rule 'pdflatex': The following rules & subrules became out-of-date:
      'pdflatex'
------------
Run number 1 of rule 'pdflatex'
------------
------------
Running 'pdflatex  -recorder  "paper.tex"'
------------
===========Latexmk: Missing input file: 'minted.sty' from line
  '! LaTeX Error: File `minted.sty' not found.'
Latexmk: Missing input file: 'minted.sty' from line
  '! LaTeX Error: File `minted.sty' not found.'
Failure to make 'paper.pdf'
Collected error summary (may duplicate other messages):
  pdflatex: Command for 'pdflatex' gave return code 1
      Refer to 'paper.log' for details
Looks like we failed to compile the PDF

```

**Comment by whedon** [comment]
OK, the editor is @ranjanan

**Comment by carstenbauer** [comment]
@whedon assign @vchuravy as editor

**Comment by whedon** [comment]
OK, the editor is @vchuravy

**Comment by vchuravy** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
PDF failed to compile for issue #105 with the following error: 
```
 Latexmk: This is Latexmk, John Collins, 17 Jan. 2018, version: 4.55.
Rule 'pdflatex': Rules & subrules not known to be previously run:
   pdflatex
Rule 'pdflatex': The following rules & subrules became out-of-date:
      'pdflatex'
------------
Run number 1 of rule 'pdflatex'
------------
------------
Running 'pdflatex  -recorder  "paper.tex"'
------------
===========Latexmk: Missing input file: 'minted.sty' from line
  '! LaTeX Error: File `minted.sty' not found.'
Latexmk: Missing input file: 'minted.sty' from line
  '! LaTeX Error: File `minted.sty' not found.'
Failure to make 'paper.pdf'
Collected error summary (may duplicate other messages):
  pdflatex: Command for 'pdflatex' gave return code 1
      Refer to 'paper.log' for details
Looks like we failed to compile the PDF

```

**Comment by matbesancon** [comment]
@whedon assign @lucaferranti as editor

**Comment by lucaferranti** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
PDF failed to compile for issue #105 with the following error: 
```
 Latexmk: This is Latexmk, John Collins, 17 Jan. 2018, version: 4.55.
Rule 'pdflatex': Rules & subrules not known to be previously run:
   pdflatex
Rule 'pdflatex': The following rules & subrules became out-of-date:
      'pdflatex'
------------
Run number 1 of rule 'pdflatex'
------------
------------
Running 'pdflatex  -recorder  "paper.tex"'
------------
===========Latexmk: Missing input file: 'minted.sty' from line
  '! LaTeX Error: File `minted.sty' not found.'
Latexmk: Missing input file: 'minted.sty' from line
  '! LaTeX Error: File `minted.sty' not found.'
Failure to make 'paper.pdf'
Collected error summary (may duplicate other messages):
  pdflatex: Command for 'pdflatex' gave return code 1
      Refer to 'paper.log' for details
Looks like we failed to compile the PDF

```

**Comment by lucaferranti** [comment]
Hi @valvarezapa :wave: ,

Apologies for the long delay, I'll be the editor for this submission.

Since it has been a while, I firsted wanted to double check with you, **are you still interested in having this published?**

If yes, I will start looking for potential reviewers. Suggestions are also welcome of course.

As a first step, as you can see from [this comment](https://github.com/JuliaCon/proceedings-review/issues/105#issuecomment-1710611310) currently the paper fails to compile. This should be fixed before starting the review process.

Looking at the error message, I suspect in your case the error is because you are using the `minted` library (for formatting code snippets I presume) but the compiler cannot find the library file. This is because if you use extra packages with `\usepackage` you should also include the corresponding source code into the `paper` folder, since we currently the bot cannot download those automatically. Can you look into this?

Please let me know if you have any further questions

**Comment by valvarezapa** [comment]
Hi!

Yes! I am still interested in having the paper published. I am very glad to
hear about this.

I have just modified the *paper.tex* file so it is now self-contained and
does not depend on any extra packages. I hope the bot can compile it now.

If there is anything else I can do to make the publishing process easier,
please let me know. Thank you for your time.
Best regards,
Víctor

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Libre
de virus.www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by matbesancon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/JuliaCon/proceedings-papers/jcon.00105/jcon.00105/10.21105.jcon.00105.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/JuliaCon/proceedings-papers/blob/jcon.00105/jcon.00105/10.21105.jcon.00105.pdf) :page_facing_up: :point_left:

**Comment by lucaferranti** [comment]
@whedon assign @lucaferranti as editor

**Comment by whedon** [comment]
OK, the editor is @lucaferranti

**Comment by lucaferranti** [comment]
@whedon assign @lbenet as reviewer

**Comment by whedon** [comment]
OK, @lbenet is now a reviewer

**Comment by lucaferranti** [comment]
Hi @valvarezapa, quick update from my side.

I found a first reviewer. I'll try to find a second one asap.

@lbenet thank you for volunteering as reviewer. You can find more details on the juliacon review process [here](https://juliacon.github.io/proceedings-guide/reviewer/). Note this submission is still in pre-review and the review will start once I found a second reviewer. Meanwhile, feel free to ask me any questions you have.

**Comment by valvarezapa** [comment]
Thank you very much, Luca!

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Libre
de virus.www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by lucaferranti** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/JuliaCon/proceedings-papers/jcon.00105/jcon.00105/10.21105.jcon.00105.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/JuliaCon/proceedings-papers/blob/jcon.00105/jcon.00105/10.21105.jcon.00105.pdf) :page_facing_up: :point_left:

**Comment by lucaferranti** [comment]
@whedon add @rpgowers as reviewer

**Comment by whedon** [comment]
OK, @rpgowers is now a reviewer

**Comment by lucaferranti** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/JuliaCon/proceedings-review/issues/140.
