### ISSUE TITLE
[PRE REVIEW]: ProtoSyn.jl: a novel platform for computational molecular manipulation and simulation with a focus on protein design

### ISSUE THREAD

**Issue by whedon** [JuliaCon/proceedings-review#106]
**Submitting author:** @JosePereiraUA
**Repository:** <a href="https://github.com/sergio-santos-group/ProtoSyn.jl" target ="_blank">https://github.com/sergio-santos-group/ProtoSyn.jl</a>
**Version:** 
**Editor:** @odow
**Reviewers:** @jgreener64, @mfherbst
**Managing EiC:** Valentin Churavy

**Author instructions**

Thanks for submitting your paper to JCON @https://github.com/JosePereiraUA. **Currently, there isn't an JCON editor assigned** to your paper.

The author's suggestion for the handling editor is @vchuravy.

@https://github.com/JosePereiraUA if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/jcon-reviewers) have already agreed to review for JCON and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JCON submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Failed to discover a `Statement of need` section in paper

**Comment by whedon** [comment]
PDF failed to compile for issue #106 with the following error: 
```
 Latexmk: This is Latexmk, John Collins, 17 Jan. 2018, version: 4.55.
Rule 'pdflatex': Rules & subrules not known to be previously run:
   pdflatex
Rule 'pdflatex': The following rules & subrules became out-of-date:
      'pdflatex'
------------
Run number 1 of rule 'pdflatex'
------------
------------
Running 'pdflatex  -recorder  "paper.tex"'
------------
Rule 'pdflatex': File changes, etc:
   Changed files, or newly in use since previous run(s):
      'paper.aux'
------------
Run number 2 of rule 'pdflatex'
------------
------------
Running 'pdflatex  -recorder  "paper.tex"'
------------
Rule 'pdflatex': File changes, etc:
   Changed files, or newly in use since previous run(s):
      'paper.out'
------------
Run number 3 of rule 'pdflatex'
------------
------------
Running 'pdflatex  -recorder  "paper.tex"'
------------
Failure to make 'paper.pdf'
Collected error summary (may duplicate other messages):
  pdflatex: Command for 'pdflatex' gave return code 1
      Refer to 'paper.log' for details
Looks like we failed to compile the PDF

```

**Comment by odow** [comment]
@JosePereiraUA you're missing the https://github.com/JuliaCon/JuliaConSubmission.jl/blob/master/paper/.latexmkrc file from the template repository.

Do you have any suggestions for reviewers?

**Comment by JosePereiraUA** [comment]
I've added the .latexmkrc file in [this commit](https://github.com/sergio-santos-group/ProtoSyn.jl/commit/50e54b5df01f3bb8f68d7856bc05d6fd79407da9).

From the above-mentioned list, and based on the descriptions provided, **sloede** seems to have some experience with numerical simulations. Besides that, I'd suggest anyone from the [MolSim](https://github.com/JuliaMolSim/MolSim) community.

A question: it seems the bot failed to find one of the DOI in my literature references, is there any action I have to take?

Thank you for your time!
Cheers

**Comment by odow** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/JuliaCon/proceedings-papers/jcon.00106/jcon.00106/10.21105.jcon.00106.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/JuliaCon/proceedings-papers/blob/jcon.00106/jcon.00106/10.21105.jcon.00106.pdf) :page_facing_up: :point_left:

**Comment by odow** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1038/nbt0798-617 is OK
- 10.1146/annurev.biophys.37.032807.125832 is OK
- 10.1038/nature19946 is OK
- 10.1002/pro.4098 is OK
- 10.1126/science.1089427 is OK
- 10.1093/bioinformatics/btq007 is OK
- 10.1038/s41592-020-0848-2 is OK
- 10.1038/s41586-019-1923-7 is OK
- 10.1038/s41586-021-03828-1 is OK
- 10.1038/s41586-021-03819-2 is OK
- 10.1073/pnas.1914677117 is OK
- 10.1002/pro.3235 is OK
- 10.1007/978-1-4939-6637-0_2 is OK
- 10.26682/sjuod.2019.22.1.11 is OK
- 10.1371/journal.pone.0020161 is OK
- 10.1002/jcc.20727 is OK
- 10.1137/141000671 is OK
- 10.1145/3276490 is OK
- 10.1007/978-1-4613-8476-2_1 is OK
- 10.1002/CBIC.202000437 is OK
- 10.1093/BIOINFORMATICS/BTU106 is OK
- 10.1145/3276483 is OK
- 10.1073/pnas.96.10.5486 is OK

MISSING DOIs

- 10.1002/(sici)1097-0134(1999)37:3+<171::aid-prot21>3.0.co;2-z may be a valid DOI for title: Ab initio protein structure prediction of CASP III targets using ROSETTA

INVALID DOIs

- None
```

**Comment by odow** [comment]
@sloede and @jgreener64 are you interested in reviewing this paper for the JuliaCon proceedings?

The submission I'd like you to review is titled: "ProtoSyn.jl: a novel platform for computational molecular manipulation and simulation with a focus on protein design". You can find more information at the top of this Github issue (https://github.com/JuliaCon/proceedings-review/issues/106).

The review process at JuliaCon is based on [JOSS](https://joss.theoj.org): it takes place in a GitHub issue, is open, and author-reviewer-editor conversations are encouraged. If you have any questions please let me know.

This is the pre-review issue. After setting at least 2 reviewers we will start the review process in a seperate thread. In that thread, there will be a check list for each reviewer.

Given the lead-up to Christmas, our deadline for the first round isn't until the end of January, so there's no expectation that you'll start the review now if you are busy. I just need an indication that you're willing, otherwise I will need to find other reviewers. If you're willing, I'll ping you again in early January with a reminder.

**Comment by sloede** [comment]
I already agreed to reviewing two JC proceedings papers, thus I would prefer if someone else could do this one.

**Comment by odow** [comment]
No problem

**Comment by jgreener64** [comment]
Yes I am happy to do it.

**Comment by odow** [comment]
@whedon add @jgreener64 as reviewer

**Comment by whedon** [comment]
OK, @jgreener64 is now a reviewer

**Comment by odow** [comment]
@mfherbst are you interested in reviewing this paper for JuliaCon? Or alternatively, do you have suggestions for other reviewers?

**Comment by mfherbst** [comment]
Sure, why not. I should add though that my next few weeks are super tight, so I don't think I'll manage this before mid March.

**Comment by odow** [comment]
@whedon add @mfherbst as reviewer

**Comment by whedon** [comment]
OK, @mfherbst is now a reviewer

**Comment by odow** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/JuliaCon/proceedings-review/issues/124.
