### ISSUE TITLE
[PRE REVIEW]: DisjunctiveProgramming.jl: Generalized Disjunctive Programming Models and Algorithms for JuMP

### ISSUE THREAD

**Issue by whedon** [JuliaCon/proceedings-review#107]
**Submitting author:** @hdavid16 (<a href="http://orcid.org/0000-0002-7374-1120">Hector Perez</a>)
**Repository:** <a href="https://github.com/hdavid16/DisjunctiveProgramming.jl" target ="_blank">https://github.com/hdavid16/DisjunctiveProgramming.jl</a>
**Version:** 
**Editor:** @matbesancon
**Reviewers:** @sbolusani, @joaquimg
**Managing EiC:** Mathieu Besançon

**Author instructions**

Thanks for submitting your paper to JCON @hdavid16. **Currently, there isn't an JCON editor assigned** to your paper.

The author's suggestion for the handling editor is @matbesancon.

@hdavid16 if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/jcon-reviewers) have already agreed to review for JCON and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JCON submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by hdavid16** [comment]
Oscar Dowson (odow)
Joshua Pulsipher (pulsipher)

**Comment by whedon** [comment]
Failed to discover a `Statement of need` section in paper

**Comment by whedon** [comment]
Wordcount for `paper.tex` is 3421

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.06 s (603.3 files/s, 327966.7 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
CSS                              2            653             33          14577
TeX                              8            282            178           2855
Julia                           13            148            115           1018
JavaScript                       4             38             64            450
Markdown                         2             20              0             71
YAML                             4              2              0             71
Ruby                             1              8              4             45
TOML                             2              4              0             19
HTML                             2              0              0              4
-------------------------------------------------------------------------------
SUM:                            38           1155            394          19110
-------------------------------------------------------------------------------


Statistical information for the repository '3ad177ee84ad6bb5c18a2acc' was
gathered on 2022/10/27.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
hdavid16                         2           609              0          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
hdavid16                    609          100.0          0.0               11.17
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/JuliaCon/proceedings-papers/jcon.00107/jcon.00107/10.21105.jcon.00107.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/JuliaCon/proceedings-papers/blob/jcon.00107/jcon.00107/10.21105.jcon.00107.pdf) :page_facing_up: :point_left:

**Comment by matbesancon** [comment]
@pulsipher would you be available to review this paper?

**Comment by pulsipher** [comment]
> @pulsipher would you be available to review 

I can, my only potential conflict of interest would be that I have helped develop the package.

**Comment by hdavid16** [comment]
> I can, my only potential conflict of interest would be that I have helped develop the package.

I will note that the contents of the paper is prior to any contributions from @pulsipher to the repo.

**Comment by matbesancon** [comment]
whedon add @sbolusani as reviewer

**Comment by matbesancon** [comment]
@whedon add @joaquimg as reviewer

**Comment by matbesancon** [comment]
@whedon add @sbolusani as reviewer

**Comment by whedon** [comment]
You need to assign an editor first.

**Comment by matbesancon** [comment]
@whedon assign @matbesancon as editor

**Comment by whedon** [comment]
OK, the editor is @matbesancon

**Comment by matbesancon** [comment]
@whedon add @sbolusani as reviewer

**Comment by whedon** [comment]
OK, @sbolusani is now a reviewer

**Comment by matbesancon** [comment]
@whedon add @joaquimg as reviewer

**Comment by whedon** [comment]
OK, @joaquimg is now a reviewer

**Comment by matbesancon** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/JuliaCon/proceedings-review/issues/117.
