### ISSUE TITLE
[PRE REVIEW]: MedPipe3D.jl: GPU accelerated medical image segmentation framework

### ISSUE THREAD

**Issue by whedon** [JuliaCon/proceedings-review#108]
**Submitting author:** @jakubMitura14(<a href="http://orcid.org/0000-0003-1823-6823">Jakub Mitura</a>)
**Repository:** <a href=" https://github.com/jakubMitura14/MedPipe3D.jl" target ="_blank"> https://github.com/jakubMitura14/MedPipe3D.jl</a>
**Version:** 
**Editor:** @vchuravy
**Reviewers:** @jpsamaroo, @timholy
**Managing EiC:** Valentin Churavy

**Author instructions**

Thanks for submitting your paper to JCON @https://github.com/jakubMitura14. **Currently, there isn't an JCON editor assigned** to your paper.

The author's suggestion for the handling editor is @vchuravy.

@https://github.com/jakubMitura14 if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/jcon-reviewers) have already agreed to review for JCON and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JCON submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by jakubMitura14** [comment]
sloedesloede

**Comment by jakubMitura14** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List Whedon's capabilities
@whedon commands

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

EDITORIAL TASKS

# Compile the paper
@whedon generate pdf

# Compile the paper from alternative branch
@whedon generate pdf from branch custom-branch-name

# Ask Whedon to check the references for missing DOIs
@whedon check references

# Ask Whedon to check repository statistics for the submitted software
@whedon check repository

```

**Comment by carstenbauer** [comment]
@whedon assign @vchuravy as editor

**Comment by whedon** [comment]
OK, the editor is @vchuravy

**Comment by vchuravy** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List all of Whedon's capabilities
@whedon commands

# Assign a GitHub user as the sole reviewer of this submission
@whedon assign @username as reviewer

# Add a GitHub user to the reviewers of this submission
@whedon add @username as reviewer

# Re-invite a reviewer (if they can't update checklists)
@whedon re-invite @username as reviewer

# Remove a GitHub user from the reviewers of this submission
@whedon remove @username as reviewer

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

# Change editorial assignment
@whedon assign @username as editor

# Set the software archive DOI at the top of the issue e.g.
@whedon set 10.0000/zenodo.00000 as archive

# Set the software version at the top of the issue e.g.
@whedon set v1.0.1 as version

# Open the review issue
@whedon start review

EDITORIAL TASKS

# All commands can be run on a non-default branch, to do this pass a custom 
# branch name by following the command with `from branch custom-branch-name`.
# For example:

# Compile the paper
@whedon generate pdf

# Compile the paper from alternative branch
@whedon generate pdf from branch custom-branch-name

# Remind an author or reviewer to return to a review after a
# certain period of time (supported units days and weeks)
@whedon remind @reviewer in 2 weeks

# Ask Whedon to do a dry run of accepting the paper and depositing with Crossref
@whedon recommend-accept

# Ask Whedon to check the references for missing DOIs
@whedon check references

# Ask Whedon to check repository statistics for the submitted software
@whedon check repository

EiC TASKS

# Invite an editor to edit a submission (sending them an email)
@whedon invite @editor as editor

# Reject a paper
@whedon reject

# Withdraw a paper
@whedon withdraw

# Ask Whedon to actually accept the paper and deposit with Crossref
@whedon accept deposit=true

```

**Comment by vchuravy** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
PDF failed to compile for issue #108 with the following error: 
```
 Can't find any papers to compile :-(

```

**Comment by vchuravy** [comment]
@jakubMitura14 do you have suggestions for reviewers.

**Comment by jakubMitura14** [comment]
For example sloedesloede, but frankly as you consider it convinient

**Comment by jakubMitura14** [comment]
@vchuravy Hello is there anything more I should do?

**Comment by mkitti** [comment]
@sloede , would you like to review?

**Comment by mkitti** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
PDF failed to compile for issue #108 with the following error: 
```
 Can't find any papers to compile :-(

```

**Comment by jakubMitura14** [comment]
[JuliaCon2022Article.pdf](https://github.com/JuliaCon/proceedings-review/files/10950040/JuliaCon2022Article.pdf)

pdf is here and link to overleaf below - I do not know why whedon is unable to compile
https://www.overleaf.com/3256953646dpzjctndcdgb

**Comment by sloede** [comment]
> @sloede , would you like to review?

Sorry, but since this is not really my area of expertise and after having been asked to review two other papers for JuliaCon already, I have to politely decline.

**Comment by jakubMitura14** [comment]
Thank you for the response !
Hence as far as I see in supplied table the only other candidate is @matbesancon

**Comment by mkitti** [comment]
Whedon is probably looking for a paper.md file.
https://joss.readthedocs.io/en/latest/editorial_bot.html?highlight=paper.md#compiling-papers

**Comment by vchuravy** [comment]
@whedon add @jpsamaroo as reviewer

**Comment by whedon** [comment]
OK, @jpsamaroo is now a reviewer

**Comment by vchuravy** [comment]
@whedon add @timholy as reviewer

**Comment by whedon** [comment]
OK, @timholy is now a reviewer

**Comment by vchuravy** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/JuliaCon/proceedings-review/issues/127.
