### ISSUE TITLE
[PRE REVIEW]: GraphPPL.jl: A Julia Package for probabilistic model and inference constraints specification

### ISSUE THREAD

**Issue by whedon** [JuliaCon/proceedings-review#112]
**Submitting author:** @bvdmitri (<a href="http://orcid.org/0000-0001-9655-7986">Dmitry Bagaev</a>)
**Repository:** <a href="https://github.com/biaslab/GraphPPL.jl" target ="_blank">https://github.com/biaslab/GraphPPL.jl</a>
**Version:** 
**Editor:** @matbesancon
**Reviewers:** @theogf, @sethaxen
**Managing EiC:** Valentin Churavy

**Author instructions**

Thanks for submitting your paper to JCON @bvdmitri. **Currently, there isn't an JCON editor assigned** to your paper.

The author's suggestion for the handling editor is @matbesancon.

@bvdmitri if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/jcon-reviewers) have already agreed to review for JCON and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JCON submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
PDF failed to compile for issue #112 with the following error: 
```
 Can't find any papers to compile :-(

```

**Comment by carstenbauer** [comment]
@whedon assign @matbesancon as editor

**Comment by whedon** [comment]
OK, the editor is @matbesancon

**Comment by bvdmitri** [comment]
The paper is in the [`paper/julia_proceedings_2022`](https://github.com/biaslab/GraphPPL.jl/tree/paper/julia_proceedings_2022) branch.

**Comment by matbesancon** [comment]
Hi, thanks for pinging, we are still looking for reviewers on our side

**Comment by matbesancon** [comment]
@whedon add @theogf as reviewer

**Comment by whedon** [comment]
OK, @theogf is now a reviewer

**Comment by whedon** [comment]
OK, @sethaxen is now a reviewer

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch julia_proceedings_2022. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #112 with the following error: 
```
 Can't find any papers to compile :-(

```

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch paper/julia_proceedings_2022. Reticulating splines etc...
```

**Comment by matbesancon** [comment]
@bvdmitri can you check that you didn't modify anything non-standard in the paper folder?

**Comment by bvdmitri** [comment]
@matbesancon  No, last commit has been made more than 4 months ago. I checked it now locally using the following instructions https://juliacon.github.io/proceedings-guide/author/#local_build and it works perfectly.

**Comment by bvdmitri** [comment]
@matbesancon Here is the pdf document generated locally
[paper.pdf](https://github.com/JuliaCon/proceedings-review/files/10437395/paper.pdf)

**Comment by bvdmitri** [comment]
@matbesancon  The official guideline mentions the [Whedon bot](https://whedon.theoj.org/), but it seems to me that it does not support `paper.tex` submissions, which is the only possible way for the JuliaCon Proceedings. Thus I have no possibility to make sure that the `whedon` works without errors. `whedon` docker image and GitHub Action do work with `paper.md` submissions, but I don't see any documentation on how to run them for `paper.tex` submissions. 

The log posted in the previous message is uninformative and does not really help to identify the issue. Is there a way to get an extensive log?

**Comment by matbesancon** [comment]
@bvdmitri one thing to watch out: we need the `.latexrc` file, check the files here:
https://github.com/JuliaCon/JuliaConSubmission.jl/tree/master/paper

**Comment by matbesancon** [comment]
that's why the logs was breaking early

**Comment by bvdmitri** [comment]
@whedon generate pdf from branch paper/julia_proceedings_2022

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch paper/julia_proceedings_2022. Reticulating splines etc...
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/JuliaCon/proceedings-papers/jcon.00112/jcon.00112/10.21105.jcon.00112.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/JuliaCon/proceedings-papers/blob/jcon.00112/jcon.00112/10.21105.jcon.00112.pdf) :page_facing_up: :point_left:

**Comment by bvdmitri** [comment]
@matbesancon Thanks for the help, the article builds without any problem now

**Comment by matbesancon** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/JuliaCon/proceedings-review/issues/123.
