### ISSUE TITLE
[PRE REVIEW]: Interplay between Chaos and Stochasticity in Celestial Mechanics

### ISSUE THREAD

**Issue by whedon** [JuliaCon/proceedings-review#113]
**Submitting author:** @matteoettam09 (<a href="http://orcid.org/0000-0002-5229-0746">Matteo Manzi</a>)
**Repository:** <a href="https://github.com/PoincareTrajectories/FTLE.jl" target ="_blank">https://github.com/PoincareTrajectories/FTLE.jl</a>
**Version:** 
**Editor:** Pending
**Reviewer:** Pending
**Managing EiC:** Valentin Churavy

**Author instructions**

Thanks for submitting your paper to JCON @matteoettam09. **Currently, there isn't an JCON editor assigned** to your paper.

The author's suggestion for the handling editor is @ranjanan.

@matteoettam09 if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/jcon-reviewers) have already agreed to review for JCON and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JCON submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Failed to discover a `Statement of need` section in paper

**Comment by whedon** [comment]
Wordcount for `paper.tex` is 858

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.05 s (478.7 files/s, 239152.3 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
SVG                              1              0              0           7144
TeX                              8            246            188           2397
Julia                           10            183            178            529
Ruby                             1              8              4             45
Markdown                         1             17              0             29
YAML                             1              0              0             22
-------------------------------------------------------------------------------
SUM:                            22            454            370          10166
-------------------------------------------------------------------------------


Statistical information for the repository '94eb9ff96b2d0231011bcbf9' was
gathered on 2022/10/27.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
mmanzi95                         1            57              0          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
mmanzi95                     57          100.0          0.0                7.02
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/JuliaCon/proceedings-papers/jcon.00113/jcon.00113/10.21105.jcon.00113.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/JuliaCon/proceedings-papers/blob/jcon.00113/jcon.00113/10.21105.jcon.00113.pdf) :page_facing_up: :point_left:

**Comment by matteoettam09** [comment]
Mirror of https://github.com/JuliaCon/proceedings-review/issues/111

This repo has been moved back from organization to personal repo. Please ignore this issue.

**Comment by vchuravy** [comment]
@whedon help

**Comment by whedon** [comment]
I'm sorry human, I don't understand that. You can see what commands I support by typing:

```
@whedon commands
```

**Comment by vchuravy** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List all of Whedon's capabilities
@whedon commands

# Assign a GitHub user as the sole reviewer of this submission
@whedon assign @username as reviewer

# Add a GitHub user to the reviewers of this submission
@whedon add @username as reviewer

# Re-invite a reviewer (if they can't update checklists)
@whedon re-invite @username as reviewer

# Remove a GitHub user from the reviewers of this submission
@whedon remove @username as reviewer

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

# Change editorial assignment
@whedon assign @username as editor

# Set the software archive DOI at the top of the issue e.g.
@whedon set 10.0000/zenodo.00000 as archive

# Set the software version at the top of the issue e.g.
@whedon set v1.0.1 as version

# Open the review issue
@whedon start review

EDITORIAL TASKS

# All commands can be run on a non-default branch, to do this pass a custom 
# branch name by following the command with `from branch custom-branch-name`.
# For example:

# Compile the paper
@whedon generate pdf

# Compile the paper from alternative branch
@whedon generate pdf from branch custom-branch-name

# Remind an author or reviewer to return to a review after a
# certain period of time (supported units days and weeks)
@whedon remind @reviewer in 2 weeks

# Ask Whedon to do a dry run of accepting the paper and depositing with Crossref
@whedon recommend-accept

# Ask Whedon to check the references for missing DOIs
@whedon check references

# Ask Whedon to check repository statistics for the submitted software
@whedon check repository

EiC TASKS

# Invite an editor to edit a submission (sending them an email)
@whedon invite @editor as editor

# Reject a paper
@whedon reject

# Withdraw a paper
@whedon withdraw

# Ask Whedon to actually accept the paper and deposit with Crossref
@whedon accept deposit=true

```

**Comment by vchuravy** [comment]
@whedon withdraw

**Comment by whedon** [comment]
Paper withdrawn.
