### ISSUE TITLE
[PRE REVIEW]: High-performance xPU Stencil Computations in Julia

### ISSUE THREAD

**Issue by whedon** [JuliaCon/proceedings-review#114]
**Submitting author:** @omlins (<a href="http://orcid.org/0000-0001-8969-5619">Samuel Omlin</a>)
**Repository:** <a href="https://github.com/omlins/ParallelStencil.jl" target ="_blank">https://github.com/omlins/ParallelStencil.jl</a>
**Version:** 
**Editor:** @fcdimitr
**Reviewers:** @georgebisbas, @sloede
**Managing EiC:** Mathieu Besançon

**Author instructions**

Thanks for submitting your paper to JCON @. **Currently, there isn't an JCON editor assigned** to your paper.

The author's suggestion for the handling editor is @ranjanan.

@ if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/jcon-reviewers) have already agreed to review for JCON and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JCON submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.05 s (1205.1 files/s, 144819.2 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Julia                           55            765            348           5848
Markdown                         1            121              0            374
YAML                             2              3              2             55
TOML                             5              9              1             45
-------------------------------------------------------------------------------
SUM:                            63            898            351           6322
-------------------------------------------------------------------------------


Statistical information for the repository '9a13b3fee7e1c3ca9488ef98' was
gathered on 2022/10/27.
No commited files with the specified extensions were found.
```

**Comment by whedon** [comment]
PDF failed to compile for issue #114 with the following error: 
```
 Can't find any papers to compile :-(

```

**Comment by carstenbauer** [comment]
@whedon assign @ranjanan as editor

**Comment by omlins** [comment]
We would suggest sloede for the review.

**Comment by ranjanan** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
PDF failed to compile for issue #114 with the following error: 
```
 Can't find any papers to compile :-(

```

**Comment by omlins** [comment]
The paper is in the branch https://github.com/omlins/ParallelStencil.jl/tree/JuliaConProceeding2022

**Comment by ranjanan** [comment]
@whedon generate pdf from branch JuliaConProceeding2022

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch JuliaConProceeding2022. Reticulating splines etc...
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/JuliaCon/proceedings-papers/jcon.00114/jcon.00114/10.21105.jcon.00114.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/JuliaCon/proceedings-papers/blob/jcon.00114/jcon.00114/10.21105.jcon.00114.pdf) :page_facing_up: :point_left:

**Comment by matbesancon** [comment]
@whedon assign @fcdimitr as editor

**Comment by fcdimitr** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List Whedon's capabilities
@whedon commands

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

EDITORIAL TASKS

# Compile the paper
@whedon generate pdf

# Compile the paper from alternative branch
@whedon generate pdf from branch custom-branch-name

# Ask Whedon to check the references for missing DOIs
@whedon check references

# Ask Whedon to check repository statistics for the submitted software
@whedon check repository

```

**Comment by fcdimitr** [comment]
@whedon generate pdf from branch JuliaConProceeding2022

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch JuliaConProceeding2022. Reticulating splines etc...
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/JuliaCon/proceedings-papers/jcon.00114/jcon.00114/10.21105.jcon.00114.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/JuliaCon/proceedings-papers/blob/jcon.00114/jcon.00114/10.21105.jcon.00114.pdf) :page_facing_up: :point_left:

**Comment by fcdimitr** [comment]
@whedon assign @fcdimitr as editor

**Comment by whedon** [comment]
I'm sorry @fcdimitr, I'm afraid I can't do that. That's something only editors are allowed to do.

**Comment by fcdimitr** [comment]
@whedon assign @fcdimitr as editor

**Comment by fcdimitr** [comment]
@whedon assign fcdimitr as editor

**Comment by fcdimitr** [comment]
@whedon assign @fcdimitr as editor

**Comment by fcdimitr** [comment]
@whedon list reviewers

**Comment by whedon** [comment]
Here's the current list of reviewers: http://bit.ly/2V9GSFq

**Comment by fcdimitr** [comment]
@whedon assign @georgebisbas as reviewer

**Comment by whedon** [comment]
OK, @georgebisbas is now a reviewer

**Comment by fcdimitr** [comment]
Hi @omlins. I am giving a quick update from my side.

I found a first reviewer. I'll try to find a second one ASAP.

@georgebisbas, thank you for volunteering as a reviewer. You can find more details on the JuliaCon review process [here](https://juliacon.github.io/proceedings-guide/reviewer/). Note this submission is still in pre-review, and the review will start once I find a second reviewer. Meanwhile, feel free to ask me any questions you have.

**Comment by fcdimitr** [comment]
@sloede thank you for volunteering as a reviewer. You can find more details on the JuliaCon review process [here](https://juliacon.github.io/proceedings-guide/reviewer/). Note that this submission is still in pre-review, and the review will start shortly. Meanwhile, feel free to ask me any questions you have.

**Comment by fcdimitr** [comment]
@whedon add @sloede as reviewer

**Comment by whedon** [comment]
OK, @sloede is now a reviewer

**Comment by fcdimitr** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/JuliaCon/proceedings-review/issues/138.
