### ISSUE TITLE
[PRE REVIEW]: JustSayIt.jl: A Fresh Approach to Open Source Voice Assistant Development

### ISSUE THREAD

**Issue by whedon** [JuliaCon/proceedings-review#116]
**Submitting author:** @omlins (<a href="http://orcid.org/0000-0001-8969-5619">Samuel Omlin</a>)
**Repository:** <a href="https://github.com/omlins/JustSayIt.jl" target ="_blank">https://github.com/omlins/JustSayIt.jl</a>
**Version:** 
**Editor:** @carstenbauer
**Reviewers:** @PetrKryslUCSD, @pfitzseb
**Managing EiC:** Valentin Churavy

**Author instructions**

Thanks for submitting your paper to JCON @omlins. **Currently, there isn't an JCON editor assigned** to your paper.

The author's suggestion for the handling editor is @carstenbauer.

@omlins if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/jcon-reviewers) have already agreed to review for JCON and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JCON submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
PDF failed to compile for issue #116 with the following error: 
```
 Can't find any papers to compile :-(

```

**Comment by vchuravy** [comment]
@omlins can you update your OrcID https://github.com/JuliaCon/proceedings-papers/actions/runs/3387758458/jobs/5628908681#step:3:102

**Comment by carstenbauer** [comment]
@whedon assign @carstenbauer as editor

**Comment by whedon** [comment]
OK, the editor is @carstenbauer

**Comment by omlins** [comment]
I would suggest matbesancon as reviewer.

**Comment by carstenbauer** [comment]
@whedon generate pdf from branch JuliaConProceeding2022

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch JuliaConProceeding2022. Reticulating splines etc...
```

**Comment by carstenbauer** [comment]
@whedon add @PetrKryslUCSD as reviewer

**Comment by whedon** [comment]
OK, @PetrKryslUCSD is now a reviewer

**Comment by carstenbauer** [comment]
@whedon add @pfitzseb as reviewer

**Comment by whedon** [comment]
OK, @pfitzseb is now a reviewer

**Comment by carstenbauer** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/JuliaCon/proceedings-review/issues/121.

**Comment by carstenbauer** [comment]
Hey @PetrKryslUCSD, yes, it would be great to get your review in over at https://github.com/JuliaCon/proceedings-review/issues/121
