### ISSUE TITLE
Juliacon proceedings paper submission form error

### ISSUE THREAD

**Issue by pitsianis** [JuliaCon/proceedings-review#131]
We are trying to submit a paper for the Juliacon proceedings (with you as the editor), but we are getting the error.

```quote
                     We're sorry, but something went wrong.
   If you are the application owner check the logs for more information.
```
Please advise us on how to proceed.

**Comment by whedon** [comment]
:wave: This repository is only for review issues (`pre-review` and `review`) that have been created by our editorial infrastructure, and this issue appears not to be one of these.

As such, this issue will be closed. If you're opening an issue as part of a review, please open a new issue instead in the software repository associated with the submission that you are reviewing.

Many thanks!
