### ISSUE TITLE
[REVIEW]: A general-purpose toolbox for efficient Kronecker-based learning

### ISSUE THREAD

**Issue by whedon** [JuliaCon/proceedings-review#15]
**Submitting author:** @michielstock (<a href="http://orcid.org/0000-0003-0903-6061">Michiel Stock</a>)
**Repository:** <a href="https://github.com/michielStock/Kronecker.jl" target ="_blank">https://github.com/michielStock/Kronecker.jl</a>
**Editor:** @matbesancon
**Reviewer:** @christianpeel, @mcognetta
**Archive:** <a href="https://doi.org/10.5281/zenodo.3463941" target="_blank">10.5281/zenodo.3463941</a>

## Status

[![status](https://proceedings.juliacon.org/papers/069e10666535d05b3a2d06023a1e4923/status.svg)](https://proceedings.juliacon.org/papers/069e10666535d05b3a2d06023a1e4923)

Status badge code:

```
HTML: <a href="https://submissions.juliacon.org/papers/069e10666535d05b3a2d06023a1e4923"><img src="https://submissions.juliacon.org/papers/069e10666535d05b3a2d06023a1e4923/status.svg"></a>
Markdown: [![status](https://submissions.juliacon.org/papers/069e10666535d05b3a2d06023a1e4923/status.svg)](https://submissions.juliacon.org/papers/069e10666535d05b3a2d06023a1e4923)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/michielStock/Kronecker.jl" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@christianpeel & @mcognetta, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/JuliaCon/proceedings-reviews/invitations

The reviewer guidelines are available here: https://proceedings.juliacon.org/guide/reviewers. Any questions/concerns please let @matbesancon know.

✨ **Please try and complete your review in the next two weeks** ✨

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JuliaCon conflict of interest policy](https://proceedings.juliacon.org/guide/authors#coi) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JuliaCon code of conduct](https://proceedings.juliacon.org/coc).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/michielStock/Kronecker.jl">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Authorship:** Has the submitting author (@michielstock) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Paper format

- [x] **Authors:** Does the `paper.tex` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?
- [x] **Page limit:** Is the page limit for extended abstracts respected by the submitted document?

### Content

- [x] **Context:** is the scientific context motivating the work correctly presented?
- [x] **Methodology:** is the approach taken in the work justified, presented with enough details and reference to reproduce it?
- [x] **Results:** are the results presented and compared to approaches with similar goals?

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JuliaCon conflict of interest policy](https://proceedings.juliacon.org/guide/authors#coi) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JuliaCon code of conduct](https://proceedings.juliacon.org/coc).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/michielStock/Kronecker.jl">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Authorship:** Has the submitting author (@michielstock) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [ ] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Paper format

- [x] **Authors:** Does the `paper.tex` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?
- [x] **Page limit:** Is the page limit for extended abstracts respected by the submitted document?

### Content

- [x] **Context:** is the scientific context motivating the work correctly presented?
- [x] **Methodology:** is the approach taken in the work justified, presented with enough details and reference to reproduce it?
- [x] **Results:** are the results presented and compared to approaches with similar goals?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @christianpeel, @mcognetta it looks like you're currently assigned to review this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/JuliaCon/proceedings-review) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/JuliaCon/proceedings-review:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/JuliaCon/proceedings-papers/blob/jcon.00015/jcon.00015/10.21105.jcon.00015.pdf)

**Comment by matbesancon** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1016/S0377-0427(00)00393-9 is OK

MISSING DOIs

- https://doi.org/10.1162/neco_a_01096 may be missing for title: A comparative study of pairwise learning methods based on kernel ridge regression
- https://doi.org/10.1109/tnnls.2017.2727545 may be missing for title: Fast Kronecker product kernel methods via generalized vec trick

INVALID DOIs

- 10.1145/1756006.1756039 is INVALID
```

**Comment by MichielStock** [comment]
Are added to the `ref.bib`, but these don't appear in the paper, as dictated by the style file.

@whedon check references

**Comment by christianpeel** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/JuliaCon/proceedings-papers/blob/jcon.00015/jcon.00015/10.21105.jcon.00015.pdf)

**Comment by christianpeel** [comment]
I recommend that the paper be **accepted as-is**.

**Comment by mcognetta** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List Whedon's capabilities
@whedon commands

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

EDITORIAL TASKS

# Compile the paper
@whedon generate pdf

# Compile the paper from alternative branch
@whedon generate pdf from branch custom-branch-name

# Ask Whedon to check the references for missing DOIs
@whedon check references

```

**Comment by mcognetta** [comment]
**Recommendation:** accept with **minor modifications**.

-----------------------------------------------------------------

Minor paper comments:
1. 'vec trick' is two words in one place but one word (hyphenated) in another.
2. In Section 3:
> To fully make use the power of Julia, we will explore three directions. 

Should be '...make use _of_ the...'

3. The citation for vec trick should be given at the first mention of vec trick (but including it for both is also fine).

Minor code comments:
1. The `show` method should be improved to be similar to printing large dense matrices. Currently it does nothing.
2. To convert to a dense matrix, `collect` must be called. It makes sense to have a `Matrix` constructor as well.
3. Many instances of unnecessary `where` statements when the type parameter is unused. For example:
https://github.com/MichielStock/Kronecker.jl/blob/a1d9d068555ff74cf99771bdbc68b71e8a90a7be/src/base.jl#L54
https://github.com/MichielStock/Kronecker.jl/blob/a1d9d068555ff74cf99771bdbc68b71e8a90a7be/src/base.jl#L77

**Comment by MichielStock** [comment]
Thank you for all the feedback and suggestions. I updated the code today, providing better integration with the `AbstractArray` interface. I will update the documentation and push to master branch.

**Comment by matbesancon** [comment]
@MichielStock can you let us know when you have done the changes?

**Comment by MichielStock** [comment]
I have done the changes and merged them into the `master` branch.

**Comment by christianpeel** [comment]
I very much like the plot of benchmark times that you added to the Readme.

**Comment by matbesancon** [comment]
ping @mcognetta to continue the review

**Comment by mcognetta** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/JuliaCon/proceedings-papers/blob/jcon.00015/jcon.00015/10.21105.jcon.00015.pdf)

**Comment by matbesancon** [comment]
@mcognetta how are you doing on the review here?

**Comment by mcognetta** [comment]
In light of the revisions, I am changing my recommendation to **accept as-is.**

**Comment by matbesancon** [comment]
@MichielStock a couple additional comments:
Section 1: "In linear algebra" -> is it necessary, given that the context is operations over matrices?

"gives rises to some elegant mathematics", elegant is a bit odd to see (hard to define). To some properties of interest?

"The elementary functions of `LinearAlgebra`" -> "The elementary functions of the `LinearAlgebra` module from the Julia standard library".

I would indicate more clearly that "vec trick" is a standard term in the literate, by using quotes and hints like "so-called vec trick" with the reference to [5]. I would not use "tricks from linear algebra" in the abstract as it sounds a bit informal.

3. Prospects

Could you cite the packages you are referencing by adding a bibtex entry? (Zygote, CuArrays), also: CuArrays -> CuArrays.jl

**Comment by MichielStock** [comment]
These comments are now done as of d33dc39371e26083b43f955df7855879884e449c

**Comment by matbesancon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/JuliaCon/proceedings-papers/blob/jcon.00015/jcon.00015/10.21105.jcon.00015.pdf)

**Comment by matbesancon** [comment]
> Alternatively, one can make use of Julia's Unicode support: `K = A \cross B`

Can you make K = A cross B an equation as to have it all on the same line?

> overloaded to work with the `Kronecker` type.

As I understand, there are several `Kronecker` types, should it be pluralized?

The last sentence of section 2 feels like a conclusion and prospect, should it go at the beginning of section 3?

At the end of section 3, could you add some more details on the extensions for high-order Kronecker products? (not a big deal if the text is a bit above 1 page)

**Comment by MichielStock** [comment]
Updated. Also added a section on higher-order Kronecker products, which are now supported.

**Comment by matbesancon** [comment]
Still the code snippet to turn into equation:

> Alternatively, one can make use of Julia's Unicode support: K = A \cross B

> Can you make K = A cross B an equation as to have it all on the same line?

**Comment by MichielStock** [comment]
Done in af1d3ced <https://github.com/MichielStock/Kronecker.jl/commit/af1d3cedb2e58902eead8584f3e04e9ddcab5ea1>. Would be nice to wrap this up.

**Comment by matbesancon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/JuliaCon/proceedings-papers/blob/jcon.00015/jcon.00015/10.21105.jcon.00015.pdf)

**Comment by matbesancon** [comment]
Looks good here

**Comment by matbesancon** [comment]
@whedon accept

**Comment by whedon** [comment]
No archive DOI set. Exiting...

**Comment by matbesancon** [comment]
ah right.
@MichielStock the next steps are: archiving the code repo with Zenodo to obtain a DOI, we'll then be able to attach the DOI to the paper

**Comment by MichielStock** [comment]
Registered to Zenodo and a badge is added to the `readme.md`: [![DOI](https://zenodo.org/badge/160198570.svg)](https://zenodo.org/badge/latestdoi/160198570)

**Comment by matbesancon** [comment]
@whedon set doi 10.5281/zenodo.3463941

**Comment by matbesancon** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List all of Whedon's capabilities
@whedon commands

# Assign a GitHub user as the sole reviewer of this submission
@whedon assign @username as reviewer

# Add a GitHub user to the reviewers of this submission
@whedon add @username as reviewer

# Remove a GitHub user from the reviewers of this submission
@whedon remove @username as reviewer

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

# Change editorial assignment
@whedon assign @username as editor

# Set the software archive DOI at the top of the issue e.g.
@whedon set 10.0000/zenodo.00000 as archive

# Set the software version at the top of the issue e.g.
@whedon set v1.0.1 as version

# Open the review issue
@whedon start review

EDITORIAL TASKS

# Compile the paper
@whedon generate pdf

# Compile the paper from alternative branch
@whedon generate pdf from branch custom-branch-name

# Remind an author or reviewer to return to a review after a
# certain period of time (supported units days and weeks)
@whedon remind @reviewer in 2 weeks

# Ask Whedon to accept the paper and deposit with Crossref
@whedon accept

# Ask Whedon to check the references for missing DOIs
@whedon check references

```

**Comment by matbesancon** [comment]
@whedon set 10.5281/zenodo.3463941 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.3463941" target="_blank">10.5281/zenodo.3463941</a> is the archive.

**Comment by matbesancon** [comment]
@whedon set v0.3.0 as version

**Comment by whedon** [comment]
OK. v0.3.0 is the version.

**Comment by matbesancon** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1109/TPDS.2018.2872064 is OK
- 10.1162/neco_a_01096 is OK
- 10.1109/TNNLS.2017.2727545 is OK
- 10.1016/S0377-0427(00)00393-9 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
Check final proof :point_right: https://github.com/JuliaCon/proceedings-papers/pull/5

If the paper PDF and Crossref deposit XML look good in https://github.com/JuliaCon/proceedings-papers/pull/5, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by matbesancon** [comment]
@MichielStock all good here, congratulations

**Comment by matbesancon** [comment]
(we will run all the final accept in batch at the end)

**Comment by arfon** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1109/TPDS.2018.2872064 is OK
- 10.1162/neco_a_01096 is OK
- 10.1109/TNNLS.2017.2727545 is OK
- 10.1016/S0377-0427(00)00393-9 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:wave: @JuliaCon/jcon-eics, this paper is ready to be accepted and published.

 Check final proof :point_right: https://github.com/JuliaCon/proceedings-papers/pull/9

If the paper PDF and Crossref deposit XML look good in https://github.com/JuliaCon/proceedings-papers/pull/9, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by arfon** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
I'm sorry @arfon, I'm afraid I can't do that. That's something only editor-in-chiefs are allowed to do.

**Comment by arfon** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JCON!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/JuliaCon/proceedings-papers/pull/10
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/jcon.00015](https://doi.org/10.21105/jcon.00015)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? Notify your editorial technical team...

**Comment by arfon** [comment]
@vchuravy @matbesancon - looks like this is mostly working now 😄 so I'm going to close this issue.

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://proceedings.juliacon.org/papers/10.21105/jcon.00015/status.svg)](https://doi.org/10.21105/jcon.00015)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/jcon.00015">
  <img src="https://proceedings.juliacon.org/papers/10.21105/jcon.00015/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://proceedings.juliacon.org/papers/10.21105/jcon.00015/status.svg
   :target: https://doi.org/10.21105/jcon.00015
```
This is how it will look in your documentation:

[![DOI](https://proceedings.juliacon.org/papers/10.21105/jcon.00015/status.svg)](https://doi.org/10.21105/jcon.00015)

**We need your help!**

JuliaCon Proceedings is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://forms.gle/yANMe4c9YmuW9MWcA
- Making a small donation to support our running costs here: https://numfocus.salsalabs.org/donate-to-jcon
