### ISSUE TITLE
[PRE REVIEW]: Locality-Aware Message Passing with ArrayChannels.jl

### ISSUE THREAD

**Issue by whedon** [JuliaCon/proceedings-review#16]
**Submitting author:** @rohanmclure (<a href="http://orcid.org/0000-0002-7018-5501">Rohan McLure</a>)
**Repository:** <a href="https://github.com/rohanmclure/ArrayChannels.jl" target ="_blank">https://github.com/rohanmclure/ArrayChannels.jl</a>
**Editor:** @vchuravy
**Reviewers:** @jpsamaroo

**Author instructions**

Thanks for submitting your paper to JuliaCon @rohanmclure. The JuliaCon editor @vchuravy, will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@rohanmclure if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](http://bit.ly/2V9GSFq) have already agreed to review for JuliaCon and may be suitable for this submission.

**Editor instructions**

The JuliaCon submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @vchuravy it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for the assigned editor (@vchuravy) to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](http://bit.ly/2V9GSFq) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
Failed to discover a valid open source license.

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/JuliaCon/proceedings-papers/blob/jcon.00016/jcon.00016/10.21105.jcon.00016.pdf)

**Comment by rohanmclure** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List Whedon's capabilities
@whedon commands

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

EDITORIAL TASKS

# Compile the paper
@whedon generate pdf

# Compile the paper from alternative branch
@whedon generate pdf from branch custom-branch-name

# Ask Whedon to check the references for missing DOIs
@whedon check references

```

**Comment by vchuravy** [comment]
@jpsamaroo mentioned he might be interested in reviewing.

@rohanmclure do you have any suggestions from your side?

**Comment by rohanmclure** [comment]
Very happy to have @jpsamaroo review the submission. It would be good to hear recommendations on figure formatting. Thanks

**Comment by vchuravy** [comment]
@whedon add @jpsamaroo as reviewer

**Comment by whedon** [comment]
OK, @jpsamaroo is now a reviewer

**Comment by vchuravy** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/JuliaCon/proceedings-review/issues/20. Feel free to close this issue now!
