### ISSUE TITLE
[PRE REVIEW]: Differential geometric algebra using Leibniz, Grassmann

### ISSUE THREAD

**Issue by whedon** [JuliaCon/proceedings-review#17]
**Submitting author:** @chakravala (<a href="http://orcid.org/0000-0002-8006-7816">Michael Reed</a>)
**Repository:** <a href="https://github.com/chakravala/Grassmann.jl" target ="_blank">https://github.com/chakravala/Grassmann.jl</a>
**Editor:** @matbesancon
**Reviewers:** @eschnett, @snoeyink

**Author instructions**

Thanks for submitting your paper to JuliaCon @chakravala. The JuliaCon editor @matbesancon, will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@chakravala if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](http://bit.ly/2V9GSFq) have already agreed to review for JuliaCon and may be suitable for this submission.

**Editor instructions**

The JuliaCon submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @matbesancon it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for the assigned editor (@matbesancon) to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](http://bit.ly/2V9GSFq) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #17 with the following error: 

 rm: cannot remove '*.aux': No such file or directory
Latexmk: This is Latexmk, John Collins, 17 Jan. 2018, version: 4.55.
Rule 'pdflatex': Rules & subrules not known to be previously run:
   pdflatex
Rule 'pdflatex': The following rules & subrules became out-of-date:
      'pdflatex'
------------
Run number 1 of rule 'pdflatex'
------------
------------
Running 'pdflatex  -recorder  "paper.tex"'
------------
===========Latexmk: Missing input file: 'dirtytalk.sty' from line
  '! LaTeX Error: File `dirtytalk.sty' not found.'
Latexmk: Missing input file: 'dirtytalk.sty' from line
  '! LaTeX Error: File `dirtytalk.sty' not found.'
Failure to make 'paper.pdf'
Collected error summary (may duplicate other messages):
  pdflatex: Command for 'pdflatex' gave return code 1
      Refer to 'paper.log' for details
Looks like we failed to compile the PDF

**Comment by chakravala** [comment]
@eschnett would you be interested in taking a look at this submission?

you might need to use `lualatex` to compile it and also some extra packages

I have already done some Travis CI compile testing using `lualatex` with this configuration:
https://github.com/chakravala/Math-Research-Notes/blob/master/.travis.yml

which automatically generated and uploaded this PDF file on [![DropBox](https://img.shields.io/badge/download_PDF-DropBox-blue.svg)](https://www.dropbox.com/sh/tphh6anw0qwija4/AAACiaXig5djrLVAKLPFmGV-a/Geometric-Algebra?preview=grassmann-juliacon-2019.pdf)

**Comment by matbesancon** [comment]
hi @chakravala, can you include in your repository the required dependencies, it should work all the way with the whedon workflow before reviewers can look at it

**Comment by eschnett** [comment]
@matbesancon I can review the paper. I'm using the `Grassmann.jl` package myself, but there is no conflict of interest.

**Comment by matbesancon** [comment]
Thanks!
@whedon add @eschnett as reviewer

**Comment by matbesancon** [comment]
@whedon add @eschnett as reviewer

**Comment by matbesancon** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List all of Whedon's capabilities
@whedon commands

# Assign a GitHub user as the sole reviewer of this submission
@whedon assign @username as reviewer

# Add a GitHub user to the reviewers of this submission
@whedon add @username as reviewer

# Remove a GitHub user from the reviewers of this submission
@whedon remove @username as reviewer

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

# Change editorial assignment
@whedon assign @username as editor

# Set the software archive DOI at the top of the issue e.g.
@whedon set 10.0000/zenodo.00000 as archive

# Set the software version at the top of the issue e.g.
@whedon set v1.0.1 as version

# Open the review issue
@whedon start review

EDITORIAL TASKS

# Compile the paper
@whedon generate pdf

# Compile the paper from alternative branch
@whedon generate pdf from branch custom-branch-name

# Remind an author or reviewer to return to a review after a
# certain period of time (supported units days and weeks)
@whedon remind @reviewer in 2 weeks

# Ask Whedon to accept the paper and deposit with Crossref
@whedon accept

# Ask Whedon to check the references for missing DOIs
@whedon check references

```

**Comment by matbesancon** [comment]
@whedon add @eschnett as reviewer

**Comment by whedon** [comment]
OK, @eschnett is now a reviewer

**Comment by matbesancon** [comment]
@snoeyink would you be interested in reviewing this proceeding?

**Comment by snoeyink** [comment]
Sure.  Tell me how to go about it, as I have not reviewed for JuliaCon before.  
(Though I have for many conferences and journals.)

Jack Snoeyink@cs.unc.edu
Computer Science, UNC Chapel Hill

**Comment by matbesancon** [comment]
great thanks. This issue will be closed with a new one starting for the review. You can discuss and request modifications to the paper and package in the issue or post issues in Grassmann.jl directly.

**Comment by matbesancon** [comment]
@whedon add @snoeyink as reviewer

**Comment by whedon** [comment]
OK, @snoeyink is now a reviewer

**Comment by matbesancon** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/JuliaCon/proceedings-review/issues/18. Feel free to close this issue now!
