### ISSUE TITLE
[PRE REVIEW]: Econometrics.jl

### ISSUE THREAD

**Issue by whedon** [JuliaCon/proceedings-review#19]
**Submitting author:** @Nosferican (<a href="http://orcid.org/0000-0002-8406-6175">José Bayoán Santiago Calderón</a>)
**Repository:** <a href="https://github.com/Nosferican/Econometrics.jl" target ="_blank">https://github.com/Nosferican/Econometrics.jl</a>
**Editor:** @matbesancon
**Reviewers:** @cpfiffer, @pkofod

**Author instructions**

Thanks for submitting your paper to JuliaCon @Nosferican. The JuliaCon editor @matbesancon, will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@Nosferican if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](http://bit.ly/2V9GSFq) have already agreed to review for JuliaCon and may be suitable for this submission.

**Editor instructions**

The JuliaCon submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @matbesancon it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for the assigned editor (@matbesancon) to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](http://bit.ly/2V9GSFq) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/JuliaCon/proceedings-papers/blob/jcon.00019/jcon.00019/10.21105.jcon.00019.pdf)

**Comment by vchuravy** [comment]
@andreasnoack might be a good candidate as a reviewer

**Comment by Nosferican** [comment]
@dmbates could be a good candidate reviewer too.

**Comment by matbesancon** [comment]
@andreasnoack @dbmates could you review this proceeding?

**Comment by matbesancon** [comment]
@aviks would you be willing to review this proceeding?

**Comment by matbesancon** [comment]
@pkofod would you like to review this?

**Comment by Nosferican** [comment]
Bump.

**Comment by matbesancon** [comment]
@whedon add @cpfiffer as reviewer

**Comment by whedon** [comment]
OK, @cpfiffer is now a reviewer

**Comment by pkofod** [comment]
I'll review it.

**Comment by matbesancon** [comment]
@whedon add @pkofod as reviewer

**Comment by whedon** [comment]
OK, @pkofod is now a reviewer

**Comment by matbesancon** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/JuliaCon/proceedings-review/issues/38. Feel free to close this issue now!
