### ISSUE TITLE
[REVIEW]: Locality-Aware Message Passing with ArrayChannels.jl

### ISSUE THREAD

**Issue by whedon** [JuliaCon/proceedings-review#20]
**Submitting author:** @rohanmclure (<a href="http://orcid.org/0000-0002-7018-5501">Rohan McLure</a>)
**Repository:** <a href="https://github.com/rohanmclure/ArrayChannels.jl" target ="_blank">https://github.com/rohanmclure/ArrayChannels.jl</a>
**Editor:** @vchuravy
**Reviewer:** @jpsamaroo
**Archive:** <a href="https://doi.org/10.5281/zenodo.3961608" target="_blank">10.5281/zenodo.3961608</a>

## Status

[![status](https://proceedings.juliacon.org/papers/ad154d81eddb5a0e6ce7237ec5b6fa59/status.svg)](https://proceedings.juliacon.org/papers/ad154d81eddb5a0e6ce7237ec5b6fa59)

Status badge code:

```
HTML: <a href="https://submissions.juliacon.org/papers/ad154d81eddb5a0e6ce7237ec5b6fa59"><img src="https://submissions.juliacon.org/papers/ad154d81eddb5a0e6ce7237ec5b6fa59/status.svg"></a>
Markdown: [![status](https://submissions.juliacon.org/papers/ad154d81eddb5a0e6ce7237ec5b6fa59/status.svg)](https://submissions.juliacon.org/papers/ad154d81eddb5a0e6ce7237ec5b6fa59)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/rohanmclure/ArrayChannels.jl" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@jpsamaroo, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/JuliaCon/proceedings-reviews/invitations

The reviewer guidelines are available here: https://proceedings.juliacon.org/guide/reviewers. Any questions/concerns please let @vchuravy know.

✨ **Please try and complete your review in the next two weeks** ✨

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JuliaCon conflict of interest policy](https://proceedings.juliacon.org/guide/authors#coi) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JuliaCon code of conduct](https://proceedings.juliacon.org/coc).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/rohanmclure/ArrayChannels.jl">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Authorship:** Has the submitting author (@rohanmclure) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Paper format

- [x] **Authors:** Does the `paper.tex` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?
- [x] **Page limit:** Is the page limit for full papers respected by the submitted document?

### Content

- [x] **Context:** is the scientific context motivating the work correctly presented?
- [x] **Methodology:** is the approach taken in the work justified, presented with enough details and reference to reproduce it?
- [x] **Results:** are the results presented and compared to approaches with similar goals?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @jpsamaroo it looks like you're currently assigned to review this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/JuliaCon/proceedings-review) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/JuliaCon/proceedings-review:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/JuliaCon/proceedings-papers/blob/jcon.00020/jcon.00020/10.21105.jcon.00020.pdf)

**Comment by rohanmclure** [comment]
Have just updated build instructions, as well as provided a Binder and Dockerfile.

**Comment by rohanmclure** [comment]
Sorry about the wait in acting on those issues, I have been in transit. I have addressed the four issues, and will set up CircleCI / Travis soon for CI, but testing documentation has been provided in `README.md`.

The Binder link should now provide a Jupyter notebook with Julia 1.1.0 and Python 3 kernels available.

**Comment by jpsamaroo** [comment]
Great! Is it possible to create DOI references for the lecture and screencast at the end of the `ref.bib`?

**Comment by rohanmclure** [comment]
> Great! Is it possible to create DOI references for the lecture and screencast at the end of the `ref.bib`?

I don't have any way to generate DOI links, however I can provide URLs for each of them.

**Comment by vchuravy** [comment]
You can deposit them with Zenodo.

**Comment by rohanmclure** [comment]
I have the DOI links submitted now, thanks.

**Comment by jpsamaroo** [comment]
Thanks for that! I'm doing my best to make time to finish up my review of the code functionality/performance and paper content; in the meantime, please check out the following file for my comments on the paper so far: [ArrayChannels-review](https://git.sr.ht/~jpsamaroo/ArrayChannels-review/tree/master/paper.md)

**Comment by rohanmclure** [comment]
Thanks Julian, appreciate your comments, and will submit another commit acknowledging them tonight.

**Comment by rohanmclure** [comment]
Hi Julian, I've responded to your recommendations so far. Thanks!

**Comment by jpsamaroo** [comment]
`@whedon commands`

**Comment by jpsamaroo** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/JuliaCon/proceedings-papers/blob/jcon.00020/jcon.00020/10.21105.jcon.00020.pdf)

**Comment by jpsamaroo** [comment]
Ok, I've ticked off all the boxes, although I still have a few nitpicks here-and-there for both the paper and the code. I'll point these out with issues on the ArrayChannels.jl repository as I encounter them. Great work with this paper and the resulting code, I look forward to using it :smile:

@vchuravy

**Comment by vchuravy** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1137/141000671 is OK
- 10.1145/2048066.2048126 is OK
- 10.1109/HPEC.2014.7040972 is OK
- 10.1145/1378704.1378723 is OK
- 10.5281/zenodo.3339238 is OK

MISSING DOIs

- None

INVALID DOIs

- 10.1016/C2011-004251-5 is INVALID
- 10.5281/zenodo.3339229 is INVALID
```

**Comment by vchuravy** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1137/141000671 is OK
- 10.1145/2048066.2048126 is OK
- 10.1109/HPEC.2014.7040972 is OK
- 10.1145/1378704.1378723 is OK
- 10.5281/zenodo.3339238 is OK

MISSING DOIs

- None

INVALID DOIs

- 10.1016/C2011-004251-5 is INVALID
- 10.5281/zenodo.3339229 is INVALID
```

**Comment by vchuravy** [comment]
@rohanmclure thank you for your patience, can you fix the DOIs? And is there an archival DOI for the associated code that you would like to associate with the publication?
https://joss.readthedocs.io/en/latest/editing.html#after-reviewers-recommend-acceptance

**Comment by rohanmclure** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1137/141000671 is OK
- 10.1145/2048066.2048126 is OK
- 10.1109/HPEC.2014.7040972 is OK
- 10.1145/1378704.1378723 is OK
- 10.5281/zenodo.3339238 is OK

MISSING DOIs

- None

INVALID DOIs

- 10.1016/C2011-004251-5 is INVALID
- 10.5281/zenodo.3339229 is INVALID
```

**Comment by rohanmclure** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1137/141000671 is OK
- 10.1016/C2011-0-04251-5 is OK
- 10.1145/2048066.2048126 is OK
- 10.1109/HPEC.2014.7040972 is OK
- 10.1145/1378704.1378723 is OK
- 10.5281/zenodo.3339229 is OK
- 10.5281/zenodo.3339238 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by rohanmclure** [comment]
@whedon set 10.5281/zenodo.3961608 as archive

**Comment by whedon** [comment]
I'm sorry @rohanmclure, I'm afraid I can't do that. That's something only editors are allowed to do.

**Comment by rohanmclure** [comment]
Oops! That is the DOI for the code archive.

**Comment by vchuravy** [comment]
@whedon set 10.5281/zenodo.3961608 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.3961608" target="_blank">10.5281/zenodo.3961608</a> is the archive.

**Comment by vchuravy** [comment]
@whedon set 1.0.0 as version

**Comment by whedon** [comment]
OK. 1.0.0 is the version.

**Comment by vchuravy** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1137/141000671 is OK
- 10.1016/C2011-0-04251-5 is OK
- 10.1145/2048066.2048126 is OK
- 10.1109/HPEC.2014.7040972 is OK
- 10.1145/1378704.1378723 is OK
- 10.5281/zenodo.3339229 is OK
- 10.5281/zenodo.3339238 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:wave: @JuliaCon/jcon-eics, this paper is ready to be accepted and published.

 Check final proof :point_right: https://github.com/JuliaCon/proceedings-papers/pull/19

If the paper PDF and Crossref deposit XML look good in https://github.com/JuliaCon/proceedings-papers/pull/19, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by vchuravy** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JCON!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/JuliaCon/proceedings-papers/pull/20
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/jcon.00020](https://doi.org/10.21105/jcon.00020)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? Notify your editorial technical team...

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://proceedings.juliacon.org/papers/10.21105/jcon.00020/status.svg)](https://doi.org/10.21105/jcon.00020)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/jcon.00020">
  <img src="https://proceedings.juliacon.org/papers/10.21105/jcon.00020/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://proceedings.juliacon.org/papers/10.21105/jcon.00020/status.svg
   :target: https://doi.org/10.21105/jcon.00020
```
This is how it will look in your documentation:

[![DOI](https://proceedings.juliacon.org/papers/10.21105/jcon.00020/status.svg)](https://doi.org/10.21105/jcon.00020)

**We need your help!**

JuliaCon Proceedings is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://forms.gle/yANMe4c9YmuW9MWcA
- Making a small donation to support our running costs here: https://numfocus.salsalabs.org/donate-to-jcon
