### ISSUE TITLE
[PRE REVIEW]: Interoperating Deep Learning models with ONNX.jl

### ISSUE THREAD

**Issue by whedon** [JuliaCon/proceedings-review#21]
**Submitting author:** @ayush-1506 (<a href="http://orcid.org/0000-0003-3550-691X">Ayush Shridhar</a>)
**Repository:** <a href="https://github.com/FluxML/ONNX.jl" target ="_blank">https://github.com/FluxML/ONNX.jl</a>
**Editor:** @vchuravy
**Reviewers:** @ekinakyurek, @NiklasGustafsson

**Author instructions**

Thanks for submitting your paper to JuliaCon @ayush-1506. The JuliaCon editor @vchuravy, will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@ayush-1506 if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](http://bit.ly/2V9GSFq) have already agreed to review for JuliaCon and may be suitable for this submission.

**Editor instructions**

The JuliaCon submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @vchuravy it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for the assigned editor (@vchuravy) to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](http://bit.ly/2V9GSFq) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #21 with the following error: 

 rm: cannot remove '*.aux': No such file or directory
Latexmk: This is Latexmk, John Collins, 17 Jan. 2018, version: 4.55.
Rule 'pdflatex': Rules & subrules not known to be previously run:
   pdflatex
Rule 'pdflatex': The following rules & subrules became out-of-date:
      'pdflatex'
------------
Run number 1 of rule 'pdflatex'
------------
------------
Running 'pdflatex  -recorder  "paper.tex"'
------------
Latexmk: List of undefined refs and citations:
  Citation `CuArrays' on page 1 undefined on input line 14
  Citation `DBLP:journals/corr/abs-1810-07951' on page 1 undefined on input line 14
  Citation `besard:2017' on page 1 undefined on input line 14
  Citation `bezanson2017julia' on page 1 undefined on input line 14
  Citation `innes:2018' on page 1 undefined on input line 14
Latexmk: Summary of warnings:
  Latex failed to resolve 5 citation(s)
Rule 'pdflatex': File changes, etc:
   Changed files, or newly in use since previous run(s):
      'paper.aux'
------------
Run number 2 of rule 'pdflatex'
------------
------------
Running 'pdflatex  -recorder  "paper.tex"'
------------
Latexmk: List of undefined refs and citations:
  Citation `CuArrays' on page 1 undefined on input line 14
  Citation `DBLP:journals/corr/abs-1810-07951' on page 1 undefined on input line 14
  Citation `besard:2017' on page 1 undefined on input line 14
  Citation `bezanson2017julia' on page 1 undefined on input line 14
  Citation `innes:2018' on page 1 undefined on input line 14
Latexmk: Summary of warnings:
  Latex failed to resolve 5 citation(s)
Rule 'pdflatex': File changes, etc:
   Changed files, or newly in use since previous run(s):
      'paper.out'
------------
Run number 3 of rule 'pdflatex'
------------
------------
Running 'pdflatex  -recorder  "paper.tex"'
------------
Latexmk: List of undefined refs and citations:
  Citation `CuArrays' on page 1 undefined on input line 14
  Citation `DBLP:journals/corr/abs-1810-07951' on page 1 undefined on input line 14
  Citation `besard:2017' on page 1 undefined on input line 14
  Citation `bezanson2017julia' on page 1 undefined on input line 14
  Citation `innes:2018' on page 1 undefined on input line 14
Latexmk: Summary of warnings:
  Latex failed to resolve 5 citation(s)
Failure to make 'paper.pdf'
Collected error summary (may duplicate other messages):
  pdflatex: Command for 'pdflatex' gave return code 1
      Refer to 'paper.log' for details
Looks like we failed to compile the PDF

**Comment by vchuravy** [comment]
@whedon  commands

**Comment by vchuravy** [comment]
@NiklasGustafsson  would you be interested in reviewing this paper? https://proceedings.juliacon.org/guide/reviewers/

**Comment by vchuravy** [comment]
@whedon add @ekinakyurek as reviewer

**Comment by whedon** [comment]
OK, @ekinakyurek is now a reviewer

**Comment by vchuravy** [comment]
@ayush-1506 please make sure that your submission compiles with whedon

**Comment by NiklasGustafsson** [comment]
Sure, I can help review.

**Comment by vchuravy** [comment]
@whedon add @NiklasGustafsson as reviewer

**Comment by whedon** [comment]
OK, @NiklasGustafsson is now a reviewer

**Comment by vchuravy** [comment]
Thank you. As soon as Ayush has fixed the paper I will start the review process.

Take a look at https://proceedings.juliacon.org/guide/reviewers/ in the meanwhile and I am happy to answer questions.

**Comment by ayush-1506** [comment]
@vchuravy Thanks a lot. I'll be targeting the special edition, not the JuliaCon proceedings, since I wasn't able to make it to JuliaCon this year (I created this PR before knowing that I wasn't going to make it). Should I keep this PR open, or move it to another repository for the special edition?

**Comment by vchuravy** [comment]
@ayush-1506 since you were accepted to JuliaCon, but couldn't make it for unrelated reasons it is up to you if you want to submit this to the proceedings or the special edition. In either case the submission process is the same and I would encourage you to finish it up as soon as possible, since we already have reviewers. Both proceedings and special edition are rolling submission.

**Comment by ayush-1506** [comment]
@vchuravy Thanks, will probably finish this up in the upcoming week. I'd prefer submitting to the JuliaCon proceedings in this case.

**Comment by vchuravy** [comment]
@ayush-1506 I have moved this from the proceedings to the planned special issue. This should give you a bit more time to finish up things.

**Comment by ayush-1506** [comment]
@vchuravy Thanks, apologies for the delay. I'm finishing this up at the moment. Could you give me an ETA on the special edition submission?

**Comment by ayush-1506** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List Whedon's capabilities
@whedon commands

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

EDITORIAL TASKS

# Compile the paper
@whedon generate pdf

# Compile the paper from alternative branch
@whedon generate pdf from branch custom-branch-name

# Ask Whedon to check the references for missing DOIs
@whedon check references

```

**Comment by ayush-1506** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/JuliaCon/proceedings-papers/blob/jcon.00021/jcon.00021/10.21105.jcon.00021.pdf)

**Comment by ayush-1506** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/JuliaCon/proceedings-papers/blob/jcon.00021/jcon.00021/10.21105.jcon.00021.pdf)

**Comment by ayush-1506** [comment]
@NiklasGustafsson Could you please review this?

**Comment by NiklasGustafsson** [comment]
Will do.

**Comment by NiklasGustafsson** [comment]
What is the preferred mechanism for providing my feedback?

**Comment by ayush-1506** [comment]
@NiklasGustafsson I reckon it's best we do this on slack (in case you're on julialang slack), or via mail. Does that sound good?

**Comment by NiklasGustafsson** [comment]
I'm not on the JuliaLang Slack channel. You can contact me at niklas.gustafsson@microsoft.com, so I'll have your email address. Once I have that, I will send you some thoughts.

**Comment by ayush-1506** [comment]
Ok, I've sent you a mail.

**Comment by vchuravy** [comment]
@ayush-1506 @NiklasGustafsson how did the review go?

**Comment by vchuravy** [comment]
@whedon start review

**Comment by NiklasGustafsson** [comment]
I forwarded my comments via email back in the winter.

**Comment by vchuravy** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List all of Whedon's capabilities
@whedon commands

# Assign a GitHub user as the sole reviewer of this submission
@whedon assign @username as reviewer

# Add a GitHub user to the reviewers of this submission
@whedon add @username as reviewer

# Re-invite a reviewer (if they can't update checklists)
@whedon re-invite @username as reviewer

# Remove a GitHub user from the reviewers of this submission
@whedon remove @username as reviewer

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

# Change editorial assignment
@whedon assign @username as editor

# Set the software archive DOI at the top of the issue e.g.
@whedon set 10.0000/zenodo.00000 as archive

# Set the software version at the top of the issue e.g.
@whedon set v1.0.1 as version

# Open the review issue
@whedon start review

EDITORIAL TASKS

# All commands can be run on a non-default branch, to do this pass a custom 
# branch name by following the command with `from branch custom-branch-name`.
# For example:

# Compile the paper
@whedon generate pdf

# Compile the paper from alternative branch
@whedon generate pdf from branch custom-branch-name

# Remind an author or reviewer to return to a review after a
# certain period of time (supported units days and weeks)
@whedon remind @reviewer in 2 weeks

# Ask Whedon to do a dry run of accepting the paper and depositing with Crossref
@whedon accept

# Ask Whedon to check the references for missing DOIs
@whedon check references

# Ask Whedon to check repository statistics for the submitted software
@whedon check repository

EiC TASKS

# Invite an editor to edit a submission (sending them an email)
@whedon invite @editor as editor

# Reject a paper
@whedon reject

# Withdraw a paper
@whedon withdraw

# Ask Whedon to actually accept the paper and deposit with Crossref
@whedon accept deposit=true

```

**Comment by vchuravy** [comment]
@whedon start review

**Comment by vchuravy** [comment]
@NiklasGustafsson thank you for that! I talked to Ayush offline and he will integrate them and then we can move forward.

**Comment by arfon** [comment]
@whedon start review

**Comment by arfon** [comment]
@whedon start review

**Comment by arfon** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/JuliaCon/proceedings-review/issues/59.
