### ISSUE TITLE
[PRE REVIEW]: Modia3D: Modeling and Simulation of 3D-Systems in Julia

### ISSUE THREAD

**Issue by whedon** [JuliaCon/proceedings-review#22]
**Submitting author:** @MartinOtter (<a href="http://orcid.org/0000-0001-6348-9569">Martin Otter</a>)
**Repository:** <a href="https://github.com/ModiaSim/Modia3D.jl/tree/JuliaCon2019-paper" target ="_blank">https://github.com/ModiaSim/Modia3D.jl/tree/JuliaCon2019-paper</a>
**Editor:** @matbesancon
**Reviewer:** Pending

**Author instructions**

Thanks for submitting your paper to JuliaCon @MartinOtter. The JuliaCon editor @matbesancon, will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@MartinOtter if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](http://bit.ly/2V9GSFq) have already agreed to review for JuliaCon and may be suitable for this submission.

**Editor instructions**

The JuliaCon submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @matbesancon it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for the assigned editor (@matbesancon) to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](http://bit.ly/2V9GSFq) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #22 with the following error: 

 /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `block in find': No such file or directory - tmp/22 (Errno::ENOENT)
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `collect!'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `find'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-85c572552d68/lib/whedon/processor.rb:61:in `find_paper_paths'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-85c572552d68/bin/whedon:50:in `prepare'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-85c572552d68/bin/whedon:116:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by matbesancon** [comment]
@whedon build pdf from branch JuliaCon2019-paper

**Comment by matbesancon** [comment]
@whedon generate pdf from branch JuliaCon2019-paper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch JuliaCon2019-paper. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #22 with the following error: 

 sh: 1: cd: can't cd to tmp/22
/app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `block in find': No such file or directory - tmp/22 (Errno::ENOENT)
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `collect!'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `find'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-85c572552d68/lib/whedon/processor.rb:61:in `find_paper_paths'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-85c572552d68/bin/whedon:50:in `prepare'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-85c572552d68/bin/whedon:116:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by matbesancon** [comment]
@MartinOtter there seems to be a problem with the submission URL, you should put the plain repo URL, and then the branch only to compile

**Comment by MartinOtter** [comment]
Can you give more detailed instructions what I shall do. The repo URL is "https://github.com/ModiaSim/Modia3D.jl" and the branch is "JuliaCon2019-paper", but I do not see how I can provide this information to your system, because only one URL seems to be possible to define and not two pieces. I also do not see a way that I can change the URL for your system.

**Comment by MartinOtter** [comment]
> @MartinOtter if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, this list of people have already agreed to review for JuliaCon and may be suitable for this submission.

In this list there seems to be no one that has a background in modeling and simulation of 3-dimensional mechanical systems or in games. Searching in the last JuliaCon and in Julia packages:
- Twan Koolen (tkoolen; developer of RigidBodyDynamics.jl)
- Robin Deits (rdeits; presentation at JuliaCon 2018: JuliaRobotics: Making robots walk with Julia, developer of MechanismGeometries.jl)
- Chris Rackauckas (ChrisRackauckas; main developer of DifferentialEquations.jl; specialist on variable-step integrators as used in the paper).

**Comment by ChrisRackauckas** [comment]
What's the time frame on reviews? I don't think I'll be able to do this well before JuliaCon.

**Comment by matbesancon** [comment]
Yeah I was thinking putting you on too many reviews would be very optimistic. A first round of review (for the content, software) would be nice before JuliaCon but the paper itself after JuliaCon is fine, since we aim at end of August

**Comment by matbesancon** [comment]
@tkoolen would you be available to review this proceeding?

**Comment by matbesancon** [comment]
@rdeits would you be available to review this proceeding?

**Comment by matbesancon** [comment]
> Can you give more detailed instructions what I shall do. The repo URL is "https://github.com/ModiaSim/Modia3D.jl" and the branch is "JuliaCon2019-paper", but I do not see how I can provide this information to your system, because only one URL seems to be possible to define and not two pieces. I also do not see a way that I can change the URL for your system.

@MartinOtter you should re-submit, https://github.com/ModiaSim/Modia3D.jl should be the URL you provide, without more information. Then when compiling, we will specify the branch, as in
`@whedon generate pdf from branch JuliaCon2019-paper`

**Comment by MartinOtter** [comment]
> @MartinOtter you should re-submit, https://github.com/ModiaSim/Modia3D.jl should be the URL you provide, without more information. Then when compiling, we will specify the branch, as in
@whedon generate pdf from branch JuliaCon2019-paper

O.k. I submitted the paper [newly](https://submissions.juliacon.org/papers/16d9193656436b4d4f774f73ab34d8c5) with the https://github.com/ModiaSim/Modia3D.jl address
and then withdraw the already submitted paper.

**Comment by matbesancon** [comment]
wait for it we will start the new review first

**Comment by MartinOtter** [comment]
> wait for it we will start the new review first

Sorry, when I now made things worse. What I did is to submit a new paper with the same title and the corrected URL (https://submissions.juliacon.org/papers/16d9193656436b4d4f774f73ab34d8c5) and then withdraw the previous paper submission (https://submissions.juliacon.org/papers/59d1f667891f69d446cf012c5ec43ffa)

**Comment by matbesancon** [comment]
@vchuravy can you assign me on the new submission?

**Comment by vchuravy** [comment]
Done

**Comment by tkoolen** [comment]
Sorry, I'm trying to graduate by the end of the summer so I can't commit to this review.

**Comment by matbesancon** [comment]
no problem, good luck
