### ISSUE TITLE
[PRE REVIEW]: StateSpaceModels.jl: a Julia Package for Time-Series Analysis in a State-Space Framework

### ISSUE THREAD

**Issue by whedon** [JuliaCon/proceedings-review#23]
**Submitting author:** @raphaelsaavedra (<a href="http://orcid.org/0000-0003-0095-4114">Raphael Saavedra</a>)
**Repository:** <a href="https://github.com/LAMPSPUC/StateSpaceModels.jl/" target ="_blank">https://github.com/LAMPSPUC/StateSpaceModels.jl/</a>
**Editor:** @matbesancon
**Reviewers:** @dehann, @mschauer

**Author instructions**

Thanks for submitting your paper to JuliaCon @raphaelsaavedra. The JuliaCon editor @matbesancon, will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@raphaelsaavedra if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](http://bit.ly/2V9GSFq) have already agreed to review for JuliaCon and may be suitable for this submission.

**Editor instructions**

The JuliaCon submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @matbesancon it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for the assigned editor (@matbesancon) to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](http://bit.ly/2V9GSFq) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/JuliaCon/proceedings-papers/blob/jcon.00023/jcon.00023/10.21105.jcon.00023.pdf)

**Comment by matbesancon** [comment]
@mschauer would you like to review this proceeding?

**Comment by matbesancon** [comment]
@dehann would you like to review this proceeding?

**Comment by dehann** [comment]
@matbesancon , sure I will review yes -- looks interesting!

**Comment by matbesancon** [comment]
@whedon add @dehann as reviewer

**Comment by whedon** [comment]
OK, @dehann is now a reviewer

**Comment by matbesancon** [comment]
@whedon add @mschauer as reviewer

**Comment by whedon** [comment]
OK, @mschauer is now a reviewer

**Comment by matbesancon** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/JuliaCon/proceedings-review/issues/28. Feel free to close this issue now!
