### ISSUE TITLE
[PRE REVIEW]: HydroPowerModels.jl: A Julia/JuMP Package forHydrothermal Economic Dispatch Optimization

### ISSUE THREAD

**Issue by whedon** [JuliaCon/proceedings-review#24]
**Submitting author:** @andrewrosemberg (<a href="http://orcid.org/0000-0002-6880-8845">Andrew Rosemberg</a>)
**Repository:** <a href="https://github.com/andrewrosemberg/HydroPowerModels.jl" target ="_blank">https://github.com/andrewrosemberg/HydroPowerModels.jl</a>
**Editor:** @vchuravy
**Reviewers:** @frapac, @Lukrosz

**Author instructions**

Thanks for submitting your paper to JuliaCon @andrewrosemberg. The JuliaCon editor @vchuravy, will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@andrewrosemberg if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](http://bit.ly/2V9GSFq) have already agreed to review for JuliaCon and may be suitable for this submission.

**Editor instructions**

The JuliaCon submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @vchuravy it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for the assigned editor (@vchuravy) to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](http://bit.ly/2V9GSFq) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/JuliaCon/proceedings-papers/blob/jcon.00024/jcon.00024/10.21105.jcon.00024.pdf)

**Comment by andrewrosemberg** [comment]
Here's suggestions for potential reviewers familiar with the subjects of optimal power flow and multistage stochastic programming:

- Jose Lara (@jd-lara)
- Bernardo da Costa (@bfpc)
- François Pacaud (@frapac)
- Luiz Carlos da Costa (@lccostajr)

**Comment by vchuravy** [comment]
@jd-lara, @bfpc, @farpac, @lccostajr would you be willing to review this paper?

**Comment by vchuravy** [comment]
@musm, @bkamins, @dourouc05, @dawbarton, @Lukrosz would you be willing to review this submission?

**Comment by frapac** [comment]
I would be happy to review this paper.

**Comment by matbesancon** [comment]
@whedon add @frapac as reviewer

**Comment by Lukrosz** [comment]
Hi, I'd like to review this article as well.

**Comment by whedon** [comment]
OK, @frapac is now a reviewer

**Comment by matbesancon** [comment]
@whedon add @Lukrosz as reviewer

**Comment by whedon** [comment]
OK, @Lukrosz is now a reviewer

**Comment by matbesancon** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/JuliaCon/proceedings-review/issues/35. Feel free to close this issue now!

**Comment by jd-lara** [comment]
Yes I can review the paper

**Comment by dourouc05** [comment]
If need be, I can also review this submission (not before Wednesday, though).

**Comment by matbesancon** [comment]
thanks both, this one already has two reviewers so it will be good to go as-is, don't hesitate to check the ones in pre-review

**Comment by matbesancon** [comment]
Like this one: https://github.com/JuliaCon/proceedings-review/issues/19

**Comment by lccostajr** [comment]
Hi, unfortunately this message went to Spam folder and I could see it only
now.
I would like to review this paper.
