### ISSUE TITLE
[PRE REVIEW]: Probabilistic Biostatistics with Julia

### ISSUE THREAD

**Issue by whedon** [JuliaCon/proceedings-review#25]
**Submitting author:** @tszanalytics (<a href="http://orcid.org/0000-0002-2469-1796">Jeffrey A Mills</a>)
**Repository:** <a href="https://github.com/tszanalytics/Juliacon2019/" target ="_blank">https://github.com/tszanalytics/Juliacon2019/</a>
**Editor:** @matbesancon
**Reviewers:** @bkamins, @kescobo

**Author instructions**

Thanks for submitting your paper to JuliaCon @tszanalytics. The JuliaCon editor @matbesancon, will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@tszanalytics if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](http://bit.ly/2V9GSFq) have already agreed to review for JuliaCon and may be suitable for this submission.

**Editor instructions**

The JuliaCon submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @matbesancon it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for the assigned editor (@matbesancon) to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](http://bit.ly/2V9GSFq) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #25 with the following error: 

 /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `block in find': No such file or directory - tmp/25 (Errno::ENOENT)
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `collect!'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `find'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-85c572552d68/lib/whedon/processor.rb:61:in `find_paper_paths'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-85c572552d68/bin/whedon:50:in `prepare'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-85c572552d68/bin/whedon:116:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by tszanalytics** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List Whedon's capabilities
@whedon commands

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

EDITORIAL TASKS

# Compile the paper
@whedon generate pdf

# Compile the paper from alternative branch
@whedon generate pdf from branch custom-branch-name

# Ask Whedon to check the references for missing DOIs
@whedon check references

```

**Comment by tszanalytics** [comment]
@matbesancon  Here's suggestions from the list of potential reviewers (starting at bottom of list) :

dmbates dmbates@gmail.com
kescobo kevbonham@gmail.com
bkamins bkamins@sgh.waw.pl

Also, the paper did not appear to compile due to a missing file.  I will see if I can fix that.
Thanks!

**Comment by matbesancon** [comment]
Thanks @tszanalytics, note that we cannot start the review while the paper doesn't compile.
@bkamins would you be available to review this proceeding?

**Comment by matbesancon** [comment]
@kescobo would you be available to review?

**Comment by bkamins** [comment]
@matbesancon - sure - I can help. What would be the process?

**Comment by matbesancon** [comment]
the review happens in an issue, you provide feedback on the code and paper, can submit issues on the main repo itself, changes can happen gradually. Once the checklist is done and you are satisfied with everything, the review is done

See https://github.com/JuliaCon/proceedings-review/issues/28 for instance

**Comment by matbesancon** [comment]
@whedon add @bkamins as reviewer

**Comment by whedon** [comment]
OK, @bkamins is now a reviewer

**Comment by tszanalytics** [comment]
@matbesancon 
Hi, sorry I don't know what I need to change to get the paper to compile. I'm unfamiliar with Ruby and latexmk.  Do I need to install these on my local machine or is there a way to compile without doing so, and if so how?  Thanks!

**Comment by matbesancon** [comment]
The URL you provided is not in the correct format, it should be the main repo, not the path to the paper file

**Comment by bkamins** [comment]
@matbesancon: I understand that I wait till the status changes to [REVIEW] and the paper PDF is generated + the list like in #28 is in place. Right?

@tszanalytics: I think it will be easier if I give you the feedback as new issues in https://github.com/tszanalytics/Juliacon2019. OK?
Also can you also please guide me where are the runnable codes for your text, as I could not find them in your repository. Finally there are two .tex files in the repo. I understand that one can be removed - right?.

**Comment by matbesancon** [comment]
> I understand that I wait till the status changes to [REVIEW] and the paper PDF is generated + the list like in #28 is in place. Right?

You can start your review now by posting issues on the main repo yes, but this one will likely be closed since the URL is invalid. Once we have a second reviewer, I'll open the review issue exactly

**Comment by matbesancon** [comment]
@tszanalytics you should submit with https://github.com/tszanalytics/Juliacon2019 as repository if it is your main repo

**Comment by kescobo** [comment]
I'd love to review, but I'm fairly strapped for time (and off the grid for a week starting Friday). What's the time frame?

**Comment by matbesancon** [comment]
This would be fine, @bkamins can start the review and you can pick up after you come back

**Comment by tszanalytics** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #25 with the following error: 

 /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `block in find': No such file or directory - tmp/25 (Errno::ENOENT)
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `collect!'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `find'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-85c572552d68/lib/whedon/processor.rb:61:in `find_paper_paths'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-85c572552d68/bin/whedon:50:in `prepare'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-85c572552d68/bin/whedon:116:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by matbesancon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/JuliaCon/proceedings-papers/blob/jcon.00025/jcon.00025/10.21105.jcon.00025.pdf)

**Comment by matbesancon** [comment]
@whedon add @kescobo as reviewer

**Comment by whedon** [comment]
OK, @kescobo is now a reviewer

**Comment by matbesancon** [comment]
@whedon start review

**Comment by matbesancon** [comment]
@tszanalytics problem fixed :)

**Comment by matbesancon** [comment]
@whedon start review

**Comment by tszanalytics** [comment]
@matbesancon  Ok, I withdrew and resubmitted using the URL as suggested.  It compled OK this time, thanks for the help!

@bkamins  Thanks for agreeing to review my paper.  I've removed the additional tex and pdf files from the \paper folder.  I just have code snippets in the paper, but I can post more complete runnable examples of julia code and add the URL to the paper.  I will do so asap.  Let me know if you have anything in particular in mind.  Also, giving feedback as an issue on the paper repo would be great.  Thanks!

**Comment by bkamins** [comment]
@tszanalytics I asked about the codes, because if you look at https://github.com/JuliaCon/proceedings-review/issues/28 for example there are the following criteria that the paper must meet (I am copying the relevant ones from **General checks**, but please review all of them there to make sure that your submission complies with it):

### General checks

- [ ] **Repository:** Is the source code for this software available?
- [ ] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?

**Comment by bkamins** [comment]
@matbesancon - I can see that you have started the review, but the "checklist" has not generated yet. Should I wait for it or I have missed something.

@tszanalytics - I can review the paper as is if you prefer not to add working codes to the repository. Please let me know how you see this.

**Comment by matbesancon** [comment]
thanks for the ping, it hasn't started indeed

**Comment by matbesancon** [comment]
@whedon start review

**Comment by matbesancon** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List all of Whedon's capabilities
@whedon commands

# Assign a GitHub user as the sole reviewer of this submission
@whedon assign @username as reviewer

# Add a GitHub user to the reviewers of this submission
@whedon add @username as reviewer

# Remove a GitHub user from the reviewers of this submission
@whedon remove @username as reviewer

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

# Change editorial assignment
@whedon assign @username as editor

# Set the software archive DOI at the top of the issue e.g.
@whedon set 10.0000/zenodo.00000 as archive

# Set the software version at the top of the issue e.g.
@whedon set v1.0.1 as version

# Open the review issue
@whedon start review

EDITORIAL TASKS

# Compile the paper
@whedon generate pdf

# Compile the paper from alternative branch
@whedon generate pdf from branch custom-branch-name

# Remind an author or reviewer to return to a review after a
# certain period of time (supported units days and weeks)
@whedon remind @reviewer in 2 weeks

# Ask Whedon to accept the paper and deposit with Crossref
@whedon accept

# Ask Whedon to check the references for missing DOIs
@whedon check references

```

**Comment by matbesancon** [comment]
@whedon start review

**Comment by matbesancon** [comment]
@arfon not sure why whedon isn't kicking off the review?

**Comment by arfon** [comment]
@matbesancon - it's showing up as `withdrawn` on the proceedings site. Is this incorrect?

**Comment by matbesancon** [comment]
ah point, sorry yup

**Comment by tszanalytics** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/JuliaCon/proceedings-papers/blob/jcon.00025/jcon.00025/10.21105.jcon.00025.pdf)

**Comment by tszanalytics** [comment]
@matbesancon @bkamins @kescobo 

Ok, I believe it is ready to move forward with review now.  I've added code to generate the figures, etc. that appear in the paper, as well as code for some of the additional examples in the presentation.  Let me know what else needs to be done and I should be able to complete quickly.

Thanks,
Jeff

**Comment by kescobo** [comment]
So why was the issue closed? I'm so confused...

**Comment by bkamins** [comment]
This one should be used: https://github.com/JuliaCon/proceedings-review/issues/36.
@tszanalytics - I am not sure but probably you should re-generate the PDF in #36

**Comment by matbesancon** [comment]
Indeed that is in #36
