### ISSUE TITLE
[PRE REVIEW]: RayTracer.jl: A General Purpose Differentiable Renderer

### ISSUE THREAD

**Issue by whedon** [JuliaCon/proceedings-review#27]
**Submitting author:** @avik-pal (<a href="http://orcid.org/0000-0002-3938-7375">Avik Pal</a>)
**Repository:** <a href="https://github.com/avik-pal/juliacon-raytracer-paper" target ="_blank">https://github.com/avik-pal/juliacon-raytracer-paper</a>
**Editor:** @matbesancon
**Reviewer:** Pending

**Author instructions**

Thanks for submitting your paper to JuliaCon @avik-pal. The JuliaCon editor @matbesancon, will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@avik-pal if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](http://bit.ly/2V9GSFq) have already agreed to review for JuliaCon and may be suitable for this submission.

**Editor instructions**

The JuliaCon submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @matbesancon it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for the assigned editor (@matbesancon) to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](http://bit.ly/2V9GSFq) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/JuliaCon/proceedings-papers/blob/jcon.00027/jcon.00027/10.21105.jcon.00027.pdf)

**Comment by matbesancon** [comment]
@avik-pal thanks for submitting. Usually JuliaCon submissions are part of a package, could this be in RayTracer.jl?

**Comment by matbesancon** [comment]
@snoeyink would you be available to review this proceeding?

**Comment by matbesancon** [comment]
@haampie would you be available to review this proceeding?

**Comment by avik-pal** [comment]
@matbesancon yes I could add this to RayTracer itself. Would it be fine, if I add it to a branch of RayTracer.jl atleast during the review process and merge it into master if it is accepted?

In that case, should I make a resubmission?

**Comment by matbesancon** [comment]
yes you can absolutely, can you re-submit with the paper on the main repo in another branch?

**Comment by avik-pal** [comment]
I have resubmitted the paper. The paper is in the `juliacon-paper` branch of RayTracer.jl.

**Comment by snoeyink** [comment]
Yes

Jack Snoeyink, snoeyink@cs.unc.edu
Computer Science, UNC Chapel Hill
