### ISSUE TITLE
[PRE REVIEW]: SemanticModels.jl: A Julia Package for Scientific Model Augmentation

### ISSUE THREAD

**Issue by whedon** [JuliaCon/proceedings-review#29]
**Submitting author:** @mehalter (<a href="http://orcid.org/0000-0002-0484-971X">Micah Halter</a>)
**Repository:** <a href="https://github.com/mehalter/juliacon2019-submission" target ="_blank">https://github.com/mehalter/juliacon2019-submission</a>
**Editor:** @vchuravy
**Reviewers:** @MasonProtter, @ChrisRackauckas

**Author instructions**

Thanks for submitting your paper to JuliaCon @mehalter. The JuliaCon editor @vchuravy, will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@mehalter if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](http://bit.ly/2V9GSFq) have already agreed to review for JuliaCon and may be suitable for this submission.

**Editor instructions**

The JuliaCon submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @vchuravy it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for the assigned editor (@vchuravy) to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](http://bit.ly/2V9GSFq) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
Failed to discover a valid open source license.

**Comment by whedon** [comment]
PDF failed to compile for issue #29 with the following error: 

 ORCID looks to be the wrong length
/app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-85c572552d68/lib/whedon.rb:123:in `block in check_orcids': Problem with ORCID (000-0002-0484-971X) for Micah Halter (RuntimeError)
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-85c572552d68/lib/whedon.rb:121:in `each'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-85c572552d68/lib/whedon.rb:121:in `check_orcids'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-85c572552d68/lib/whedon.rb:81:in `initialize'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-85c572552d68/lib/whedon/processor.rb:36:in `new'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-85c572552d68/lib/whedon/processor.rb:36:in `set_paper'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-85c572552d68/bin/whedon:55:in `prepare'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-85c572552d68/bin/whedon:116:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by mehalter** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List Whedon's capabilities
@whedon commands

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

EDITORIAL TASKS

# Compile the paper
@whedon generate pdf

# Compile the paper from alternative branch
@whedon generate pdf from branch custom-branch-name

# Ask Whedon to check the references for missing DOIs
@whedon check references

```

**Comment by mehalter** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/JuliaCon/proceedings-papers/blob/jcon.00029/jcon.00029/10.21105.jcon.00029.pdf)

**Comment by mehalter** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1137/141000671 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by vchuravy** [comment]
@mehalter do you have suggestions for reviewers?

I was about to suggest @jpfairbanks, but he is a co-author.

**Comment by mehalter** [comment]
Sorry for the late reply! I don't know if the reviewer has been selected yet, but maybe Chris Rackauckas. His work in partially symbolic computing with Julia fits this project very well.

**Comment by vchuravy** [comment]
@shashi, @ChrisRackauckas, @rdeits, @HarrisonGrodin, @MasonProtter would either one of you be willing and interesting in reviewing this submission?

**Comment by ChrisRackauckas** [comment]
Ping me again if it's not sorted out by December.

**Comment by MasonProtter** [comment]
Yes, I would be interested but I don't know anything about the review process. That is, I need documentation on what is expected of me as a reviewer and what is expected of a high quality submission.

**Comment by vchuravy** [comment]
You can find information about the review process at https://proceedings.juliacon.org/guide/reviewers/ and I am also available on Slack for questions.

**Comment by vchuravy** [comment]
@whedon add @ChrisRackauckas as reviewer

**Comment by whedon** [comment]
OK, @ChrisRackauckas is now a reviewer

**Comment by vchuravy** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/JuliaCon/proceedings-review/issues/57. Feel free to close this issue now!
