### ISSUE TITLE
[PRE REVIEW]: Modia3D: Modeling and Simulation of 3D-Systems in Julia

### ISSUE THREAD

**Issue by whedon** [JuliaCon/proceedings-review#30]
**Submitting author:** @MartinOtter (<a href="http://orcid.org/0000-0001-6348-9569">Martin Otter</a>)
**Repository:** <a href="https://github.com/ModiaSim/Modia3D.jl" target ="_blank">https://github.com/ModiaSim/Modia3D.jl</a>
**Editor:** @matbesancon
**Reviewers:** @Datseris

**Author instructions**

Thanks for submitting your paper to JuliaCon @MartinOtter. The JuliaCon editor @matbesancon, will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@MartinOtter if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](http://bit.ly/2V9GSFq) have already agreed to review for JuliaCon and may be suitable for this submission.

**Editor instructions**

The JuliaCon submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @matbesancon it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for the assigned editor (@matbesancon) to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](http://bit.ly/2V9GSFq) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #30 with the following error: 

 Can't find any papers to compile :-(

**Comment by matbesancon** [comment]
@whedon generate pdf from branch JuliaCon2019-paper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch JuliaCon2019-paper. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #30 with the following error: 

 rm: cannot remove '*.aux': No such file or directory
Latexmk: This is Latexmk, John Collins, 17 Jan. 2018, version: 4.55.
Rule 'pdflatex': Rules & subrules not known to be previously run:
   pdflatex
Rule 'pdflatex': The following rules & subrules became out-of-date:
      'pdflatex'
------------
Run number 1 of rule 'pdflatex'
------------
------------
Running 'pdflatex  -recorder  "paper.tex"'
------------
===========Latexmk: Missing input file: 'enumitem.sty' from line
  '! LaTeX Error: File `enumitem.sty' not found.'
Latexmk: Missing input file: 'enumitem.sty' from line
  '! LaTeX Error: File `enumitem.sty' not found.'
Failure to make 'paper.pdf'
Collected error summary (may duplicate other messages):
  pdflatex: Command for 'pdflatex' gave return code 1
      Refer to 'paper.log' for details
Looks like we failed to compile the PDF

**Comment by matbesancon** [comment]
@MartinOtter see the error message, enumitem.sty required

**Comment by MartinOtter** [comment]
> @MartinOtter see the error message, enumitem.sty required

Added the missing file.

**Comment by matbesancon** [comment]
@whedon generate pdf from branch JuliaCon2019-paper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch JuliaCon2019-paper. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/JuliaCon/proceedings-papers/blob/jcon.00030/jcon.00030/10.21105.jcon.00030.pdf)

**Comment by matbesancon** [comment]
@Datseris would you like to review this proceeding?

**Comment by matbesancon** [comment]
@rdeits would you be available to review this proceeding?

**Comment by Datseris** [comment]
@matbesancon yes, I accept reviewing this. (but I am letting you know that this will be my first review in JOSS)

**Comment by matbesancon** [comment]
no problem, this is pretty smooth usually

**Comment by matbesancon** [comment]
@whedon add @Datseris as reviewer

**Comment by whedon** [comment]
OK, @Datseris is now a reviewer

**Comment by matbesancon** [comment]
@ChrisRackauckas would you like to review this paper?

**Comment by matbesancon** [comment]
@MartinOtter sorry about the delay on this paper. @Datseris I will find a second reviewer but you can start reviewing the paper and code already (you can see example checklists on the other issues)

**Comment by Datseris** [comment]
@matbesancon there is no review issue open on this. Having the checklist is pretty helpful, can you please start the review? In another paper that I reviewed this is how it progressed and a second reviewer was added after I have finished my review.

**Comment by matbesancon** [comment]
ok yes sure

**Comment by matbesancon** [comment]
@whedon start review
