### ISSUE TITLE
[REVIEW]: HydroPowerModels.jl: A Julia/JuMP Package forHydrothermal Economic Dispatch Optimization

### ISSUE THREAD

**Issue by whedon** [JuliaCon/proceedings-review#35]
**Submitting author:** @andrewrosemberg (<a href="http://orcid.org/0000-0002-6880-8845">Andrew Rosemberg</a>)
**Repository:** <a href="https://github.com/andrewrosemberg/HydroPowerModels.jl" target ="_blank">https://github.com/andrewrosemberg/HydroPowerModels.jl</a>
**Editor:** @vchuravy
**Reviewer:** @frapac, @Lukrosz
**Archive:** <a href="https://doi.org/10.5281/zenodo.3842130" target="_blank">10.5281/zenodo.3842130</a>

## Status

[![status](https://proceedings.juliacon.org/papers/ad43bcbd43a6f904e60db8838c177520/status.svg)](https://proceedings.juliacon.org/papers/ad43bcbd43a6f904e60db8838c177520)

Status badge code:

```
HTML: <a href="https://submissions.juliacon.org/papers/ad43bcbd43a6f904e60db8838c177520"><img src="https://submissions.juliacon.org/papers/ad43bcbd43a6f904e60db8838c177520/status.svg"></a>
Markdown: [![status](https://submissions.juliacon.org/papers/ad43bcbd43a6f904e60db8838c177520/status.svg)](https://submissions.juliacon.org/papers/ad43bcbd43a6f904e60db8838c177520)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/andrewrosemberg/HydroPowerModels.jl" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@frapac & @Lukrosz, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/JuliaCon/proceedings-reviews/invitations

The reviewer guidelines are available here: https://proceedings.juliacon.org/guide/reviewers. Any questions/concerns please let @vchuravy know.

✨ **Please try and complete your review in the next two weeks** ✨

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JuliaCon conflict of interest policy](https://proceedings.juliacon.org/guide/authors#coi) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JuliaCon code of conduct](https://proceedings.juliacon.org/coc).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/andrewrosemberg/HydroPowerModels.jl">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Authorship:** Has the submitting author (@andrewrosemberg) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Paper format

- [x] **Authors:** Does the `paper.tex` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?
- [x] **Page limit:** Is the page limit for full papers respected by the submitted document?

### Content

- [x] **Context:** is the scientific context motivating the work correctly presented?
- [x] **Methodology:** is the approach taken in the work justified, presented with enough details and reference to reproduce it?
- [x] **Results:** are the results presented and compared to approaches with similar goals?

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JuliaCon conflict of interest policy](https://proceedings.juliacon.org/guide/authors#coi) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JuliaCon code of conduct](https://proceedings.juliacon.org/coc).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/andrewrosemberg/HydroPowerModels.jl">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Authorship:** Has the submitting author (@andrewrosemberg) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Paper format

- [x] **Authors:** Does the `paper.tex` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?
- [x] **Page limit:** Is the page limit for full papers respected by the submitted document?

### Content

- [x] **Context:** is the scientific context motivating the work correctly presented?
- [x] **Methodology:** is the approach taken in the work justified, presented with enough details and reference to reproduce it?
- [x] **Results:** are the results presented and compared to approaches with similar goals?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @frapac, @Lukrosz it looks like you're currently assigned to review this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/JuliaCon/proceedings-review) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/JuliaCon/proceedings-review:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/JuliaCon/proceedings-papers/blob/jcon.00035/jcon.00035/10.21105.jcon.00035.pdf)

**Comment by frapac** [comment]
@andrewrosemberg Do you mind if I open a PR on HydroPowerModels.jl to comment out your article?

**Comment by andrewrosemberg** [comment]
> @andrewrosemberg Do you mind if I open a PR on HydroPowerModels.jl to comment out your article?

I don't mind at all. Please feel free to open one!

**Comment by Lukrosz** [comment]
Hi @andrewrosemberg,

Here attached is a document with my reviews of your article ([HydroPowerModels.jl_article.pdf](https://github.com/JuliaCon/proceedings-review/files/3401264/HydroPowerModels.jl_article.pdf)). For now, they are mainly focused on the structure and grammatics of the article and details about the model. Later on, I will comment about the package.

Let me know when you have the chance to read the pdf.

**Comment by frapac** [comment]
Hi @andrewrosemberg,  
please find [my final review](https://github.com/frapac/HydroPowerModels.jl/blob/fp/review/paper/review.md) of the paper. Let me know if you have any question about it!

**Comment by andrewrosemberg** [comment]
Hi @frapac and @Lukrosz,
Thank you for your reviews! I just pushed 0a05688489d83478bd03daba1a40e945025fd9c2 changes according to some of the comments of your first reviews. 

I will continue working to resolve the remaining points of your comments. Please let me know it you have any questions or additional comments.

**Comment by andrewrosemberg** [comment]
Hi @frapac and @Lukrosz,

Once again, thank you for the thoughtful comments and reviews. I just [pushed](https://github.com/andrewrosemberg/HydroPowerModels.jl/commit/10ecf35357637c6a620f0ebcd7b510d75dcbca91) the modifications I was working on based on your first and final reviews. 

The remaining enhancements of the package proposed in the issues and reviews (seminal use-case testing, project.toml enhancement, benchmarks for SDDP libraries, ...) will be the developed from now on! 

About the remaining boxes to be checked, do you have additional questions about the implementation, the usage or other points?

I am at your disposal for anything you may need.

Best regards,
Andrew

**Comment by vchuravy** [comment]
@andrewrosemberg, @frapac and @Lukrosz would be good to wrap this up soon.

**Comment by andrewrosemberg** [comment]
Hi @frapac and @Lukrosz,

Thanks again for the thoughtful comments and reviews.  Do you need any additional information for the remaining points? 

Best,
Andrew

**Comment by frapac** [comment]
Hi @andrewrosemberg . For my part, I think you have addressed all the points that I raised during the review. I am looking forward seeing a clear separation between the optimization pass and the simulation, but this may be a bit premature at the moment. In any case, I would be very interested seeing an open-source package that solves OPF in a multistage stochastic programming setting!

**Comment by andrewrosemberg** [comment]
Thanks @frapac ! Yes, an pure multistage OPF would be very good, I will look into it!
About the review, I believe all the boxes should be checked in order for it to be over. @vchuravy Please correct me if I am wrong.

**Comment by Lukrosz** [comment]
Hello, @andrewrosemberg. Sorry for my very late respones. 
Of my part, I don't have any further comments. I checked all the boxes to continue. with the process.

**Comment by andrewrosemberg** [comment]
@frapac and @Lukrosz, thanks for all the work and time you dedicated to this! I hope the package will meet your expectations :)

@vchuravy, thanks for the help in the review process! Please let me know if any additional steps are required.

Best,
Andrew

**Comment by andrewrosemberg** [comment]
@vchuravy, sorry for the subsequent comment, but occurred to me a question:

During the review process I have changed the article. Do we need to recompile de PDF?

**Comment by andrewrosemberg** [comment]
@vchuravy, we have checked all the boxes, are there any further steps for the paper to be accepted?

**Comment by andrewrosemberg** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/JuliaCon/proceedings-papers/blob/jcon.00035/jcon.00035/10.21105.jcon.00035.pdf)

**Comment by andrewrosemberg** [comment]
@vchuravy, I have published the code using zenodo, following the proceedings [docs](https://joss.readthedocs.io/en/latest/editing.html#after-reviewers-recommend-acceptance), and the DOI associated with the final version of the paper and package is: `10.5281/zenodo.3842130`
The version is `v0.1.0`.
Doi is shown in the [master](https://github.com/andrewrosemberg/HydroPowerModels.jl/tree/master).
Tag is [this one](https://github.com/andrewrosemberg/HydroPowerModels.jl/tree/v0.1.0).

**Comment by vchuravy** [comment]
@whedon set 10.5281/zenodo.3842130 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.3842130" target="_blank">10.5281/zenodo.3842130</a> is the archive.

**Comment by vchuravy** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1287/opre.38.5.911 is OK
- 10.1109/TPWRS.2017.2672204 is OK
- 10.23919/PSCC.2018.8442948 is OK
- 10.1137/15M1020575 is OK
- 10.5281/zenodo.2628748 is OK

MISSING DOIs

- https://doi.org/10.1137/141000671 may be missing for title: Julia: A fresh approach to numerical computing
- https://doi.org/10.1016/0142-0615(89)90025-2 may be missing for title: Optimal stochastic operations scheduling of large hydroelectric systems
- https://doi.org/10.1007/bf01582895 may be missing for title: Multi-stage stochastic optimization applied to energy planning
- https://doi.org/10.1287/opre.2013.1175 may be missing for title: On solving multistage stochastic programs with coherent risk measures
- https://doi.org/10.1561/9781680835410 may be missing for title: A survey of relaxations and approximations of the power flow equations
- https://doi.org/10.1023/a:1022641805263 may be missing for title: Convergent cutting-plane and partial-sampling algorithm for multistage stochastic linear programs with recourse
- https://doi.org/10.23919/pscc.2018.8442754 may be missing for title: Twenty Years of Application of Stochastic Dual Dynamic Programming in Official and Agent Studies in Brazil-Main Features and Improvements on the NEWAVE Model

INVALID DOIs

- None
```

**Comment by vchuravy** [comment]
@wheden set v0.1.0 as version

**Comment by vchuravy** [comment]
@whedon set v0.1.0 as version

**Comment by whedon** [comment]
OK. v0.1.0 is the version.

**Comment by vchuravy** [comment]
@andrewrosemberg thank you for your patience can you add the missing DOIs?

**Comment by andrewrosemberg** [comment]
Yess will do that now! Will let you know when its done

**Comment by andrewrosemberg** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1137/141000671 is OK
- 10.1287/opre.38.5.911 is OK
- 10.1016/0142-0615(89)90025-2 is OK
- 10.1007/bf01582895 is OK
- 10.1287/opre.2013.1175 is OK
- 10.1109/TPWRS.2017.2672204 is OK
- 10.23919/PSCC.2018.8442948 is OK
- 10.1137/15M1020575 is OK
- 10.5281/zenodo.2628748 is OK
- 10.1561/9781680835410 is OK
- 10.1023/a:1022641805263 is OK
- 10.23919/pscc.2018.8442754 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by andrewrosemberg** [comment]
@vchuravy Missing DOIs added! sorry for the delay. 
The updated version is already in the master, do I need to make a new release?

**Comment by vchuravy** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
:wave: @JuliaCon/jcon-eics, this paper is ready to be accepted and published.

 Check final proof :point_right: https://github.com/JuliaCon/proceedings-papers/pull/26

If the paper PDF and Crossref deposit XML look good in https://github.com/JuliaCon/proceedings-papers/pull/26, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1137/141000671 is OK
- 10.1287/opre.38.5.911 is OK
- 10.1016/0142-0615(89)90025-2 is OK
- 10.1007/bf01582895 is OK
- 10.1287/opre.2013.1175 is OK
- 10.1109/TPWRS.2017.2672204 is OK
- 10.23919/PSCC.2018.8442948 is OK
- 10.1137/15M1020575 is OK
- 10.5281/zenodo.2628748 is OK
- 10.1561/9781680835410 is OK
- 10.1023/a:1022641805263 is OK
- 10.23919/pscc.2018.8442754 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by vchuravy** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JCON!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/JuliaCon/proceedings-papers/pull/27
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/jcon.00035](https://doi.org/10.21105/jcon.00035)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? Notify your editorial technical team...

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://proceedings.juliacon.org/papers/10.21105/jcon.00035/status.svg)](https://doi.org/10.21105/jcon.00035)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/jcon.00035">
  <img src="https://proceedings.juliacon.org/papers/10.21105/jcon.00035/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://proceedings.juliacon.org/papers/10.21105/jcon.00035/status.svg
   :target: https://doi.org/10.21105/jcon.00035
```
This is how it will look in your documentation:

[![DOI](https://proceedings.juliacon.org/papers/10.21105/jcon.00035/status.svg)](https://doi.org/10.21105/jcon.00035)

**We need your help!**

JuliaCon Proceedings is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://forms.gle/yANMe4c9YmuW9MWcA
- Making a small donation to support our running costs here: https://numfocus.salsalabs.org/donate-to-jcon
