### ISSUE TITLE
[PRE REVIEW]: Markov Chain-Monte Carlo Methods for Linear Algebra using Julia v.1.0

### ISSUE THREAD

**Issue by whedon** [JuliaCon/proceedings-review#41]
**Submitting author:** @oaefbsc (<a href="http://orcid.org/0000-0003-1451-1285">Oscar Alejandro Esquivel-Flores</a>)
**Repository:** <a href="https://github.com/oaefbsc/Juliacon2019" target ="_blank">https://github.com/oaefbsc/Juliacon2019</a>
**Editor:** @vchuravy
**Reviewers:** @dpsanders, @andreasnoack 

**Author instructions**

Thanks for submitting your paper to JuliaCon @oaefbsc. The JuliaCon editor @matbesancon, will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@oaefbsc if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](http://bit.ly/2V9GSFq) have already agreed to review for JuliaCon and may be suitable for this submission.

**Editor instructions**

The JuliaCon submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @matbesancon it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```


**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for the assigned editor (@matbesancon) to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](http://bit.ly/2V9GSFq) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
Failed to discover a valid open source license.

**Comment by whedon** [comment]
PDF failed to compile for issue #41 with the following error: 

 /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-5a9319b684e6/lib/whedon/author.rb:23:in `strip_footnotes': undefined method `[]' for nil:NilClass (NoMethodError)
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-5a9319b684e6/lib/whedon/author.rb:13:in `initialize'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-5a9319b684e6/lib/whedon.rb:141:in `new'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-5a9319b684e6/lib/whedon.rb:141:in `block in parse_authors'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-5a9319b684e6/lib/whedon.rb:138:in `each'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-5a9319b684e6/lib/whedon.rb:138:in `parse_authors'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-5a9319b684e6/lib/whedon.rb:84:in `initialize'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-5a9319b684e6/lib/whedon/processor.rb:36:in `new'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-5a9319b684e6/lib/whedon/processor.rb:36:in `set_paper'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-5a9319b684e6/bin/whedon:55:in `prepare'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-5a9319b684e6/bin/whedon:116:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by matbesancon** [comment]
@oaefbsc can you see what errors here? Also, you should put the code repo instead of a new one

**Comment by matbesancon** [comment]
ping @oaefbsc

**Comment by oaefbsc** [comment]
Apreciated Mahtie,

I have been a lot of problems, personal and technical, about to solve the
problem with my Juliacon2019 paper.
I would like to kwon if is possible to do somethin about review it and
include in proceedings.

I will appreciate your answer.

Regards,
Oscar Esquivel

**Comment by vchuravy** [comment]
@oaefbsc please follow the author instructions at https://proceedings.juliacon.org/guide/authors/ 
Without Whedon being able to compile your submission we are unable to proceed.

**Comment by vchuravy** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/JuliaCon/proceedings-papers/blob/jcon.00041/jcon.00041/10.21105.jcon.00041.pdf)

**Comment by vchuravy** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List all of Whedon's capabilities
@whedon commands

# Assign a GitHub user as the sole reviewer of this submission
@whedon assign @username as reviewer

# Add a GitHub user to the reviewers of this submission
@whedon add @username as reviewer

# Re-invite a reviewer (if they can't update checklists)
@whedon re-invite @username as reviewer

# Remove a GitHub user from the reviewers of this submission
@whedon remove @username as reviewer

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

# Change editorial assignment
@whedon assign @username as editor

# Set the software archive DOI at the top of the issue e.g.
@whedon set 10.0000/zenodo.00000 as archive

# Set the software version at the top of the issue e.g.
@whedon set v1.0.1 as version

# Open the review issue
@whedon start review

EDITORIAL TASKS

# All commands can be run on a non-default branch, to do this pass a custom 
# branch name by following the command with `from branch custom-branch-name`.
# For example:

# Compile the paper
@whedon generate pdf

# Compile the paper from alternative branch
@whedon generate pdf from branch custom-branch-name

# Remind an author or reviewer to return to a review after a
# certain period of time (supported units days and weeks)
@whedon remind @reviewer in 2 weeks

# Ask Whedon to do a dry run of accepting the paper and depositing with Crossref
@whedon accept

# Ask Whedon to check the references for missing DOIs
@whedon check references

# Ask Whedon to check repository statistics for the submitted software
@whedon check repository

EiC TASKS

# Invite an editor to edit a submission (sending them an email)
@whedon invite @editor as editor

# Reject a paper
@whedon reject

# Withdraw a paper
@whedon withdraw

# Ask Whedon to actually accept the paper and deposit with Crossref
@whedon accept deposit=true

```

**Comment by vchuravy** [comment]
@whedon add @dpsanders as reviewer

**Comment by whedon** [comment]
OK, @dpsanders is now a reviewer

**Comment by vchuravy** [comment]
@oaefbsc thank you for your patience. Are you still interested in seeing this submission as part of the JuliaCon proceedings?

**Comment by vchuravy** [comment]
@whedon set @vchuravy as editor

**Comment by whedon** [comment]
I'm sorry human, I don't understand that. You can see what commands I support by typing:

```
@whedon commands
```

**Comment by vchuravy** [comment]
@whedon invite @vchuravy as editor

**Comment by whedon** [comment]
@vchuravy has been invited to edit this submission.

**Comment by vchuravy** [comment]
@whedon assign @vchuravy as editor

**Comment by whedon** [comment]
OK, the editor is @vchuravy

**Comment by vchuravy** [comment]
@whedon add @andreasnoack  as reviewer

**Comment by whedon** [comment]
OK, @andreasnoack  is now a reviewer

**Comment by vchuravy** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/JuliaCon/proceedings-review/issues/60.
