### ISSUE TITLE
[PRE REVIEW]: ∂P: A Differentiable Programming System to Bridge Machine Learning and Scientific Computing

### ISSUE THREAD

**Issue by whedon** [JuliaCon/proceedings-review#44]
**Submitting author:** @MikeInnes (<a href="http://orcid.org/0000-0003-0788-0242">Michael Innes</a>)
**Repository:** <a href="https://github.com/MikeInnes/zygote-paper" target ="_blank">https://github.com/MikeInnes/zygote-paper</a>
**Editor:** @vchuravy
**Reviewers:** @tlienart, @jiahao

**Author instructions**

Thanks for submitting your paper to JuliaCon @MikeInnes. The JuliaCon editor @vchuravy, will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@MikeInnes if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](http://bit.ly/2V9GSFq) have already agreed to review for JuliaCon and may be suitable for this submission.

**Editor instructions**

The JuliaCon submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @vchuravy it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```


**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for the assigned editor (@vchuravy) to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](http://bit.ly/2V9GSFq) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
Failed to discover a valid open source license.

**Comment by whedon** [comment]
PDF failed to compile for issue #44 with the following error: 

 rm: cannot remove '*.aux': No such file or directory
Latexmk: This is Latexmk, John Collins, 17 Jan. 2018, version: 4.55.
Rule 'pdflatex': Rules & subrules not known to be previously run:
   pdflatex
Rule 'pdflatex': The following rules & subrules became out-of-date:
      'pdflatex'
------------
Run number 1 of rule 'pdflatex'
------------
------------
Running 'pdflatex  -recorder  "paper.tex"'
------------
===========Latexmk: Missing input file: 'algorithm2e.sty' from line
  '! LaTeX Error: File `algorithm2e.sty' not found.'
Latexmk: Missing input file: 'algorithm2e.sty' from line
  '! LaTeX Error: File `algorithm2e.sty' not found.'
Failure to make 'paper.pdf'
Collected error summary (may duplicate other messages):
  pdflatex: Command for 'pdflatex' gave return code 1
      Refer to 'paper.log' for details
Looks like we failed to compile the PDF

**Comment by vchuravy** [comment]
@mikeinnes please make sure that the submission compiles with whedon

**Comment by vchuravy** [comment]
@whedon add @tlienart as reviewer

**Comment by whedon** [comment]
OK, @tlienart is now a reviewer

**Comment by MikeInnes** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #44 with the following error: 

 rm: cannot remove '*.aux': No such file or directory
Latexmk: This is Latexmk, John Collins, 17 Jan. 2018, version: 4.55.
Rule 'pdflatex': Rules & subrules not known to be previously run:
   pdflatex
Rule 'pdflatex': The following rules & subrules became out-of-date:
      'pdflatex'
------------
Run number 1 of rule 'pdflatex'
------------
------------
Running 'pdflatex  -recorder  "paper.tex"'
------------
===========Latexmk: Missing input file: 'todonotes.sty' from line
  '! LaTeX Error: File `todonotes.sty' not found.'
Latexmk: Missing input file: 'todonotes.sty' from line
  '! LaTeX Error: File `todonotes.sty' not found.'
Failure to make 'paper.pdf'
Collected error summary (may duplicate other messages):
  pdflatex: Command for 'pdflatex' gave return code 1
      Refer to 'paper.log' for details
Looks like we failed to compile the PDF

**Comment by MikeInnes** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #44 with the following error: 

 rm: cannot remove '*.aux': No such file or directory
Latexmk: This is Latexmk, John Collins, 17 Jan. 2018, version: 4.55.
Rule 'pdflatex': Rules & subrules not known to be previously run:
   pdflatex
Rule 'pdflatex': The following rules & subrules became out-of-date:
      'pdflatex'
------------
Run number 1 of rule 'pdflatex'
------------
------------
Running 'pdflatex  -recorder  "paper.tex"'
------------
===========Latexmk: Missing input file: 'comment.sty' from line
  '! LaTeX Error: File `comment.sty' not found.'
Latexmk: Missing input file: 'comment.sty' from line
  '! LaTeX Error: File `comment.sty' not found.'
Failure to make 'paper.pdf'
Collected error summary (may duplicate other messages):
  pdflatex: Command for 'pdflatex' gave return code 1
      Refer to 'paper.log' for details
Looks like we failed to compile the PDF

**Comment by MikeInnes** [comment]
Sorry, not familiar with Whedon so don't know a more efficient way than just removing packages it doesn't like one by one :)

@whedon generate pdf

**Comment by MikeInnes** [comment]
@whedon generate pdf

**Comment by MikeInnes** [comment]
Well, we're using minted for syntax highlighting; should we be doing something different there?

**Comment by vchuravy** [comment]
Normally you can add the `sty` files you need yourself. But minted requires shelling out to python and I am afraid the environment doesn't support that.
We recommend listings for highlighting.

**Comment by MikeInnes** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #44 with the following error: 

 rm: cannot remove '*.aux': No such file or directory
Latexmk: This is Latexmk, John Collins, 17 Jan. 2018, version: 4.55.
Rule 'pdflatex': Rules & subrules not known to be previously run:
   pdflatex
Rule 'pdflatex': The following rules & subrules became out-of-date:
      'pdflatex'
------------
Run number 1 of rule 'pdflatex'
------------
------------
Running 'pdflatex  -recorder  "paper.tex"'
------------
Latexmk: List of undefined refs and citations:
  Citation `2019sbc' on page 3 undefined on input line 143
  Citation `Flux.jl-2018' on page 3 undefined on input line 143
  Citation `Gen.jl-2019' on page 2 undefined on input line 70
  Citation `Julia-2017-a' on page 2 undefined on input line 74
  Citation `Turing.jl-2018' on page 2 undefined on input line 70
  Citation `adifor' on page 3 undefined on input line 151
  Citation `baydin2018automatic' on page 3 undefined on input line 151
  Citation `blas' on page 1 undefined on input line 56
  Citation `chen2018neural' on page 1 undefined on input line 58
  Citation `gordon-bell-2018-a' on page 1 undefined on input line 60
  Citation `jax' on page 3 undefined on input line 143
  Citation `jax' on page 3 undefined on input line 145
  Citation `lapack' on page 1 undefined on input line 56
  Citation `mpi' on page 1 undefined on input line 56
  Citation `pytorch' on page 3 undefined on input line 143
  Citation `tensorflow' on page 3 undefined on input line 143
  Reference `chain' on page 3 undefined on input line 169
Latexmk: Summary of warnings:
  Latex failed to resolve 1 reference(s)
  Latex failed to resolve 16 citation(s)
Rule 'pdflatex': File changes, etc:
   Changed files, or newly in use since previous run(s):
      'paper.aux'
------------
Run number 2 of rule 'pdflatex'
------------
------------
Running 'pdflatex  -recorder  "paper.tex"'
------------
Latexmk: List of undefined refs and citations:
  Citation `2019sbc' on page 3 undefined on input line 143
  Citation `Flux.jl-2018' on page 3 undefined on input line 143
  Citation `Gen.jl-2019' on page 2 undefined on input line 70
  Citation `Julia-2017-a' on page 2 undefined on input line 74
  Citation `Turing.jl-2018' on page 2 undefined on input line 70
  Citation `adifor' on page 3 undefined on input line 151
  Citation `baydin2018automatic' on page 3 undefined on input line 151
  Citation `blas' on page 1 undefined on input line 56
  Citation `chen2018neural' on page 1 undefined on input line 58
  Citation `gordon-bell-2018-a' on page 1 undefined on input line 60
  Citation `jax' on page 3 undefined on input line 143
  Citation `jax' on page 3 undefined on input line 145
  Citation `lapack' on page 1 undefined on input line 56
  Citation `mpi' on page 1 undefined on input line 56
  Citation `pytorch' on page 3 undefined on input line 143
  Citation `tensorflow' on page 3 undefined on input line 143
  Reference `chain' on page 3 undefined on input line 169
Latexmk: Summary of warnings:
  Latex failed to resolve 1 reference(s)
  Latex failed to resolve 16 citation(s)
Rule 'pdflatex': File changes, etc:
   Changed files, or newly in use since previous run(s):
      'paper.out'
------------
Run number 3 of rule 'pdflatex'
------------
------------
Running 'pdflatex  -recorder  "paper.tex"'
------------
Latexmk: List of undefined refs and citations:
  Citation `2019sbc' on page 3 undefined on input line 143
  Citation `Flux.jl-2018' on page 3 undefined on input line 143
  Citation `Gen.jl-2019' on page 2 undefined on input line 70
  Citation `Julia-2017-a' on page 2 undefined on input line 74
  Citation `Turing.jl-2018' on page 2 undefined on input line 70
  Citation `adifor' on page 3 undefined on input line 151
  Citation `baydin2018automatic' on page 3 undefined on input line 151
  Citation `blas' on page 1 undefined on input line 56
  Citation `chen2018neural' on page 1 undefined on input line 58
  Citation `gordon-bell-2018-a' on page 1 undefined on input line 60
  Citation `jax' on page 3 undefined on input line 143
  Citation `jax' on page 3 undefined on input line 145
  Citation `lapack' on page 1 undefined on input line 56
  Citation `mpi' on page 1 undefined on input line 56
  Citation `pytorch' on page 3 undefined on input line 143
  Citation `tensorflow' on page 3 undefined on input line 143
  Reference `chain' on page 3 undefined on input line 169
Latexmk: Summary of warnings:
  Latex failed to resolve 1 reference(s)
  Latex failed to resolve 16 citation(s)
Failure to make 'paper.pdf'
Collected error summary (may duplicate other messages):
  pdflatex: Command for 'pdflatex' gave return code 1
      Refer to 'paper.log' for details
Looks like we failed to compile the PDF

**Comment by MikeInnes** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/JuliaCon/proceedings-papers/blob/jcon.00044/jcon.00044/10.21105.jcon.00044.pdf)

**Comment by MikeInnes** [comment]
Alright, that was a journey, but we got there.

**Comment by vchuravy** [comment]
Thanks Mike!

**Comment by vchuravy** [comment]
@whedon add @jiahao as reviewer

**Comment by whedon** [comment]
OK, @jiahao is now a reviewer

**Comment by vchuravy** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/JuliaCon/proceedings-review/issues/55. Feel free to close this issue now!
