### ISSUE TITLE
[PRE REVIEW]: Circuitscape in Julia: High Performance Connectivity Modelling to Support Conservation Decisions

### ISSUE THREAD

**Issue by whedon** [JuliaCon/proceedings-review#46]
**Submitting author:** @ranjanan (<a href="http://orcid.org/0000-0002-4409-3937">Ranjan Anantharaman</a>)
**Repository:** <a href="https://github.com/Circuitscape/Circuitscape.jl" target ="_blank">https://github.com/Circuitscape/Circuitscape.jl</a>
**Editor:** @matbesancon
**Reviewers:** @vlandau

**Author instructions**

Thanks for submitting your paper to JuliaCon @ranjanan. The JuliaCon editor @matbesancon, will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@ranjanan if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](http://bit.ly/2V9GSFq) have already agreed to review for JuliaCon and may be suitable for this submission.

**Editor instructions**

The JuliaCon submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @matbesancon it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```


**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for the assigned editor (@matbesancon) to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](http://bit.ly/2V9GSFq) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/JuliaCon/proceedings-papers/blob/jcon.00046/jcon.00046/10.21105.jcon.00046.pdf)

**Comment by matbesancon** [comment]
@ranjanan hi, the paper is the template we provided

**Comment by ranjanan** [comment]
@matbesancon oh no, my paper.yml and my paper.tex are updated. I do see that paper.pdf is the template. Do I delete that? Do you know how I can debug this?

**Comment by matbesancon** [comment]
you can remove the paper.pdf from the template yes.

- You can debug locally using https://proceedings.juliacon.org/guide/authors/
- You can generate the pdf online using the command: `@whedon generate pdf`

**Comment by matbesancon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/JuliaCon/proceedings-papers/blob/jcon.00046/jcon.00046/10.21105.jcon.00046.pdf)

**Comment by matbesancon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/JuliaCon/proceedings-papers/blob/jcon.00046/jcon.00046/10.21105.jcon.00046.pdf)

**Comment by matbesancon** [comment]
@whedon generate pdf from branch master

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch master. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/JuliaCon/proceedings-papers/blob/jcon.00046/jcon.00046/10.21105.jcon.00046.pdf)

**Comment by matbesancon** [comment]
@ranjanan yes I think you need to remove from the github repo the pdf

**Comment by ranjanan** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #46 with the following error: 

 rm: cannot remove '*.aux': No such file or directory
Latexmk: This is Latexmk, John Collins, 17 Jan. 2018, version: 4.55.
Rule 'pdflatex': Rules & subrules not known to be previously run:
   pdflatex
Rule 'pdflatex': The following rules & subrules became out-of-date:
      'pdflatex'
------------
Run number 1 of rule 'pdflatex'
------------
------------
Running 'pdflatex  -recorder  "paper.tex"'
------------
===========Latexmk: Missing input file: 'algorithm2e.sty' from line
  '! LaTeX Error: File `algorithm2e.sty' not found.'
Latexmk: Missing input file: 'algorithm2e.sty' from line
  '! LaTeX Error: File `algorithm2e.sty' not found.'
Failure to make 'paper.pdf'
Collected error summary (may duplicate other messages):
  pdflatex: Command for 'pdflatex' gave return code 1
      Refer to 'paper.log' for details
Looks like we failed to compile the PDF

**Comment by matbesancon** [comment]
missing dependencies, they should be added to the folder

**Comment by ranjanan** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #46 with the following error: 

 rm: cannot remove '*.aux': No such file or directory
Latexmk: This is Latexmk, John Collins, 17 Jan. 2018, version: 4.55.
Rule 'pdflatex': Rules & subrules not known to be previously run:
   pdflatex
Rule 'pdflatex': The following rules & subrules became out-of-date:
      'pdflatex'
------------
Run number 1 of rule 'pdflatex'
------------
------------
Running 'pdflatex  -recorder  "paper.tex"'
------------
===========Latexmk: Missing input file: 'ifoddpage.sty' from line
  '! LaTeX Error: File `ifoddpage.sty' not found.'
Latexmk: Missing input file: 'ifoddpage.sty' from line
  '! LaTeX Error: File `ifoddpage.sty' not found.'
Failure to make 'paper.pdf'
Collected error summary (may duplicate other messages):
  pdflatex: Command for 'pdflatex' gave return code 1
      Refer to 'paper.log' for details
Looks like we failed to compile the PDF

**Comment by ranjanan** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/JuliaCon/proceedings-papers/blob/jcon.00046/jcon.00046/10.21105.jcon.00046.pdf)

**Comment by ranjanan** [comment]
@matbesancon I just uploaded a manually generated paper.pdf from overleaf. Would that do?

**Comment by matbesancon** [comment]
that's not the easiest thing to review, it means the reviewers need to read the PDF and cannot review on the source directly. Can you plase remove the pdf from the `paper` directory, the tex should just work like that

**Comment by ranjanan** [comment]
I see, alright. I'll keep plugging away at this. @whedon generate pdf

**Comment by ranjanan** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #46 with the following error: 

 rm: cannot remove '*.aux': No such file or directory
Latexmk: This is Latexmk, John Collins, 17 Jan. 2018, version: 4.55.
Rule 'pdflatex': Rules & subrules not known to be previously run:
   pdflatex
Rule 'pdflatex': The following rules & subrules became out-of-date:
      'pdflatex'
------------
Run number 1 of rule 'pdflatex'
------------
------------
Running 'pdflatex  -recorder  "paper.tex"'
------------
===========Latexmk: Missing input file: 'ifoddpage.sty' from line
  '! LaTeX Error: File `ifoddpage.sty' not found.'
Latexmk: Missing input file: 'ifoddpage.sty' from line
  '! LaTeX Error: File `ifoddpage.sty' not found.'
Failure to make 'paper.pdf'
Collected error summary (may duplicate other messages):
  pdflatex: Command for 'pdflatex' gave return code 1
      Refer to 'paper.log' for details
Looks like we failed to compile the PDF

**Comment by ranjanan** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/JuliaCon/proceedings-papers/blob/jcon.00046/jcon.00046/10.21105.jcon.00046.pdf)

**Comment by ranjanan** [comment]
@matbesancon it works now

**Comment by matbesancon** [comment]
@ranjanan can you remove the line `\bibliographystyle{apalike}` from your paper? There is already a citing style generated in the bst, you don't need to specify it

**Comment by ranjanan** [comment]
Sure, removed it.

@whedon generate pdf

**Comment by ranjanan** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/JuliaCon/proceedings-papers/blob/jcon.00046/jcon.00046/10.21105.jcon.00046.pdf)

**Comment by ranjanan** [comment]
This messed up the citations, for some reason. :thinking:

**Comment by ranjanan** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/JuliaCon/proceedings-papers/blob/jcon.00046/jcon.00046/10.21105.jcon.00046.pdf)

**Comment by ranjanan** [comment]
Ok, looks good to me now.

**Comment by ranjanan** [comment]
@jpfairbanks would you like to review this?

**Comment by ranjanan** [comment]
@vlandau would you be able to review this?

**Comment by vlandau** [comment]
@ranjanan sure, I would be happy to. I will be out until Jan. 2nd, but after that I can carve out time to review. Sorry for the late reply here.

**Comment by ranjanan** [comment]
@vlandau bump

**Comment by vlandau** [comment]
@ranjanan can you let me know what you're looking specifically in a review? Hadn't started since I hadn't heard from you about it after responding. Feel free to follow up on email.

**Comment by vlandau** [comment]
@ranjanan just following up here in addition to the email I sent you to mark my review as complete.

**Comment by ranjanan** [comment]
[Anatharaman-et-al-2020-VL-review.pdf](https://github.com/JuliaCon/proceedings-review/files/4447003/Anatharaman-et-al-2020-VL-review.pdf)

**Comment by ranjanan** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/JuliaCon/proceedings-papers/blob/jcon.00046/jcon.00046/10.21105.jcon.00046.pdf)

**Comment by ranjanan** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/JuliaCon/proceedings-papers/blob/jcon.00046/jcon.00046/10.21105.jcon.00046.pdf)

**Comment by ranjanan** [comment]
@matbesancon could you remove reviewers needed here? Also, I have incorporated the reviewers feedback and produced a new proof. If there are no further issues, could you consider accepting this?

**Comment by matbesancon** [comment]
@whedon start review

**Comment by whedon** [comment]
It looks like you don't have an editor and reviewer assigned yet so I can't start the review. Try one or more of these commands:

```
# Change editorial assignment
@whedon assign @username as editor

# Assign a GitHub user as the sole reviewer of this submission
@whedon assign @username as reviewer

# Add a GitHub user to the reviewers of this submission
@whedon add @username as reviewer
```

**Comment by matbesancon** [comment]
@whedon assign @vlandau as reviewer

**Comment by whedon** [comment]
OK, @vlandau is now a reviewer

**Comment by matbesancon** [comment]
@whedon start review
