### ISSUE TITLE
[PRE REVIEW]: JuliaDB: addressing the two-language problem in analytical databases

### ISSUE THREAD

**Issue by whedon** [JuliaCon/proceedings-review#47]
**Submitting author:** @shashi (<a href="http://orcid.org/0000-0001-7100-7419">Shashi Gowda</a>)
**Repository:** <a href="https://github.com/shashi/JuliaDB-JuliaCon2019Proceedings" target ="_blank">https://github.com/shashi/JuliaDB-JuliaCon2019Proceedings</a>
**Editor:** @matbesancon
**Reviewer:** Pending

**Author instructions**

Thanks for submitting your paper to JuliaCon @shashi. The JuliaCon editor @matbesancon, will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@shashi if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](http://bit.ly/2V9GSFq) have already agreed to review for JuliaCon and may be suitable for this submission.

**Editor instructions**

The JuliaCon submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @matbesancon it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```


**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for the assigned editor (@matbesancon) to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](http://bit.ly/2V9GSFq) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
Failed to discover a valid open source license.

**Comment by whedon** [comment]
PDF failed to compile for issue #47 with the following error: 

 rm: cannot remove '*.aux': No such file or directory
Latexmk: This is Latexmk, John Collins, 17 Jan. 2018, version: 4.55.
Rule 'pdflatex': Rules & subrules not known to be previously run:
   pdflatex
Rule 'pdflatex': The following rules & subrules became out-of-date:
      'pdflatex'
------------
Run number 1 of rule 'pdflatex'
------------
------------
Running 'pdflatex  -recorder  "paper.tex"'
------------
Latexmk: List of undefined refs and citations:
  Citation `bezanson2017julia' on page 1 undefined on input line 25
  Citation `bezanson2017julia' on page 1 undefined on input line 44
  Citation `dplyr' on page 1 undefined on input line 36
  Citation `giordano2016' on page 3 undefined on input line 140
  Citation `juliadbapi' on page 2 undefined on input line 96
  Citation `mckinney-proc-scipy-2010' on page 1 undefined on input line 36
  Citation `pyspark' on page 1 undefined on input line 42
  Citation `scalaslow' on page 1 undefined on input line 42
  Citation `spark' on page 1 undefined on input line 42
  Citation `sparkr' on page 1 undefined on input line 42
  Citation `wes2017' on page 1 undefined on input line 55
  Reference `fig:stringarray' on page 2 undefined on input line 107
  Reference `sec:sort' on page 2 undefined on input line 96
Latexmk: Summary of warnings:
  Latex failed to resolve 2 reference(s)
  Latex failed to resolve 11 citation(s)
Rule 'pdflatex': File changes, etc:
   Changed files, or newly in use since previous run(s):
      'paper.aux'
------------
Run number 2 of rule 'pdflatex'
------------
------------
Running 'pdflatex  -recorder  "paper.tex"'
------------
Latexmk: List of undefined refs and citations:
  Citation `bezanson2017julia' on page 1 undefined on input line 25
  Citation `bezanson2017julia' on page 1 undefined on input line 44
  Citation `dplyr' on page 1 undefined on input line 36
  Citation `giordano2016' on page 3 undefined on input line 140
  Citation `juliadbapi' on page 2 undefined on input line 96
  Citation `mckinney-proc-scipy-2010' on page 1 undefined on input line 36
  Citation `pyspark' on page 1 undefined on input line 42
  Citation `scalaslow' on page 1 undefined on input line 42
  Citation `spark' on page 1 undefined on input line 42
  Citation `sparkr' on page 1 undefined on input line 42
  Citation `wes2017' on page 1 undefined on input line 55
  Reference `fig:stringarray' on page 2 undefined on input line 107
Latexmk: Summary of warnings:
  Latex failed to resolve 1 reference(s)
  Latex failed to resolve 11 citation(s)
Rule 'pdflatex': File changes, etc:
   Changed files, or newly in use since previous run(s):
      'paper.out'
------------
Run number 3 of rule 'pdflatex'
------------
------------
Running 'pdflatex  -recorder  "paper.tex"'
------------
Latexmk: List of undefined refs and citations:
  Citation `bezanson2017julia' on page 1 undefined on input line 25
  Citation `bezanson2017julia' on page 1 undefined on input line 44
  Citation `dplyr' on page 1 undefined on input line 36
  Citation `giordano2016' on page 3 undefined on input line 140
  Citation `juliadbapi' on page 2 undefined on input line 96
  Citation `mckinney-proc-scipy-2010' on page 1 undefined on input line 36
  Citation `pyspark' on page 1 undefined on input line 42
  Citation `scalaslow' on page 1 undefined on input line 42
  Citation `spark' on page 1 undefined on input line 42
  Citation `sparkr' on page 1 undefined on input line 42
  Citation `wes2017' on page 1 undefined on input line 55
  Reference `fig:stringarray' on page 2 undefined on input line 107
Latexmk: Summary of warnings:
  Latex failed to resolve 1 reference(s)
  Latex failed to resolve 11 citation(s)
Failure to make 'paper.pdf'
Collected error summary (may duplicate other messages):
  pdflatex: Command for 'pdflatex' gave return code 1
      Refer to 'paper.log' for details
Looks like we failed to compile the PDF

**Comment by matbesancon** [comment]
hi @shashi, could you put the paper directory where the related code is? (if not possible this option is fine)

**Comment by matbesancon** [comment]
ping @shashi

**Comment by shashi** [comment]
Many of the citations it claims to be missing are present in `ref.bib`...

**Comment by shashi** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #47 with the following error: 

 rm: cannot remove '*.aux': No such file or directory
Latexmk: This is Latexmk, John Collins, 17 Jan. 2018, version: 4.55.
Rule 'pdflatex': Rules & subrules not known to be previously run:
   pdflatex
Rule 'pdflatex': The following rules & subrules became out-of-date:
      'pdflatex'
------------
Run number 1 of rule 'pdflatex'
------------
------------
Running 'pdflatex  -recorder  "paper.tex"'
------------
Latexmk: List of undefined refs and citations:
  Citation `bezanson2017julia' on page 1 undefined on input line 25
  Citation `bezanson2017julia' on page 1 undefined on input line 44
  Citation `dplyr' on page 1 undefined on input line 36
  Citation `giordano2016' on page 3 undefined on input line 140
  Citation `juliadbapi' on page 2 undefined on input line 96
  Citation `mckinney-proc-scipy-2010' on page 1 undefined on input line 36
  Citation `pyspark' on page 1 undefined on input line 42
  Citation `scalaslow' on page 1 undefined on input line 42
  Citation `spark' on page 1 undefined on input line 42
  Citation `sparkr' on page 1 undefined on input line 42
  Citation `wes2017' on page 1 undefined on input line 55
  Reference `fig:stringarray' on page 2 undefined on input line 107
  Reference `sec:sort' on page 2 undefined on input line 96
Latexmk: Summary of warnings:
  Latex failed to resolve 2 reference(s)
  Latex failed to resolve 11 citation(s)
Rule 'pdflatex': File changes, etc:
   Changed files, or newly in use since previous run(s):
      'paper.aux'
------------
Run number 2 of rule 'pdflatex'
------------
------------
Running 'pdflatex  -recorder  "paper.tex"'
------------
Latexmk: List of undefined refs and citations:
  Citation `bezanson2017julia' on page 1 undefined on input line 25
  Citation `bezanson2017julia' on page 1 undefined on input line 44
  Citation `dplyr' on page 1 undefined on input line 36
  Citation `giordano2016' on page 3 undefined on input line 140
  Citation `juliadbapi' on page 2 undefined on input line 96
  Citation `mckinney-proc-scipy-2010' on page 1 undefined on input line 36
  Citation `pyspark' on page 1 undefined on input line 42
  Citation `scalaslow' on page 1 undefined on input line 42
  Citation `spark' on page 1 undefined on input line 42
  Citation `sparkr' on page 1 undefined on input line 42
  Citation `wes2017' on page 1 undefined on input line 55
  Reference `fig:stringarray' on page 2 undefined on input line 107
Latexmk: Summary of warnings:
  Latex failed to resolve 1 reference(s)
  Latex failed to resolve 11 citation(s)
Rule 'pdflatex': File changes, etc:
   Changed files, or newly in use since previous run(s):
      'paper.out'
------------
Run number 3 of rule 'pdflatex'
------------
------------
Running 'pdflatex  -recorder  "paper.tex"'
------------
Latexmk: List of undefined refs and citations:
  Citation `bezanson2017julia' on page 1 undefined on input line 25
  Citation `bezanson2017julia' on page 1 undefined on input line 44
  Citation `dplyr' on page 1 undefined on input line 36
  Citation `giordano2016' on page 3 undefined on input line 140
  Citation `juliadbapi' on page 2 undefined on input line 96
  Citation `mckinney-proc-scipy-2010' on page 1 undefined on input line 36
  Citation `pyspark' on page 1 undefined on input line 42
  Citation `scalaslow' on page 1 undefined on input line 42
  Citation `spark' on page 1 undefined on input line 42
  Citation `sparkr' on page 1 undefined on input line 42
  Citation `wes2017' on page 1 undefined on input line 55
  Reference `fig:stringarray' on page 2 undefined on input line 107
Latexmk: Summary of warnings:
  Latex failed to resolve 1 reference(s)
  Latex failed to resolve 11 citation(s)
Failure to make 'paper.pdf'
Collected error summary (may duplicate other messages):
  pdflatex: Command for 'pdflatex' gave return code 1
      Refer to 'paper.log' for details
Looks like we failed to compile the PDF

**Comment by vchuravy** [comment]
What happens if you just run `latexmk` on a local copy of the repository?

**Comment by vchuravy** [comment]
@shashi I have moved this from the proceedings to the planned special issue. This should give you a bit more time to finish up things.

**Comment by vchuravy** [comment]
@shashi are you still interested in having this appear in the JuliaCon proceedings? If not I will withdraw this submission.

**Comment by matbesancon** [comment]
ping @shashi

**Comment by vchuravy** [comment]
@shashi If you are still interested in publishing this in the JuliaCon proceedings please feel free to resubmit. Since there hasn't been much movement recently I will close this.

**Comment by lucaferranti** [comment]
@editorialbot reject
