### ISSUE TITLE
[PRE REVIEW]: Basic Threading Examples in JuliaLang v1.3

### ISSUE THREAD

**Issue by whedon** [JuliaCon/proceedings-review#49]
**Submitting author:** @vtjnash (<a href="http://orcid.org/0000-0002-8991-0523">Jameson Nash</a>)
**Repository:** <a href="https://github.com/vtjnash/JuliaCon2019Threading" target ="_blank">https://github.com/vtjnash/JuliaCon2019Threading</a>
**Editor:** @vchuravy
**Reviewers:** @ArchRobison, @wsmoses 

**Author instructions**

Thanks for submitting your paper to JuliaCon @vtjnash. The JuliaCon editor @vchuravy, will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@vtjnash if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](http://bit.ly/2V9GSFq) have already agreed to review for JuliaCon and may be suitable for this submission.

**Editor instructions**

The JuliaCon submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @vchuravy it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```


**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for the assigned editor (@vchuravy) to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](http://bit.ly/2V9GSFq) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #49 with the following error: 

 /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `block in find': No such file or directory - tmp/49 (Errno::ENOENT)
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `collect!'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `find'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-61fc68877343/lib/whedon/processor.rb:61:in `find_paper_paths'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-61fc68877343/bin/whedon:50:in `prepare'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-61fc68877343/bin/whedon:116:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by vchuravy** [comment]
@vtjnash please follow the instructions at https://proceedings.juliacon.org/guide/authors/ and setup a Github repository with the paper.

**Comment by vchuravy** [comment]
@whedon compile

**Comment by vchuravy** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #49 with the following error: 

 rm: cannot remove '*.aux': No such file or directory
Latexmk: This is Latexmk, John Collins, 17 Jan. 2018, version: 4.55.
Rule 'pdflatex': Rules & subrules not known to be previously run:
   pdflatex
Rule 'pdflatex': The following rules & subrules became out-of-date:
      'pdflatex'
------------
Run number 1 of rule 'pdflatex'
------------
------------
Running 'pdflatex  -recorder  "paper.tex"'
------------
===========Latexmk: Missing input file: 'mdframed.sty' from line
  '! LaTeX Error: File `mdframed.sty' not found.'
Latexmk: Missing input file: 'mdframed.sty' from line
  '! LaTeX Error: File `mdframed.sty' not found.'
Failure to make 'paper.pdf'
Collected error summary (may duplicate other messages):
  pdflatex: Command for 'pdflatex' gave return code 1
      Refer to 'paper.log' for details
Looks like we failed to compile the PDF

**Comment by whedon** [comment]
Failed to discover a valid open source license.

**Comment by vtjnash** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #49 with the following error: 

 rm: cannot remove '*.aux': No such file or directory
Latexmk: This is Latexmk, John Collins, 17 Jan. 2018, version: 4.55.
Rule 'pdflatex': Rules & subrules not known to be previously run:
   pdflatex
Rule 'pdflatex': The following rules & subrules became out-of-date:
      'pdflatex'
------------
Run number 1 of rule 'pdflatex'
------------
------------
Running 'pdflatex  -recorder  "paper.tex"'
------------
===========Latexmk: Missing input file: 'images/threads_sieve.png' from line
  'LaTeX Warning: File `images/threads_sieve.png' not found on input line 288.'
Latexmk: Missing input file: 'images/threads_sieve.png' from line
  'LaTeX Warning: File `images/threads_sieve.png' not found on input line 288.'
Latexmk: List of undefined refs and citations:
  Citation `Hoare:1978:CSP:359576.359585' on page 3 undefined on input line 285
  Reference `fig:scalings' on page 3 undefined on input line 275
  Reference `fig:sieve' on page 3 undefined on input line 285
Latexmk: Summary of warnings:
  Latex failed to resolve 2 reference(s)
  Latex failed to resolve 1 citation(s)
Rule 'pdflatex': File changes, etc:
   Changed files, or newly in use since previous run(s):
      'paper.aux'
------------
Run number 2 of rule 'pdflatex'
------------
------------
Running 'pdflatex  -recorder  "paper.tex"'
------------
===========Latexmk: Missing input file: 'images/threads_sieve.png' from line
  'LaTeX Warning: File `images/threads_sieve.png' not found on input line 288.'
Latexmk: Missing input file: 'images/threads_sieve.png' from line
  'LaTeX Warning: File `images/threads_sieve.png' not found on input line 288.'
Latexmk: List of undefined refs and citations:
  Citation `Hoare:1978:CSP:359576.359585' on page 3 undefined on input line 285
  Reference `fig:scalings' on page 3 undefined on input line 275
  Reference `fig:sieve' on page 3 undefined on input line 285
Latexmk: Summary of warnings:
  Latex failed to resolve 2 reference(s)
  Latex failed to resolve 1 citation(s)
Rule 'pdflatex': File changes, etc:
   Changed files, or newly in use since previous run(s):
      'paper.out'
------------
Run number 3 of rule 'pdflatex'
------------
------------
Running 'pdflatex  -recorder  "paper.tex"'
------------
===========Latexmk: Missing input file: 'images/threads_sieve.png' from line
  'LaTeX Warning: File `images/threads_sieve.png' not found on input line 288.'
Latexmk: Missing input file: 'images/threads_sieve.png' from line
  'LaTeX Warning: File `images/threads_sieve.png' not found on input line 288.'
Latexmk: List of undefined refs and citations:
  Citation `Hoare:1978:CSP:359576.359585' on page 3 undefined on input line 285
  Reference `fig:scalings' on page 3 undefined on input line 275
  Reference `fig:sieve' on page 3 undefined on input line 285
Latexmk: Summary of warnings:
  Latex failed to resolve 2 reference(s)
  Latex failed to resolve 1 citation(s)
Failure to make 'paper.pdf'
Collected error summary (may duplicate other messages):
  pdflatex: Command for 'pdflatex' gave return code 1
      Refer to 'paper.log' for details
Looks like we failed to compile the PDF

**Comment by vtjnash** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/JuliaCon/proceedings-papers/blob/jcon.00049/jcon.00049/10.21105.jcon.00049.pdf)

**Comment by vtjnash** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #49 with the following error: 

 /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-61fc68877343/lib/whedon/author.rb:68:in `block in build_affiliation_string': Problem with affiliations for Jameson Nash, perhaps the affiliations index need quoting? (RuntimeError)
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-61fc68877343/lib/whedon/author.rb:67:in `each'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-61fc68877343/lib/whedon/author.rb:67:in `build_affiliation_string'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-61fc68877343/lib/whedon/author.rb:17:in `initialize'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-61fc68877343/lib/whedon.rb:191:in `new'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-61fc68877343/lib/whedon.rb:191:in `block in parse_authors'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-61fc68877343/lib/whedon.rb:188:in `each'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-61fc68877343/lib/whedon.rb:188:in `parse_authors'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-61fc68877343/lib/whedon.rb:91:in `initialize'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-61fc68877343/lib/whedon/processor.rb:36:in `new'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-61fc68877343/lib/whedon/processor.rb:36:in `set_paper'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-61fc68877343/bin/whedon:55:in `prepare'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-61fc68877343/bin/whedon:116:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by vtjnash** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/JuliaCon/proceedings-papers/blob/jcon.00049/jcon.00049/10.21105.jcon.00049.pdf)

**Comment by vchuravy** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List all of Whedon's capabilities
@whedon commands

# Assign a GitHub user as the sole reviewer of this submission
@whedon assign @username as reviewer

# Add a GitHub user to the reviewers of this submission
@whedon add @username as reviewer

# Remove a GitHub user from the reviewers of this submission
@whedon remove @username as reviewer

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

# Change editorial assignment
@whedon assign @username as editor

# Set the software archive DOI at the top of the issue e.g.
@whedon set 10.0000/zenodo.00000 as archive

# Set the software version at the top of the issue e.g.
@whedon set v1.0.1 as version

# Open the review issue
@whedon start review

EDITORIAL TASKS

# Compile the paper
@whedon generate pdf

# Compile the paper from alternative branch
@whedon generate pdf from branch custom-branch-name

# Remind an author or reviewer to return to a review after a
# certain period of time (supported units days and weeks)
@whedon remind @reviewer in 2 weeks

# Ask Whedon to accept the paper and deposit with Crossref
@whedon accept

# Ask Whedon to check the references for missing DOIs
@whedon check references

```

**Comment by vchuravy** [comment]
@whedon assign @wsmoses as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @wsmoses

**Comment by vtjnash** [comment]
@JeffBezanson @kpamnany

**Comment by vchuravy** [comment]
@whedon assign @ArchRobison as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @ArchRobison

**Comment by vchuravy** [comment]
@whedon add @wsmoses  as reviewer

**Comment by whedon** [comment]
OK, @wsmoses  is now a reviewer

**Comment by ArchRobison** [comment]
@whedon start review

**Comment by whedon** [comment]
I'm sorry @ArchRobison, I'm afraid I can't do that. That's something only editors are allowed to do.

**Comment by ArchRobison** [comment]
I had a few comments,  mostly editorial.  Here's a PDF with my markup [10.21105.jcon.00049.pdf](https://github.com/JuliaCon/proceedings-review/files/3644900/10.21105.jcon.00049.pdf)

**Comment by ArchRobison** [comment]
I had a few comments.  Here's a copy with my markup.
[10.21105.jcon.00049 - ADR comments.pdf](https://github.com/JuliaCon/proceedings-review/files/3644904/10.21105.jcon.00049.-.ADR.comments.pdf)

**Comment by vchuravy** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/JuliaCon/proceedings-review/issues/54. Feel free to close this issue now!
