### ISSUE TITLE
[PRE REVIEW]: ModelingToolkit.jl: An Intermediate Representation for Scientific Domain-Specific Languages

### ISSUE THREAD

**Issue by whedon** [JuliaCon/proceedings-review#50]
**Submitting author:** @HarrisonGrodin (<a href="http://orcid.org/0000-0002-0947-3520">Harrison Grodin</a>)
**Repository:** <a href="https://github.com/JuliaDiffEq/ModelingToolkit.jl" target ="_blank">https://github.com/JuliaDiffEq/ModelingToolkit.jl</a>
**Editor:** @matbesancon
**Reviewers:** @clagms, @jpfairbanks

**Author instructions**

Thanks for submitting your paper to JuliaCon @HarrisonGrodin. The JuliaCon editor @matbesancon, will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@HarrisonGrodin if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](http://bit.ly/2V9GSFq) have already agreed to review for JuliaCon and may be suitable for this submission.

**Editor instructions**

The JuliaCon submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @matbesancon it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```


**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for the assigned editor (@matbesancon) to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](http://bit.ly/2V9GSFq) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
Failed to discover a valid open source license.

**Comment by whedon** [comment]
PDF failed to compile for issue #50 with the following error: 

 rm: cannot remove '*.aux': No such file or directory
Latexmk: This is Latexmk, John Collins, 17 Jan. 2018, version: 4.55.
Rule 'pdflatex': Rules & subrules not known to be previously run:
   pdflatex
Rule 'pdflatex': The following rules & subrules became out-of-date:
      'pdflatex'
------------
Run number 1 of rule 'pdflatex'
------------
------------
Running 'pdflatex  -recorder  "paper.tex"'
------------
Latexmk: List of undefined refs and citations:
  Citation `alan_c._hindmarsh_sundials:_2005' on page 1 undefined on input line 43
  Citation `bezanson_julia:_2017' on page 1 undefined on input line 53
  Citation `christopher_rackauckas_differentialequations.jl_2017' on page 1 undefined on input line 53
  Citation `diffeqbiological' on page 1 undefined on input line 53
  Citation `doi:10.1137/0909014' on page 1 undefined on input line 43
  Citation `mattsson_modelica_1997' on page 1 undefined on input line 43
  Citation `petzold_description_nodate' on page 1 undefined on input line 43
  Citation `sheiner1977estimation' on page 1 undefined on input line 43
  Reference `code:reaction' on page 1 undefined on input line 53
Latexmk: Summary of warnings:
  Latex failed to resolve 1 reference(s)
  Latex failed to resolve 8 citation(s)
Rule 'pdflatex': File changes, etc:
   Changed files, or newly in use since previous run(s):
      'paper.aux'
------------
Run number 2 of rule 'pdflatex'
------------
------------
Running 'pdflatex  -recorder  "paper.tex"'
------------
Latexmk: List of undefined refs and citations:
  Citation `alan_c._hindmarsh_sundials:_2005' on page 1 undefined on input line 43
  Citation `bezanson_julia:_2017' on page 1 undefined on input line 53
  Citation `christopher_rackauckas_differentialequations.jl_2017' on page 1 undefined on input line 53
  Citation `diffeqbiological' on page 1 undefined on input line 53
  Citation `doi:10.1137/0909014' on page 1 undefined on input line 43
  Citation `mattsson_modelica_1997' on page 1 undefined on input line 43
  Citation `petzold_description_nodate' on page 1 undefined on input line 43
  Citation `sheiner1977estimation' on page 1 undefined on input line 43
  Reference `code:reaction' on page 1 undefined on input line 53
Latexmk: Summary of warnings:
  Latex failed to resolve 1 reference(s)
  Latex failed to resolve 8 citation(s)
Rule 'pdflatex': File changes, etc:
   Changed files, or newly in use since previous run(s):
      'paper.out'
------------
Run number 3 of rule 'pdflatex'
------------
------------
Running 'pdflatex  -recorder  "paper.tex"'
------------
Latexmk: List of undefined refs and citations:
  Citation `alan_c._hindmarsh_sundials:_2005' on page 1 undefined on input line 43
  Citation `bezanson_julia:_2017' on page 1 undefined on input line 53
  Citation `christopher_rackauckas_differentialequations.jl_2017' on page 1 undefined on input line 53
  Citation `diffeqbiological' on page 1 undefined on input line 53
  Citation `doi:10.1137/0909014' on page 1 undefined on input line 43
  Citation `mattsson_modelica_1997' on page 1 undefined on input line 43
  Citation `petzold_description_nodate' on page 1 undefined on input line 43
  Citation `sheiner1977estimation' on page 1 undefined on input line 43
  Reference `code:reaction' on page 1 undefined on input line 53
Latexmk: Summary of warnings:
  Latex failed to resolve 1 reference(s)
  Latex failed to resolve 8 citation(s)
Failure to make 'paper.pdf'
Collected error summary (may duplicate other messages):
  pdflatex: Command for 'pdflatex' gave return code 1
      Refer to 'paper.log' for details
Looks like we failed to compile the PDF

**Comment by matbesancon** [comment]
Hi @HarrisonGrodin, for the juliacon proceedings we prefer having the paper in the same repo as the code. If you don't want to pollute the repo you can put it in another branch

**Comment by ChrisRackauckas** [comment]
Yeah, we can do that.

**Comment by matbesancon** [comment]
ping me here with the repo (and branch if not on master) when it's ready to build

**Comment by HarrisonGrodin** [comment]
I've added it to the `paper` branch, in the `paper` directory:
https://github.com/JuliaDiffEq/ModelingToolkit.jl/tree/paper

**Comment by matbesancon** [comment]
@whedon generate PDF from branch paper

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #50 with the following error: 

 Can't find any papers to compile :-(

**Comment by matbesancon** [comment]
@whedon generate pdf from branch paper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch paper. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #50 with the following error: 

 rm: cannot remove '*.aux': No such file or directory
Latexmk: This is Latexmk, John Collins, 17 Jan. 2018, version: 4.55.
Rule 'pdflatex': Rules & subrules not known to be previously run:
   pdflatex
Rule 'pdflatex': The following rules & subrules became out-of-date:
      'pdflatex'
------------
Run number 1 of rule 'pdflatex'
------------
------------
Running 'pdflatex  -recorder  "paper.tex"'
------------
Latexmk: List of undefined refs and citations:
  Citation `alan_c._hindmarsh_sundials:_2005' on page 1 undefined on input line 43
  Citation `bezanson_julia:_2017' on page 1 undefined on input line 53
  Citation `christopher_rackauckas_differentialequations.jl_2017' on page 1 undefined on input line 53
  Citation `diffeqbiological' on page 1 undefined on input line 53
  Citation `doi:10.1137/0909014' on page 1 undefined on input line 43
  Citation `mattsson_modelica_1997' on page 1 undefined on input line 43
  Citation `petzold_description_nodate' on page 1 undefined on input line 43
  Citation `sheiner1977estimation' on page 1 undefined on input line 43
  Reference `code:reaction' on page 1 undefined on input line 53
Latexmk: Summary of warnings:
  Latex failed to resolve 1 reference(s)
  Latex failed to resolve 8 citation(s)
Rule 'pdflatex': File changes, etc:
   Changed files, or newly in use since previous run(s):
      'paper.aux'
------------
Run number 2 of rule 'pdflatex'
------------
------------
Running 'pdflatex  -recorder  "paper.tex"'
------------
Latexmk: List of undefined refs and citations:
  Citation `alan_c._hindmarsh_sundials:_2005' on page 1 undefined on input line 43
  Citation `bezanson_julia:_2017' on page 1 undefined on input line 53
  Citation `christopher_rackauckas_differentialequations.jl_2017' on page 1 undefined on input line 53
  Citation `diffeqbiological' on page 1 undefined on input line 53
  Citation `doi:10.1137/0909014' on page 1 undefined on input line 43
  Citation `mattsson_modelica_1997' on page 1 undefined on input line 43
  Citation `petzold_description_nodate' on page 1 undefined on input line 43
  Citation `sheiner1977estimation' on page 1 undefined on input line 43
  Reference `code:reaction' on page 1 undefined on input line 53
Latexmk: Summary of warnings:
  Latex failed to resolve 1 reference(s)
  Latex failed to resolve 8 citation(s)
Rule 'pdflatex': File changes, etc:
   Changed files, or newly in use since previous run(s):
      'paper.out'
------------
Run number 3 of rule 'pdflatex'
------------
------------
Running 'pdflatex  -recorder  "paper.tex"'
------------
Latexmk: List of undefined refs and citations:
  Citation `alan_c._hindmarsh_sundials:_2005' on page 1 undefined on input line 43
  Citation `bezanson_julia:_2017' on page 1 undefined on input line 53
  Citation `christopher_rackauckas_differentialequations.jl_2017' on page 1 undefined on input line 53
  Citation `diffeqbiological' on page 1 undefined on input line 53
  Citation `doi:10.1137/0909014' on page 1 undefined on input line 43
  Citation `mattsson_modelica_1997' on page 1 undefined on input line 43
  Citation `petzold_description_nodate' on page 1 undefined on input line 43
  Citation `sheiner1977estimation' on page 1 undefined on input line 43
  Reference `code:reaction' on page 1 undefined on input line 53
Latexmk: Summary of warnings:
  Latex failed to resolve 1 reference(s)
  Latex failed to resolve 8 citation(s)
Failure to make 'paper.pdf'
Collected error summary (may duplicate other messages):
  pdflatex: Command for 'pdflatex' gave return code 1
      Refer to 'paper.log' for details
Looks like we failed to compile the PDF

**Comment by matbesancon** [comment]
@HarrisonGrodin there may be some illegal characters in the bibtex keys?

**Comment by HarrisonGrodin** [comment]
@whedon generate pdf from branch paper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch paper. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/JuliaCon/proceedings-papers/blob/jcon.00050/jcon.00050/10.21105.jcon.00050.pdf)

**Comment by matbesancon** [comment]
@jpfairbanks would you be available to review this proceeding?

**Comment by matbesancon** [comment]
@blegat would you be available to review this proceeding?

**Comment by matbesancon** [comment]
ping @jpfairbanks

**Comment by matbesancon** [comment]
@clagms would you be available to review this proceeding?

**Comment by matbesancon** [comment]
@whedon add @clagms as reviewer

**Comment by whedon** [comment]
OK, @clagms is now a reviewer

**Comment by jpfairbanks** [comment]
Yes

**Comment by matbesancon** [comment]
@whedon add @jpfairbanks as reviewer

**Comment by whedon** [comment]
OK, @jpfairbanks is now a reviewer

**Comment by matbesancon** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/JuliaCon/proceedings-review/issues/52. Feel free to close this issue now!
