### ISSUE TITLE
[REVIEW]: Fashionable Modelling With Flux

### ISSUE THREAD

**Issue by whedon** [JuliaCon/proceedings-review#56]
**Submitting author:** @dhairyagandhi96 (<a href="http://orcid.org/0000-0002-8549-5270">Dhairya Gandhi</a>)
**Repository:** <a href="https://github.com/dhairyagandhi96/flux-juliacon-paper.git" target ="_blank">https://github.com/dhairyagandhi96/flux-juliacon-paper.git</a>
**Editor:** @carstenbauer
**Reviewer:** @denizyuret
**Archive:** Pending

## Status

[![status](https://proceedings.juliacon.org/papers/626f91af151579cb19fcbf3e59586b3a/status.svg)](https://proceedings.juliacon.org/papers/626f91af151579cb19fcbf3e59586b3a)

Status badge code:

```
HTML: <a href="https://submissions.juliacon.org/papers/626f91af151579cb19fcbf3e59586b3a"><img src="https://submissions.juliacon.org/papers/626f91af151579cb19fcbf3e59586b3a/status.svg"></a>
Markdown: [![status](https://submissions.juliacon.org/papers/626f91af151579cb19fcbf3e59586b3a/status.svg)](https://submissions.juliacon.org/papers/626f91af151579cb19fcbf3e59586b3a)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/dhairyagandhi96/flux-juliacon-paper.git" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@denizyuret, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/JuliaCon/proceedings-reviews/invitations

The reviewer guidelines are available here: https://proceedings.juliacon.org/guide/reviewers. Any questions/concerns please let @vchuravy know.

✨ **Please try and complete your review in the next two weeks** ✨

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JuliaCon conflict of interest policy](https://proceedings.juliacon.org/guide/authors#coi) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JuliaCon code of conduct](https://proceedings.juliacon.org/coc).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/dhairyagandhi96/flux-juliacon-paper.git">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Authorship:** Has the submitting author (@dhairyagandhi96) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Paper format

- [x] **Authors:** Does the `paper.tex` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?
- [x] **Page limit:** Is the page limit for full papers respected by the submitted document?

### Content

- [x] **Context:** is the scientific context motivating the work correctly presented?
- [x] **Methodology:** is the approach taken in the work justified, presented with enough details and reference to reproduce it?
- [x] **Results:** are the results presented and compared to approaches with similar goals?

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/JuliaCon/proceedings-papers/blob/jcon.00056/jcon.00056/10.21105.jcon.00056.pdf)

**Comment by denizyuret** [comment]
Some questions:
- [ ] I am not sure what the page limit is. Assuming 8 pages is ok.
- [ ] The repository url points to the paper repo, not Flux.jl. Assuming Flux.jl for other questions.
- [ ] The formatting seems off, lots of space at the bottom of each page, is this normal?

**Comment by dhairyagandhi96** [comment]
Thanks for the review. Following this, we've made some changes to address some of the suggestions.

Re the AlphaGo point; we couldn't converge it for Go.

Per section 3; the GPU functionality, as well as the AD are mature. The acceleration with TPUs, outputting with JS and batching are working prototypes as of now. We plan to expand this functionality in the future.

With regards to Listing 7, it is not meant as a motivating example, rather an illustrative one. Broadcasting would do the same work internally, the vectorisation of the code is the larger question that we've tried to address in that section.

The missing cite to Knet is unintentional and we shall remedy that.

@whedon generate pdf

**Comment by vchuravy** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/JuliaCon/proceedings-papers/blob/jcon.00056/jcon.00056/10.21105.jcon.00056.pdf)

**Comment by vchuravy** [comment]
@dhairyagandhi96 did you address the review?

**Comment by ranjanan** [comment]
@DhairyaLGandhi bump

**Comment by ranjanan** [comment]
@DhairyaLGandhi can you confirm you addressed the review?

**Comment by DhairyaLGandhi** [comment]
Yes will be finishing this over the next couple days

**Comment by vchuravy** [comment]
@whedon remind @DhairyaLGandhi in one week.

**Comment by vchuravy** [comment]
@DhairyaLGandhi  can you add a footnote stating that parts of this paper were presented at the Learningsys workshop?

**Comment by vchuravy** [comment]
@whedon help

**Comment by whedon** [comment]
I'm sorry human, I don't understand that. You can see what commands I support by typing:

```
@whedon commands
```

**Comment by vchuravy** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List all of Whedon's capabilities
@whedon commands

# Assign a GitHub user as the sole reviewer of this submission
@whedon assign @username as reviewer

# Add a GitHub user to the reviewers of this submission
@whedon add @username as reviewer

# Re-invite a reviewer (if they can't update checklists)
@whedon re-invite @username as reviewer

# Remove a GitHub user from the reviewers of this submission
@whedon remove @username as reviewer

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

# Change editorial assignment
@whedon assign @username as editor

# Set the software archive DOI at the top of the issue e.g.
@whedon set 10.0000/zenodo.00000 as archive

# Set the software version at the top of the issue e.g.
@whedon set v1.0.1 as version

# Open the review issue
@whedon start review

EDITORIAL TASKS

# All commands can be run on a non-default branch, to do this pass a custom 
# branch name by following the command with `from branch custom-branch-name`.
# For example:

# Compile the paper
@whedon generate pdf

# Compile the paper from alternative branch
@whedon generate pdf from branch custom-branch-name

# Remind an author or reviewer to return to a review after a
# certain period of time (supported units days and weeks)
@whedon remind @reviewer in 2 weeks

# Ask Whedon to do a dry run of accepting the paper and depositing with Crossref
@whedon recommend-accept

# Ask Whedon to check the references for missing DOIs
@whedon check references

# Ask Whedon to check repository statistics for the submitted software
@whedon check repository

EiC TASKS

# Invite an editor to edit a submission (sending them an email)
@whedon invite @editor as editor

# Reject a paper
@whedon reject

# Withdraw a paper
@whedon withdraw

# Ask Whedon to actually accept the paper and deposit with Crossref
@whedon accept deposit=true

```

**Comment by vchuravy** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1145/567067.567085 is OK

MISSING DOIs

- 10.1109/cvpr.2016.90 may be a valid DOI for title: Deep Residual Learning for Image Recognition
- 10.1109/inpar.2012.6339601 may be a valid DOI for title: ispc: A SPMD compiler for high-performance CPU programming
- 10.1137/141000671 may be a valid DOI for title: Julia: A fresh approach to numerical computing
- 10.1137/15m1020575 may be a valid DOI for title: JuMP: A modeling language for mathematical optimization
- 10.1109/tpds.2018.2872064 may be a valid DOI for title: Effective Extensible Programming: Unleashing Julia on GPUs
- 10.2172/5254402 may be a valid DOI for title: Compiling fast partial derivatives of functions given by algorithms
- 10.1109/cgo.2004.1281665 may be a valid DOI for title: LLVM: A compilation framework for lifelong program analysis & transformation
- 10.1049/cce:19910064 may be a valid DOI for title: Vector models for data-parallel computing
- 10.1007/978-3-658-10113-8_6 may be a valid DOI for title: Whole-Function Vectorization

INVALID DOIs

- None
```

**Comment by vchuravy** [comment]
@whedon check repository

**Comment by whedon** [comment]
Failed to discover a `Statement of need` section in paper

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.01 s (675.9 files/s, 220087.6 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
TeX                              8            335            178           2656
YAML                             1              0              0             40
Ruby                             1              7              3             37
-------------------------------------------------------------------------------
SUM:                            10            342            181           2733
-------------------------------------------------------------------------------


Statistical information for the repository 'a8be22fa48e68ff6bb434f20' was
gathered on 2021/07/01.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Dhairya Gandhi                   1            47              0          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Dhairya Gandhi               47          100.0          0.0                6.38
```

**Comment by DhairyaLGandhi** [comment]
@whedon check references

**Comment by whedon** [comment]
Checking the BibTeX entries failed with the following error: 

 Failed to parse BibTeX on value "doi" (NAME) [#<BibTeX::Bibliography data=[29]>, "@", #<BibTeX::Entry >, {:title=>["{LLVM}: A compilation framework for lifelong program analysis \\& transformation"], :author=>["Lattner, Chris and Adve, Vikram"], :booktitle=>["Proceedings of the international symposium on Code generation and optimization: feedback-directed and runtime optimization"], :pages=>["75"], :year=>["2004"], :organization=>["IEEE Computer Society"]}]

**Comment by vchuravy** [comment]
@whedon check references

**Comment by whedon** [comment]
Checking the BibTeX entries failed with the following error: 

 Failed to parse BibTeX on value "doi" (NAME) [#<BibTeX::Bibliography data=[29]>, "@", #<BibTeX::Entry >, {:title=>["{LLVM}: A compilation framework for lifelong program analysis \\& transformation"], :author=>["Lattner, Chris and Adve, Vikram"], :booktitle=>["Proceedings of the international symposium on Code generation and optimization: feedback-directed and runtime optimization"], :pages=>["75"], :year=>["2004"], :organization=>["IEEE Computer Society"]}]

**Comment by carstenbauer** [comment]
Since there haven't been any updates here for almost a year (and this submission is actually from ~2019), I'm assuming that the authors don't want to move forward with this. For these reasons, I'm closing this issue.

**Comment by lucaferranti** [comment]
@editorialbot reject
