### ISSUE TITLE
[REVIEW]: SemanticModels.jl: A Julia Package for Scientific Model Augmentation

### ISSUE THREAD

**Issue by whedon** [JuliaCon/proceedings-review#57]
**Submitting author:** @mehalter (<a href="http://orcid.org/0000-0002-0484-971X">Micah Halter</a>)
**Repository:** <a href="https://github.com/mehalter/juliacon2019-submission" target ="_blank">https://github.com/mehalter/juliacon2019-submission</a>
**Editor:** @vchuravy
**Reviewer:** @MasonProtter, @ChrisRackauckas
**Archive:** <a href="https://doi.org/10.5281/zenodo.3961696" target="_blank">10.5281/zenodo.3961696</a>

## Status

[![status](https://proceedings.juliacon.org/papers/33aac8bcc9f413f18cc1cb3894ad7b57/status.svg)](https://proceedings.juliacon.org/papers/33aac8bcc9f413f18cc1cb3894ad7b57)

Status badge code:

```
HTML: <a href="https://submissions.juliacon.org/papers/33aac8bcc9f413f18cc1cb3894ad7b57"><img src="https://submissions.juliacon.org/papers/33aac8bcc9f413f18cc1cb3894ad7b57/status.svg"></a>
Markdown: [![status](https://submissions.juliacon.org/papers/33aac8bcc9f413f18cc1cb3894ad7b57/status.svg)](https://submissions.juliacon.org/papers/33aac8bcc9f413f18cc1cb3894ad7b57)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/mehalter/juliacon2019-submission" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@MasonProtter & @ChrisRackauckas, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/JuliaCon/proceedings-reviews/invitations

The reviewer guidelines are available here: https://proceedings.juliacon.org/guide/reviewers. Any questions/concerns please let @vchuravy know.

✨ **Please try and complete your review in the next two weeks** ✨

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JuliaCon conflict of interest policy](https://proceedings.juliacon.org/guide/authors#coi) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JuliaCon code of conduct](https://proceedings.juliacon.org/coc).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/mehalter/juliacon2019-submission">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Authorship:** Has the submitting author (@mehalter) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [ ] **Functionality:** Have the functional claims of the software been confirmed?
- [ ] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Paper format

- [x] **Authors:** Does the `paper.tex` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [ ] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?
- [ ] **Page limit:** Is the page limit for extended abstracts respected by the submitted document?

### Content

- [x] **Context:** is the scientific context motivating the work correctly presented?
- [x] **Methodology:** is the approach taken in the work justified, presented with enough details and reference to reproduce it?
- [ ] **Results:** are the results presented and compared to approaches with similar goals?

### Conflict of interest

- [ ] As the reviewer I confirm that I have read the [JuliaCon conflict of interest policy](https://proceedings.juliacon.org/guide/authors#coi) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [ ] I confirm that I read and will adhere to the [JuliaCon code of conduct](https://proceedings.juliacon.org/coc).

### General checks

- [ ] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/mehalter/juliacon2019-submission">repository url</a>?
- [ ] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [ ] **Authorship:** Has the submitting author (@mehalter) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [ ] **Installation:** Does installation proceed as outlined in the documentation?
- [ ] **Functionality:** Have the functional claims of the software been confirmed?
- [ ] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [ ] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [ ] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [ ] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [ ] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [ ] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [ ] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Paper format

- [ ] **Authors:** Does the `paper.tex` file include a list of authors with their affiliations?
- [ ] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [ ] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?
- [ ] **Page limit:** Is the page limit for extended abstracts respected by the submitted document?

### Content

- [ ] **Context:** is the scientific context motivating the work correctly presented?
- [ ] **Methodology:** is the approach taken in the work justified, presented with enough details and reference to reproduce it?
- [ ] **Results:** are the results presented and compared to approaches with similar goals?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @MasonProtter, @ChrisRackauckas it looks like you're currently assigned to review this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/JuliaCon/proceedings-review) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/JuliaCon/proceedings-review:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/JuliaCon/proceedings-papers/blob/jcon.00057/jcon.00057/10.21105.jcon.00057.pdf)

**Comment by vchuravy** [comment]
@ChrisRackauckas @MasonProtter are you still willing to perform reviews?

**Comment by ChrisRackauckas** [comment]
I recently took a pretty deep dive through the package and its documentation. The documentation is extremely thorough, especially things like https://aske.gtri.gatech.edu/docs/latest/examples/html/malaria.html . I have nothing to add and think this can be accepted as is. It might finally make a category theorist out of me.

**Comment by vchuravy** [comment]
@ChrisRackauckas good to hear that the package is in a good state. Anuthing about the submitted paper?

**Comment by ChrisRackauckas** [comment]
The paper is mostly good. It should really be citing a lot more of the tools that it's using an some of the category theory background. Maybe a full example that's from scratch and not reading from a file? That's about it.

**Comment by vchuravy** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1137/141000671 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by MasonProtter** [comment]
I'm very sorry to say that I forgot about this, my apologies to Valentin and the submission authors. 

@vchuravy It appears all the Juliacon related links are currently broken. What is the page limit for the paper? If it's more than a page, I think it'd be good if the paper was expanded a bit, but also this is fine. People can see the every extensive and well written docs / notebooks if they want to see more.

I will need a bit more time before I can say I feel that I understand the package well enough to sign off on functionality claims, but what I have seen and understand of the package so far is very impressive and interesting. 

The test suite failed for me on 1.5.0-beta1, and I'm currently running it on 1.4.2 to see how that goes.

One area I'm a little unsure about, and I also don't know what the requirements / expectations are on the JuliaCon side, would be "Are there any comparable or similar packages in other programming languages?" So far as I can tell, other than saying that this package takes a different approach from Jump, Stan and ModellingToolkit it's hard for me to know how novel this work is in the wider world of scientific domain modelling.

**Comment by vchuravy** [comment]
Thank you Mason for your comments.

@mehalter thank you for your patience, can you address the reviewer comments? And is there an archival DOI for the associated code that you would like to associate with the publication?
https://joss.readthedocs.io/en/latest/editing.html#after-reviewers-recommend-acceptance

**Comment by mehalter** [comment]
I have just tagged a new release on SemanticModels to address the notes from @MasonProtter about the test suite, this now works again in Julia v1.0-1.4.2. Julia v1.5.0-beta1 does not work, but the error comes from being unable to precompile Cassette with the new version. Given it is an unreleased version of Julia for now, we are alright with it not working quite yet until Cassette updates their package.

In regards to the paper length and adding more content, the paper was submitted as an extended abstract with a 1 page limit. As @ChrisRackauckas mentioned, with the short page limit, we were expecting to build interest in the package with the abstract and have people go check out it's documentation which we have spent a lot of time on to have full fledge examples and thorough usage notes.

Thank you to both @MasonProtter and @ChrisRackauckas for taking time to review the paper and your great feedback. 

@vchuravy We do not have an archival DOI to be associated with the publication.

**Comment by vchuravy** [comment]
> @vchuravy We do not have an archival DOI to be associated with the publication.

Can you create one for SemanticsModels.jl see https://joss.readthedocs.io/en/latest/editing.html#after-reviewers-recommend-acceptance

**Comment by mehalter** [comment]
@whedon set 10.5281/zenodo.3961696 as archive

**Comment by whedon** [comment]
I'm sorry @mehalter, I'm afraid I can't do that. That's something only editors are allowed to do.

**Comment by mehalter** [comment]
ah sorry, also I misunderstood. We do have a DOI for SemanticModels (this is for the new v0.4.0):  10.5281/zenodo.3961696

**Comment by vchuravy** [comment]
@whedon set 10.5281/zenodo.3961696 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.3961696" target="_blank">10.5281/zenodo.3961696</a> is the archive.

**Comment by vchuravy** [comment]
@whedon set 0.4.0 as version

**Comment by whedon** [comment]
OK. 0.4.0 is the version.

**Comment by vchuravy** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.1137/141000671 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:wave: @JuliaCon/jcon-eics, this paper is ready to be accepted and published.

 Check final proof :point_right: https://github.com/JuliaCon/proceedings-papers/pull/21

If the paper PDF and Crossref deposit XML look good in https://github.com/JuliaCon/proceedings-papers/pull/21, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by mehalter** [comment]
The paper PDF looks good. Thanks for your help @vchuravy

**Comment by vchuravy** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JCON!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/JuliaCon/proceedings-papers/pull/22
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/jcon.00057](https://doi.org/10.21105/jcon.00057)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? Notify your editorial technical team...

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://proceedings.juliacon.org/papers/10.21105/jcon.00057/status.svg)](https://doi.org/10.21105/jcon.00057)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/jcon.00057">
  <img src="https://proceedings.juliacon.org/papers/10.21105/jcon.00057/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://proceedings.juliacon.org/papers/10.21105/jcon.00057/status.svg
   :target: https://doi.org/10.21105/jcon.00057
```
This is how it will look in your documentation:

[![DOI](https://proceedings.juliacon.org/papers/10.21105/jcon.00057/status.svg)](https://doi.org/10.21105/jcon.00057)

**We need your help!**

JuliaCon Proceedings is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://forms.gle/yANMe4c9YmuW9MWcA
- Making a small donation to support our running costs here: https://numfocus.salsalabs.org/donate-to-jcon

**Comment by mehalter** [comment]
@vchuravy  I just checked the page and the software repository links to the paper repository, could we get that moved to https://github.com/jpfairbanks/SemanticModels.jl

**Comment by vchuravy** [comment]
@arfon On we had the case that some folks submitted their papers in independent repositories from the actual software: As an example https://proceedings.juliacon.org/papers/10.21105/jcon.00057 points to https://github.com/mehalter/juliacon2019-submission

Is it possible to add an alias?

**Comment by arfon** [comment]
I've updated this submission to point to https://github.com/jpfairbanks/SemanticModels.jl on the JCON website.
