### ISSUE TITLE
[REVIEW]: Circuitscape in Julia: High Performance Connectivity Modelling to Support Conservation Decisions

### ISSUE THREAD

**Issue by whedon** [JuliaCon/proceedings-review#58]
**Submitting author:** @ranjanan (<a href="http://orcid.org/0000-0002-4409-3937">Ranjan Anantharaman</a>)
**Repository:** <a href="https://github.com/Circuitscape/CircuitscapeJuliaPaper" target ="_blank">https://github.com/Circuitscape/CircuitscapeJuliaPaper</a>
**Editor:** @matbesancon
**Reviewer:** @vlandau
**Archive:** <a href="https://doi.org/10.5281/zenodo.3960829" target="_blank">10.5281/zenodo.3960829</a>

## Status

[![status](https://proceedings.juliacon.org/papers/61b6e6921b305755b416f3949d3da1a9/status.svg)](https://proceedings.juliacon.org/papers/61b6e6921b305755b416f3949d3da1a9)

Status badge code:

```
HTML: <a href="https://submissions.juliacon.org/papers/61b6e6921b305755b416f3949d3da1a9"><img src="https://submissions.juliacon.org/papers/61b6e6921b305755b416f3949d3da1a9/status.svg"></a>
Markdown: [![status](https://submissions.juliacon.org/papers/61b6e6921b305755b416f3949d3da1a9/status.svg)](https://submissions.juliacon.org/papers/61b6e6921b305755b416f3949d3da1a9)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/Circuitscape/Circuitscape.jl" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@vlandau, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/JuliaCon/proceedings-reviews/invitations

The reviewer guidelines are available here: https://proceedings.juliacon.org/guide/reviewers. Any questions/concerns please let @matbesancon know.

✨ **Please try and complete your review in the next two weeks** ✨

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JuliaCon conflict of interest policy](https://proceedings.juliacon.org/guide/authors#coi) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JuliaCon code of conduct](https://proceedings.juliacon.org/coc).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/Circuitscape/Circuitscape.jl">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Authorship:** Has the submitting author (@ranjanan) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Paper format

- [x] **Authors:** Does the `paper.tex` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?
- [x] **Page limit:** Is the page limit for full papers respected by the submitted document?

### Content

- [x] **Context:** is the scientific context motivating the work correctly presented?
- [x] **Methodology:** is the approach taken in the work justified, presented with enough details and reference to reproduce it?
- [x] **Results:** are the results presented and compared to approaches with similar goals?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @vlandau it looks like you're currently assigned to review this paper :tada:.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/JuliaCon/proceedings-review) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/JuliaCon/proceedings-review:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/JuliaCon/proceedings-papers/blob/jcon.00058/jcon.00058/10.21105.jcon.00058.pdf)

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.5281/zenodo.1438428 is OK
- 10.5281/zenodo.2584373 is OK

MISSING DOIs

- https://doi.org/10.1038/373299a0 may be missing for title: Connecting landscape patterns to ecosystem and population processes
- https://doi.org/10.1007/s10980-016-0353-2 may be missing for title: Applying fire connectivity and centrality measures to mitigate the cheatgrass-fire cycle in the arid West, USA
- https://doi.org/10.1111/cobi.12938 may be missing for title: Connecting today’s climates to future climate analogs to facilitate movement of species under climate change
- https://doi.org/10.1016/j.landurbplan.2017.01.007 may be missing for title: Habitat suitability is a poor proxy for landscape connectivity during dispersal and mating movements
- https://doi.org/10.1111/j.1365-294x.2010.04657.x may be missing for title: Use of resistance surfaces for landscape genetic studies: considerations for parameterization and analysis
- https://doi.org/10.1007/s10980-012-9737-0 may be missing for title: Estimating landscape resistance to movement: a review
- https://doi.org/10.1007/s10980-012-9737-0 may be missing for title: Estimating landscape resistance to movement: a review
- https://doi.org/10.1890/07-1861.1 may be missing for title: Using circuit theory to model connectivity in ecology, evolution, and conservation
- https://doi.org/10.1109/mcse.2011.37 may be missing for title: The NumPy array: a structure for efficient numerical computation
- https://doi.org/10.1016/s0168-9274(01)00115-5 may be missing for title: BoomerAMG: a parallel algebraic multigrid solver and preconditioner
- https://doi.org/10.1137/141000671 may be missing for title: Julia: A fresh approach to numerical computing
- https://doi.org/10.1007/springerreference_72145 may be missing for title: Cholesky factorization
- https://doi.org/10.1371/journal.pone.0084135 may be missing for title: Applying circuit theory for corridor expansion and management at regional scales: tiling, pinch points, and omnidirectional connectivity
- https://doi.org/10.1007/bf02238511 may be missing for title: Algebraic multigrid by smoothed aggregation for second and fourth order elliptic problems
- https://doi.org/10.1016/b978-0-444-50616-0.50012-9 may be missing for title: A review of algebraic multigrid
- https://doi.org/10.1002/ecs2.1652 may be missing for title: Using nested connectivity models to resolve management conflicts of isolated water networks in the Sonoran Desert
- https://doi.org/10.1002/ecs2.2847 may be missing for title: A range‐wide model of contemporary, omnidirectional connectivity for the threatened Mojave desert tortoise

INVALID DOIs

- None
```

**Comment by matbesancon** [comment]
@vlandau thanks for the review and sorry for the delay, can you verify that the paper meets the criteria from the list above and check them when it applies?

**Comment by matbesancon** [comment]
@ranjanan for archiving purposes can you repost the review PDF here?
Also there seems to be some DOI missing, whedon is sometimes incorrect on these so let us know if it doesn't apply

**Comment by vlandau** [comment]
Hmm, when I click the link to accept the invitation I am getting a 404 error that the page doesn't exist -- I haven't been able to accept an invitation so maybe that's why I'm not seeing how to check the checklist above.

**Comment by matbesancon** [comment]
@whedon help

**Comment by whedon** [comment]
I'm sorry human, I don't understand that. You can see what commands I support by typing:

```
@whedon commands
```

**Comment by matbesancon** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List all of Whedon's capabilities
@whedon commands

# Assign a GitHub user as the sole reviewer of this submission
@whedon assign @username as reviewer

# Add a GitHub user to the reviewers of this submission
@whedon add @username as reviewer

# Re-invite a reviewer (if they can't update checklists)
@whedon re-invite @username as reviewer

# Remove a GitHub user from the reviewers of this submission
@whedon remove @username as reviewer

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

# Change editorial assignment
@whedon assign @username as editor

# Set the software archive DOI at the top of the issue e.g.
@whedon set 10.0000/zenodo.00000 as archive

# Set the software version at the top of the issue e.g.
@whedon set v1.0.1 as version

# Open the review issue
@whedon start review

EDITORIAL TASKS

# Compile the paper
@whedon generate pdf

# Compile the paper from alternative branch
@whedon generate pdf from branch custom-branch-name

# Remind an author or reviewer to return to a review after a
# certain period of time (supported units days and weeks)
@whedon remind @reviewer in 2 weeks

# Ask Whedon to do a  dry run of accepting the paper and depositing with Crossref
@whedon accept

# Ask Whedon to check the references for missing DOIs
@whedon check references

# Ask Whedon to check repository statistics for the submitted software
@whedon check repository

EiC TASKS

# Invite an editor to edit a submission (sending them an email)
@whedon invite @editor as editor

# Reject a paper
@whedon reject

# Withdraw a paper
@whedon withdraw

# Ask Whedon to actually accept the paper and deposit with Crossref
@whedon accept deposit=true

```

**Comment by matbesancon** [comment]
@whedon list reviewers

**Comment by whedon** [comment]
Here's the current list of reviewers: http://bit.ly/2V9GSFq

**Comment by matbesancon** [comment]
@whedon re-invite @vlandau as reviewer

**Comment by whedon** [comment]
The reviewer already has a pending invite.

@vlandau please accept the invite by clicking this link: https://github.com/JuliaCon/proceedings-review/invitations

**Comment by ranjanan** [comment]
Almost all the DOIs that whedon complained are missing exist, except for the cholesky factorization citation (https://onlinelibrary.wiley.com/doi/full/10.1002/wics.18) which has a different DOI than the one whedon detected. I'll update the paper with the DOI and generate it here.

**Comment by matbesancon** [comment]
>  I'm not sure what the page limit is, so it is unchecked for now.

if I remember correctly it's 8 pages, so this paper is fine

You can verify that references are adequate, disregarding the technical DOI issue, that is, is the paper referencing appropriate references to point the reader where needed

**Comment by vlandau** [comment]
Okay -- all looks good on my end!

**Comment by ranjanan** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/JuliaCon/proceedings-papers/blob/jcon.00058/jcon.00058/10.21105.jcon.00058.pdf)

**Comment by ranjanan** [comment]
Updated the fautly DOI and generated the paper, like you asked.

**Comment by matbesancon** [comment]
fine grained -> fine-grained

Over the past decade Circuitscape -> Over the past decade, Circuitscape

Then, in collaboration with Tanmay Mohapatra, it was translated to Python for flexible scripting, platform independence, and released under an open-source license.

in the C programmming language --> 2 Ms

is high performance -> high-performance

our user base, and works well on every platform (comma)

Julia is an open source programming language --> open-source (multiple occurrences)

are often problem specific -> problem-specific

the choleksy factorization -> Choleksy (multiple occurrences)

backsubstitution -> back-substitution

process independently \cite{pelletier2014applying} , and (no space before and)

produce fine scale and localized -> fine-scale

switch to 64-bit integer ->integers

feedback loop with policy makers and result -> policymakers, and

Its high level mathematical -> high-level

presents upto -> up to

is open source and is available -> is open-source

**Comment by ranjanan** [comment]
@matbesancon I made the changes, but I changed the URL from the original package repo to https://github.com/Circuitscape/CircuitscapeJuliaPaper.

**Comment by matbesancon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/JuliaCon/proceedings-papers/blob/jcon.00058/jcon.00058/10.21105.jcon.00058.pdf)

**Comment by matbesancon** [comment]
did it work

**Comment by ranjanan** [comment]
Yes, it worked. I see you edited the original comment. Nice.

**Comment by ranjanan** [comment]
@matbesancon what's next here?

**Comment by matbesancon** [comment]
this looks good on my side

**Comment by matbesancon** [comment]
@whedon check DOI

**Comment by whedon** [comment]
I'm sorry human, I don't understand that. You can see what commands I support by typing:

```
@whedon commands
```

**Comment by matbesancon** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List all of Whedon's capabilities
@whedon commands

# Assign a GitHub user as the sole reviewer of this submission
@whedon assign @username as reviewer

# Add a GitHub user to the reviewers of this submission
@whedon add @username as reviewer

# Re-invite a reviewer (if they can't update checklists)
@whedon re-invite @username as reviewer

# Remove a GitHub user from the reviewers of this submission
@whedon remove @username as reviewer

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

# Change editorial assignment
@whedon assign @username as editor

# Set the software archive DOI at the top of the issue e.g.
@whedon set 10.0000/zenodo.00000 as archive

# Set the software version at the top of the issue e.g.
@whedon set v1.0.1 as version

# Open the review issue
@whedon start review

EDITORIAL TASKS

# Compile the paper
@whedon generate pdf

# Compile the paper from alternative branch
@whedon generate pdf from branch custom-branch-name

# Remind an author or reviewer to return to a review after a
# certain period of time (supported units days and weeks)
@whedon remind @reviewer in 2 weeks

# Ask Whedon to do a  dry run of accepting the paper and depositing with Crossref
@whedon accept

# Ask Whedon to check the references for missing DOIs
@whedon check references

# Ask Whedon to check repository statistics for the submitted software
@whedon check repository

EiC TASKS

# Invite an editor to edit a submission (sending them an email)
@whedon invite @editor as editor

# Reject a paper
@whedon reject

# Withdraw a paper
@whedon withdraw

# Ask Whedon to actually accept the paper and deposit with Crossref
@whedon accept deposit=true

```

**Comment by matbesancon** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.5281/zenodo.1438428 is OK
- 10.5281/zenodo.2584373 is OK

MISSING DOIs

- https://doi.org/10.1038/373299a0 may be missing for title: Connecting landscape patterns to ecosystem and population processes
- https://doi.org/10.1007/s10980-016-0353-2 may be missing for title: Applying fire connectivity and centrality measures to mitigate the cheatgrass-fire cycle in the arid West, USA
- https://doi.org/10.1111/cobi.12938 may be missing for title: Connecting today’s climates to future climate analogs to facilitate movement of species under climate change
- https://doi.org/10.1016/j.landurbplan.2017.01.007 may be missing for title: Habitat suitability is a poor proxy for landscape connectivity during dispersal and mating movements
- https://doi.org/10.1111/j.1365-294x.2010.04657.x may be missing for title: Use of resistance surfaces for landscape genetic studies: considerations for parameterization and analysis
- https://doi.org/10.1007/s10980-012-9737-0 may be missing for title: Estimating landscape resistance to movement: a review
- https://doi.org/10.1007/s10980-012-9737-0 may be missing for title: Estimating landscape resistance to movement: a review
- https://doi.org/10.1890/07-1861.1 may be missing for title: Using circuit theory to model connectivity in ecology, evolution, and conservation
- https://doi.org/10.1109/mcse.2011.37 may be missing for title: The NumPy array: a structure for efficient numerical computation
- https://doi.org/10.1016/s0168-9274(01)00115-5 may be missing for title: BoomerAMG: a parallel algebraic multigrid solver and preconditioner
- https://doi.org/10.1137/141000671 may be missing for title: Julia: A fresh approach to numerical computing
- https://doi.org/10.1007/springerreference_72145 may be missing for title: Cholesky factorization
- https://doi.org/10.1371/journal.pone.0084135 may be missing for title: Applying circuit theory for corridor expansion and management at regional scales: tiling, pinch points, and omnidirectional connectivity
- https://doi.org/10.1007/bf02238511 may be missing for title: Algebraic multigrid by smoothed aggregation for second and fourth order elliptic problems
- https://doi.org/10.1016/b978-0-444-50616-0.50012-9 may be missing for title: A review of algebraic multigrid
- https://doi.org/10.1002/ecs2.1652 may be missing for title: Using nested connectivity models to resolve management conflicts of isolated water networks in the Sonoran Desert
- https://doi.org/10.1002/ecs2.2847 may be missing for title: A range‐wide model of contemporary, omnidirectional connectivity for the threatened Mojave desert tortoise

INVALID DOIs

- None
```

**Comment by matbesancon** [comment]
@ranjanan can you check the DOIs above? Whedon is buggy so some of them might be wrong

**Comment by arfon** [comment]
@whedon accept

**Comment by whedon** [comment]
No archive DOI set. Exiting...

**Comment by matbesancon** [comment]
hey @ranjanan, can you archive your repo on Zenodo and give me the provided DOI here when done?

**Comment by ranjanan** [comment]
@matbesancon how do I do that? Can't find Circuitscape.jl on Zenodo...

**Comment by ranjanan** [comment]
Don't think I ever put it there, now that I think about it

**Comment by matbesancon** [comment]
if you go on Zenodo, you can link your github, and then register your project, this will allow you to register an archive

**Comment by ranjanan** [comment]
Yes, here's the release DOI: 10.5281/zenodo.3960829. Should I create a DOI for the paper as well, or will this do?

**Comment by matbesancon** [comment]
@whedon set10.5281/zenodo.3960829 as archive

**Comment by whedon** [comment]
I'm sorry human, I don't understand that. You can see what commands I support by typing:

```
@whedon commands
```

**Comment by matbesancon** [comment]
@whedon set 10.5281/zenodo.3960829 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.3960829" target="_blank">10.5281/zenodo.3960829</a> is the archive.

**Comment by matbesancon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/JuliaCon/proceedings-papers/blob/jcon.00058/jcon.00058/10.21105.jcon.00058.pdf)

**Comment by matbesancon** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
:wave: @JuliaCon/jcon-eics, this paper is ready to be accepted and published.

 Check final proof :point_right: https://github.com/JuliaCon/proceedings-papers/pull/16

If the paper PDF and Crossref deposit XML look good in https://github.com/JuliaCon/proceedings-papers/pull/16, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.5281/zenodo.1438428 is OK
- 10.5281/zenodo.2584373 is OK

MISSING DOIs

- https://doi.org/10.1038/373299a0 may be missing for title: Connecting landscape patterns to ecosystem and population processes
- https://doi.org/10.1007/s10980-016-0353-2 may be missing for title: Applying fire connectivity and centrality measures to mitigate the cheatgrass-fire cycle in the arid West, USA
- https://doi.org/10.1111/cobi.12938 may be missing for title: Connecting today’s climates to future climate analogs to facilitate movement of species under climate change
- https://doi.org/10.1016/j.landurbplan.2017.01.007 may be missing for title: Habitat suitability is a poor proxy for landscape connectivity during dispersal and mating movements
- https://doi.org/10.1111/j.1365-294x.2010.04657.x may be missing for title: Use of resistance surfaces for landscape genetic studies: considerations for parameterization and analysis
- https://doi.org/10.1007/s10980-012-9737-0 may be missing for title: Estimating landscape resistance to movement: a review
- https://doi.org/10.1007/s10980-012-9737-0 may be missing for title: Estimating landscape resistance to movement: a review
- https://doi.org/10.1890/07-1861.1 may be missing for title: Using circuit theory to model connectivity in ecology, evolution, and conservation
- https://doi.org/10.1109/mcse.2011.37 may be missing for title: The NumPy array: a structure for efficient numerical computation
- https://doi.org/10.1016/s0168-9274(01)00115-5 may be missing for title: BoomerAMG: a parallel algebraic multigrid solver and preconditioner
- https://doi.org/10.1137/141000671 may be missing for title: Julia: A fresh approach to numerical computing
- https://doi.org/10.1007/springerreference_72145 may be missing for title: Cholesky factorization
- https://doi.org/10.1371/journal.pone.0084135 may be missing for title: Applying circuit theory for corridor expansion and management at regional scales: tiling, pinch points, and omnidirectional connectivity
- https://doi.org/10.1007/bf02238511 may be missing for title: Algebraic multigrid by smoothed aggregation for second and fourth order elliptic problems
- https://doi.org/10.1016/b978-0-444-50616-0.50012-9 may be missing for title: A review of algebraic multigrid
- https://doi.org/10.1002/ecs2.1652 may be missing for title: Using nested connectivity models to resolve management conflicts of isolated water networks in the Sonoran Desert
- https://doi.org/10.1002/ecs2.2847 may be missing for title: A range‐wide model of contemporary, omnidirectional connectivity for the threatened Mojave desert tortoise

INVALID DOIs

- None
```

**Comment by matbesancon** [comment]
@ranjanan can you check the DOIs?

**Comment by ranjanan** [comment]
All DOIs that whedon is complaining about are valid, except for the "cholesky factorization" one. But I updated the DOI for that reference here: https://github.com/Circuitscape/CircuitscapeJuliaPaper/blob/master/paper/paper.bib#L221. Doesn't look like whedon looks at that field?

**Comment by matbesancon** [comment]
weird

**Comment by matbesancon** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
:wave: @JuliaCon/jcon-eics, this paper is ready to be accepted and published.

 Check final proof :point_right: https://github.com/JuliaCon/proceedings-papers/pull/17

If the paper PDF and Crossref deposit XML look good in https://github.com/JuliaCon/proceedings-papers/pull/17, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.5281/zenodo.1438428 is OK
- 10.5281/zenodo.2584373 is OK

MISSING DOIs

- https://doi.org/10.1038/373299a0 may be missing for title: Connecting landscape patterns to ecosystem and population processes
- https://doi.org/10.1007/s10980-016-0353-2 may be missing for title: Applying fire connectivity and centrality measures to mitigate the cheatgrass-fire cycle in the arid West, USA
- https://doi.org/10.1111/cobi.12938 may be missing for title: Connecting today’s climates to future climate analogs to facilitate movement of species under climate change
- https://doi.org/10.1016/j.landurbplan.2017.01.007 may be missing for title: Habitat suitability is a poor proxy for landscape connectivity during dispersal and mating movements
- https://doi.org/10.1111/j.1365-294x.2010.04657.x may be missing for title: Use of resistance surfaces for landscape genetic studies: considerations for parameterization and analysis
- https://doi.org/10.1007/s10980-012-9737-0 may be missing for title: Estimating landscape resistance to movement: a review
- https://doi.org/10.1007/s10980-012-9737-0 may be missing for title: Estimating landscape resistance to movement: a review
- https://doi.org/10.1890/07-1861.1 may be missing for title: Using circuit theory to model connectivity in ecology, evolution, and conservation
- https://doi.org/10.1109/mcse.2011.37 may be missing for title: The NumPy array: a structure for efficient numerical computation
- https://doi.org/10.1016/s0168-9274(01)00115-5 may be missing for title: BoomerAMG: a parallel algebraic multigrid solver and preconditioner
- https://doi.org/10.1137/141000671 may be missing for title: Julia: A fresh approach to numerical computing
- https://doi.org/10.1007/springerreference_72145 may be missing for title: Cholesky factorization
- https://doi.org/10.1371/journal.pone.0084135 may be missing for title: Applying circuit theory for corridor expansion and management at regional scales: tiling, pinch points, and omnidirectional connectivity
- https://doi.org/10.1007/bf02238511 may be missing for title: Algebraic multigrid by smoothed aggregation for second and fourth order elliptic problems
- https://doi.org/10.1016/b978-0-444-50616-0.50012-9 may be missing for title: A review of algebraic multigrid
- https://doi.org/10.1002/ecs2.1652 may be missing for title: Using nested connectivity models to resolve management conflicts of isolated water networks in the Sonoran Desert
- https://doi.org/10.1002/ecs2.2847 may be missing for title: A range‐wide model of contemporary, omnidirectional connectivity for the threatened Mojave desert tortoise

INVALID DOIs

- None
```

**Comment by matbesancon** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JCON!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/JuliaCon/proceedings-papers/pull/18
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/jcon.00058](https://doi.org/10.21105/jcon.00058)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? Notify your editorial technical team...

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://proceedings.juliacon.org/papers/10.21105/jcon.00058/status.svg)](https://doi.org/10.21105/jcon.00058)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/jcon.00058">
  <img src="https://proceedings.juliacon.org/papers/10.21105/jcon.00058/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://proceedings.juliacon.org/papers/10.21105/jcon.00058/status.svg
   :target: https://doi.org/10.21105/jcon.00058
```
This is how it will look in your documentation:

[![DOI](https://proceedings.juliacon.org/papers/10.21105/jcon.00058/status.svg)](https://doi.org/10.21105/jcon.00058)

**We need your help!**

JuliaCon Proceedings is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://forms.gle/yANMe4c9YmuW9MWcA
- Making a small donation to support our running costs here: https://numfocus.salsalabs.org/donate-to-jcon
