### ISSUE TITLE
[PRE REVIEW]: DFTK: A Julian approach for simulating electrons in solids

### ISSUE THREAD

**Issue by whedon** [JuliaCon/proceedings-review#61]
**Submitting author:** @mfherbst (<a href="http://orcid.org/0000-0003-0378-7921">Michael F. Herbst</a>)
**Repository:** <a href="https://github.com/mfherbst/juliacon2020-proceedings-dftk.git" target ="_blank">https://github.com/mfherbst/juliacon2020-proceedings-dftk.git</a>
**Version:** 
**Editor:** @crstnbr
**Reviewers:** @MasonProtter, @jagot
**Managing EiC:** Valentin Churavy

**Author instructions**

Thanks for submitting your paper to JCON @mfherbst. **Currently, there isn't an JCON editor assigned** to your paper.

The author's suggestion for the handling editor is @vchuravy.

@mfherbst if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/jcon-reviewers) have already agreed to review for JCON and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JCON submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Failed to discover a `Statement of need` section in paper

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- None

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.02 s (95.8 files/s, 4597.1 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Markdown                         2              5              0             91
-------------------------------------------------------------------------------
SUM:                             2              5              0             91
-------------------------------------------------------------------------------


Statistical information for the repository 'e2ce2a5ae6db487c57efbb47' was
gathered on 2020/10/15.
No commited files with the specified extensions were found.
```

**Comment by whedon** [comment]
Failed to discover a valid open source license.

**Comment by whedon** [comment]
PDF failed to compile for issue #61 with the following error: 

 pandoc: /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-d14a699185fb/resources/jcon/latex.template: openBinaryFile: does not exist (No such file or directory)
Looks like we failed to compile the PDF

**Comment by mfherbst** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List Whedon's capabilities
@whedon commands

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

EDITORIAL TASKS

# Compile the paper
@whedon generate pdf

# Compile the paper from alternative branch
@whedon generate pdf from branch custom-branch-name

# Ask Whedon to check the references for missing DOIs
@whedon check references

# Ask Whedon to check repository statistics for the submitted software
@whedon check repository

```

**Comment by mfherbst** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
PDF failed to compile for issue #61 with the following error: 

 pandoc: /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-d14a699185fb/resources/jcon/latex.template: openBinaryFile: does not exist (No such file or directory)
Looks like we failed to compile the PDF

**Comment by mfherbst** [comment]
Hmm I'm a bit surprised this fails, since it worked fine when I tested it at https://whedon.theoj.org/. Aim I missing something?

**Comment by vchuravy** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
PDF failed to compile for issue #61 with the following error: 

 pandoc: /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/resources/jcon/latex.template: openBinaryFile: does not exist (No such file or directory)
Looks like we failed to compile the PDF

**Comment by vchuravy** [comment]
@whedon assign @crstnbr   as editor

**Comment by crstnbr** [comment]
@whedon assign @crstnbr as editor

**Comment by whedon** [comment]
I'm sorry @crstnbr, I'm afraid I can't do that. That's something only editors are allowed to do.

**Comment by vchuravy** [comment]
@whedon assign @crstnbr as editor

**Comment by whedon** [comment]
OK, the editor is @crstnbr

**Comment by crstnbr** [comment]
Hi @mfherbst, you're confusion about why this isn't working is understandable. Our website apparently contains outdated information which I only now am in the process of fixing.

Anyways, the issue is that in contrast to JOSS we are accepting LaTeX only submissions. So instead of a paper.md etc. you should have a `paper.tex` file. More specifically, check out our new [author's guide](https://juliacon.github.io/proceedings-guide/author/). It points you to a template repository that shows you exactly how your repository/`paper/` subfolder should look like. It should be rather straightforward to port your paper repo to this format.

Sorry for the inconvenience!

BTW: If you think there is something unclear in/to be added to the author's guide, I'd very much appreciate some feedback!

**Comment by mfherbst** [comment]
@crstnbr Thanks for letting me know. I was not aware of this at all, sorry about that. I changed the repo structure as shown in the docs. Hopefully it works now.

**Comment by mfherbst** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
PDF failed to compile for issue #61 with the following error: 

 rm: cannot remove '*.aux': No such file or directory
Latexmk: This is Latexmk, John Collins, 17 Jan. 2018, version: 4.55.
Rule 'pdflatex': Rules & subrules not known to be previously run:
   pdflatex
Rule 'pdflatex': The following rules & subrules became out-of-date:
      'pdflatex'
------------
Run number 1 of rule 'pdflatex'
------------
------------
Running 'pdflatex  -recorder  "paper.tex"'
------------
===========Latexmk: Missing input file: 'dftk.pdf' from line
  'LaTeX Warning: File `dftk.pdf' not found on input line 82.'
Latexmk: Missing input file: 'dftk.pdf' from line
  'LaTeX Warning: File `dftk.pdf' not found on input line 82.'
Latexmk: List of undefined refs and citations:
  Citation `garrigue2021building' on page 1 undefined on input line 66
  Citation `scfanalysis' on page 1 undefined on input line 66
  Citation `scferror' on page 1 undefined on input line 66
  Citation `scferror' on page 1 undefined on input line 69
  Citation `scfprecondition' on page 1 undefined on input line 66
  Citation `scfprecondition' on page 1 undefined on input line 72
  Reference `fig:logodftk' on page 1 undefined on input line 22
Latexmk: Summary of warnings:
  Latex failed to resolve 1 reference(s)
  Latex failed to resolve 8 citation(s)
Rule 'pdflatex': File changes, etc:
   Changed files, or newly in use since previous run(s):
      'paper.aux'
------------
Run number 2 of rule 'pdflatex'
------------
------------
Running 'pdflatex  -recorder  "paper.tex"'
------------
===========Latexmk: Missing input file: 'dftk.pdf' from line
  'LaTeX Warning: File `dftk.pdf' not found on input line 82.'
Latexmk: Missing input file: 'dftk.pdf' from line
  'LaTeX Warning: File `dftk.pdf' not found on input line 82.'
Latexmk: List of undefined refs and citations:
  Citation `garrigue2021building' on page 1 undefined on input line 66
  Citation `scfanalysis' on page 1 undefined on input line 66
  Citation `scferror' on page 1 undefined on input line 66
  Citation `scferror' on page 1 undefined on input line 69
  Citation `scfprecondition' on page 1 undefined on input line 66
  Citation `scfprecondition' on page 1 undefined on input line 72
  Reference `fig:logodftk' on page 1 undefined on input line 22
Latexmk: Summary of warnings:
  Latex failed to resolve 1 reference(s)
  Latex failed to resolve 8 citation(s)
Rule 'pdflatex': File changes, etc:
   Changed files, or newly in use since previous run(s):
      'paper.out'
------------
Run number 3 of rule 'pdflatex'
------------
------------
Running 'pdflatex  -recorder  "paper.tex"'
------------
===========Latexmk: Missing input file: 'dftk.pdf' from line
  'LaTeX Warning: File `dftk.pdf' not found on input line 82.'
Latexmk: Missing input file: 'dftk.pdf' from line
  'LaTeX Warning: File `dftk.pdf' not found on input line 82.'
Latexmk: List of undefined refs and citations:
  Citation `garrigue2021building' on page 1 undefined on input line 66
  Citation `scfanalysis' on page 1 undefined on input line 66
  Citation `scferror' on page 1 undefined on input line 66
  Citation `scferror' on page 1 undefined on input line 69
  Citation `scfprecondition' on page 1 undefined on input line 66
  Citation `scfprecondition' on page 1 undefined on input line 72
  Reference `fig:logodftk' on page 1 undefined on input line 22
Latexmk: Summary of warnings:
  Latex failed to resolve 1 reference(s)
  Latex failed to resolve 8 citation(s)
Failure to make 'paper.pdf'
Collected error summary (may duplicate other messages):
  pdflatex: Command for 'pdflatex' gave return code 1
      Refer to 'paper.log' for details
Looks like we failed to compile the PDF

**Comment by mfherbst** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/JuliaCon/proceedings-papers/jcon.00061/jcon.00061/10.21105.jcon.00061.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/JuliaCon/proceedings-papers/blob/jcon.00061/jcon.00061/10.21105.jcon.00061.pdf) :page_facing_up: :point_left:

**Comment by mfherbst** [comment]
Hooray :smile:. Let me know if/when there is something else to be done on my end @crstnbr.

**Comment by crstnbr** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1039/d0fd00048e is OK
- 10.1088/1361-648x/abcbdb is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by crstnbr** [comment]
@mfherbst Great to see that compilation worked this time!

Typically our standard for the "extended abstract" papers is one page **excluding** references. Do you think it is possible to slightly extend the current paper in a meaningful way to meet this criterium?

Also it would be great if you could suggest potential referees. Physics + Julia background would be ideal but is no strict requirement.

**Comment by mfherbst** [comment]
@crstnbr Sure I can extend the paper a little to meet that criterion, but I can't guarantee I get to it within the next two weeks as my schedule is pretty heavy.

Regarding referees in the intersection of quantum physics and Julia, how about: davpoolechem, haampie, jagot, jgreener64, PhilipVinc.

**Comment by crstnbr** [comment]
> Sure I can extend the paper a little to meet that criterion, but I can't guarantee I get to it within the next two weeks as my schedule is pretty heavy.

That's perfectly fine, just let whedon recompile the article proof once you've made the changes.

**Comment by crstnbr** [comment]
@whedon add @MasonProtter as reviewer

**Comment by whedon** [comment]
OK, @MasonProtter is now a reviewer

**Comment by mfherbst** [comment]
@crstnbr @MasonProtter Ready for review on our end!

**Comment by mfherbst** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/JuliaCon/proceedings-papers/jcon.00061/jcon.00061/10.21105.jcon.00061.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/JuliaCon/proceedings-papers/blob/jcon.00061/jcon.00061/10.21105.jcon.00061.pdf) :page_facing_up: :point_left:

**Comment by mfherbst** [comment]
Ups one second too quick ... git push was not done.

**Comment by mfherbst** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
PDF failed to compile for issue #61 with the following error: 

 rm: cannot remove '*.aux': No such file or directory
Latexmk: This is Latexmk, John Collins, 17 Jan. 2018, version: 4.55.
Rule 'pdflatex': Rules & subrules not known to be previously run:
   pdflatex
Rule 'pdflatex': The following rules & subrules became out-of-date:
      'pdflatex'
------------
Run number 1 of rule 'pdflatex'
------------
------------
Running 'pdflatex  -recorder  "paper.tex"'
------------
===========Latexmk: Missing input file: 'lipsum.sty' from line
  '! LaTeX Error: File `lipsum.sty' not found.'
Latexmk: Missing input file: 'lipsum.sty' from line
  '! LaTeX Error: File `lipsum.sty' not found.'
Failure to make 'paper.pdf'
Collected error summary (may duplicate other messages):
  pdflatex: Command for 'pdflatex' gave return code 1
      Refer to 'paper.log' for details
Looks like we failed to compile the PDF

**Comment by mfherbst** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/JuliaCon/proceedings-papers/jcon.00061/jcon.00061/10.21105.jcon.00061.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/JuliaCon/proceedings-papers/blob/jcon.00061/jcon.00061/10.21105.jcon.00061.pdf) :page_facing_up: :point_left:

**Comment by mfherbst** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/JuliaCon/proceedings-papers/jcon.00061/jcon.00061/10.21105.jcon.00061.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/JuliaCon/proceedings-papers/blob/jcon.00061/jcon.00061/10.21105.jcon.00061.pdf) :page_facing_up: :point_left:

**Comment by mfherbst** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1039/d0fd00048e is OK
- 10.1088/1361-648x/abcbdb is OK
- 10.1038/natrevmats.2015.4 is OK
- 10.1038/ncomms11962 is OK
- 10.1021/jacs.7b02120 is OK
- 10.1038/nmat1752 is OK
- 10.1063/1.3148892 is OK
- 10.1021/acscentsci.8b00229 is OK
- 10.1063/1.5144261 is OK
- 10.1063/5.0005082 is OK
- 10.1103/PhysRevB.54.1703 is OK
- 10.1103/PhysRevLett.77.3865 is OK
- 10.1088/1361-648x/aa680e is OK
- 10.1016/j.commatsci.2012.10.028 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by mfherbst** [comment]
Interesting ... so whedon sees the new version, because it extracts all the new references, but the PDF it builds is still the version I submitted a few weeks ago. @crstnbr any idea why?

**Comment by mfherbst** [comment]
What now it got updated ... ok anyway: the PDFs linked by whedon now point to the version we want to submit.

**Comment by crstnbr** [comment]
I will move things to review stage once I've added a second reviewer.

**Comment by crstnbr** [comment]
@whedon add @jagot as reviewer

**Comment by whedon** [comment]
OK, @jagot is now a reviewer

**Comment by crstnbr** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/JuliaCon/proceedings-review/issues/69.
