### ISSUE TITLE
[PRE REVIEW]: MPI.jl: Julia bindings for the Message Passing Interface

### ISSUE THREAD

**Issue by whedon** [JuliaCon/proceedings-review#62]
**Submitting author:** @simonbyrne (<a href="http://orcid.org/0000-0001-8048-6810">Simon Byrne</a>)
**Repository:** <a href="https://github.com/JuliaParallel/MPI.jl" target ="_blank">https://github.com/JuliaParallel/MPI.jl</a>
**Version:** 
**Editor:** @crstnbr
**Reviewers:** @dalcinl, @stevengj
**Managing EiC:** Valentin Churavy

**Author instructions**

Thanks for submitting your paper to JCON @simonbyrne. **Currently, there isn't an JCON editor assigned** to your paper.

The author's suggestion for the handling editor is @matbesancon.

@simonbyrne if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/jcon-reviewers) have already agreed to review for JCON and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JCON submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.17 s (576.3 files/s, 49677.6 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Julia                           67           1289            568           5247
Markdown                        15            148              0            466
YAML                            10             47             16            306
Bourne Shell                     2             10             22            128
SVG                              1              0              0             80
TOML                             2              4              0             30
-------------------------------------------------------------------------------
SUM:                            97           1498            606           6257
-------------------------------------------------------------------------------


Statistical information for the repository '8d7661a9a569acfa6afd4567' was
gathered on 2020/10/15.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Bart Janssens                    5            39              2            4.69
Erik Schnetter                   6           163            152           36.04
Filippo Vicentini                1             4              0            0.46
Jake Bolewski                    1            41             41            9.38
Jared Crean                      2             8              0            0.92
Joel Mason                       1             2              0            0.23
Joey Huchette                    1            54             54           12.36
Katie Hyatt                      1             8              0            0.92
Lucas C Wilcox                   1            54              0            6.18
Sam                              1             4              0            0.46
Simon Byrne                      2             0            138           15.79
Steven G. Johnson                2            51             49           11.44
Thomas Bolemann                  3             9              1            1.14

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
```

**Comment by whedon** [comment]
PDF failed to compile for issue #62 with the following error: 

 Can't find any papers to compile :-(

**Comment by simonbyrne** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List Whedon's capabilities
@whedon commands

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

EDITORIAL TASKS

# Compile the paper
@whedon generate pdf

# Compile the paper from alternative branch
@whedon generate pdf from branch custom-branch-name

# Ask Whedon to check the references for missing DOIs
@whedon check references

# Ask Whedon to check repository statistics for the submitted software
@whedon check repository

```

**Comment by simonbyrne** [comment]
@whedon generate pdf from branch paper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch paper. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #62 with the following error: 

 pandoc: /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-d14a699185fb/resources/jcon/latex.template: openBinaryFile: does not exist (No such file or directory)
Looks like we failed to compile the PDF

**Comment by simonbyrne** [comment]
@whedon check references

**Comment by simonbyrne** [comment]
@whedon generate pdf from branch paper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch paper. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #62 with the following error: 

 pandoc: /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-d14a699185fb/resources/jcon/latex.template: openBinaryFile: does not exist (No such file or directory)
Looks like we failed to compile the PDF

**Comment by matbesancon** [comment]
@simonbyrne you will need a "paper" folder at the top-level in the paper branch, where you can add all the paper-related files

**Comment by simonbyrne** [comment]
@whedon generate pdf from branch paper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch paper. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #62 with the following error: 

 pandoc: /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-d14a699185fb/resources/jcon/latex.template: openBinaryFile: does not exist (No such file or directory)
Looks like we failed to compile the PDF

**Comment by simonbyrne** [comment]
@matbesancon I tried that: https://github.com/JuliaParallel/MPI.jl/tree/paper/paper

**Comment by matbesancon** [comment]
You will need at least the YAML file, see https://github.com/JuliaCon/JuliaConSubmission.jl/tree/master/paper
If you want to build locally you will also need the rest of them

**Comment by simonbyrne** [comment]
Ah, I didn't know about these instructions.

**Comment by simonbyrne** [comment]
Does it have to be .tex file, or can it be a .md file like JOSS?

**Comment by matbesancon** [comment]
we only have tex

**Comment by simonbyrne** [comment]
@whedon generate pdf from branch paper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch paper. Reticulating splines etc...
```

**Comment by simonbyrne** [comment]
@whedon ping

**Comment by whedon** [comment]
I'm sorry human, I don't understand that. You can see what commands I support by typing:

```
@whedon commands
```

**Comment by simonbyrne** [comment]
@matbesancon is whedon working?

**Comment by simonbyrne** [comment]
@whedon generate pdf from branch paper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch paper. Reticulating splines etc...
```

**Comment by simonbyrne** [comment]
@whedon generate pdf from branch paper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch paper. Reticulating splines etc...
```

**Comment by simonbyrne** [comment]
@matbesancon @vchuravy any idea why this isn't working?

**Comment by vchuravy** [comment]
@whedon generate pdf from branch paper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch paper. Reticulating splines etc...
```

**Comment by crstnbr** [comment]
@whedon assign @crstnbr as editor

**Comment by whedon** [comment]
OK, the editor is @crstnbr

**Comment by crstnbr** [comment]
@whedon generate pdf from branch paper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch paper. Reticulating splines etc...
```

**Comment by crstnbr** [comment]
@simonbyrne It seems that the issue is that you have a `paper.md` in your `paper/` directory. This conflicts with the `paper.tex` that we use for the Julia proceedings. Can you remove the `paper.md` file and ask whedon to generate the article proof again?

**Comment by simonbyrne** [comment]
@whedon generate pdf from branch paper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch paper. Reticulating splines etc...
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/JuliaCon/proceedings-papers/jcon.00062/jcon.00062/10.21105.jcon.00062.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/JuliaCon/proceedings-papers/blob/jcon.00062/jcon.00062/10.21105.jcon.00062.pdf) :page_facing_up: :point_left:

**Comment by crstnbr** [comment]
Great!

@simonbyrne, can you suggest potential reviewers? No need to ping them directly here, plain GitHub handles suffice. I'll contact them in private.

**Comment by crstnbr** [comment]
@whedon assign @stevengj as reviewer

**Comment by whedon** [comment]
OK, @stevengj is now a reviewer

**Comment by crstnbr** [comment]
@whedon assign @dalcinl as reviewer

**Comment by whedon** [comment]
OK, @dalcinl is now a reviewer

**Comment by crstnbr** [comment]
@simonbyrne Given that you submitted some time ago (sorry for the delay) do you want to make additional changes to the manuscript or the repo? If not, I would let Whedon close this thread and move us to review stage.

**Comment by crstnbr** [comment]
@whedon add @stevengj as reviewer

**Comment by whedon** [comment]
OK, @stevengj is now a reviewer

**Comment by crstnbr** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/JuliaCon/proceedings-review/issues/68.
