### ISSUE TITLE
[PRE REVIEW]: Setfield.jl: Changing the immutable

### ISSUE THREAD

**Issue by whedon** [JuliaCon/proceedings-review#64]
**Submitting author:** @jw3126 (<a href="http://orcid.org/0000-0002-0980-8239">Jan Weidner</a>)
**Repository:** <a href="https://github.com/jw3126/Setfield.jl" target ="_blank">https://github.com/jw3126/Setfield.jl</a>
**Version:** 
**Editor:** @vchuravy
**Reviewer:** Pending
**Managing EiC:** Valentin Churavy

**Author instructions**

Thanks for submitting your paper to JCON @jw3126. **Currently, there isn't an JCON editor assigned** to your paper.

The author's suggestion for the handling editor is @matbesancon.

@jw3126 if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/jcon-reviewers) have already agreed to review for JCON and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JCON submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.06 s (481.2 files/s, 34392.1 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Julia                           16            317             54           1329
Markdown                         5             34              0            122
YAML                             5              9             11             92
TOML                             2              5              0             28
-------------------------------------------------------------------------------
SUM:                            28            365             65           1571
-------------------------------------------------------------------------------


Statistical information for the repository 'e6587d699f31ae3ca24dc490' was
gathered on 2020/10/15.
No commited files with the specified extensions were found.
```

**Comment by whedon** [comment]
PDF failed to compile for issue #64 with the following error: 

 Can't find any papers to compile :-(

**Comment by jw3126** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List Whedon's capabilities
@whedon commands

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

EDITORIAL TASKS

# Compile the paper
@whedon generate pdf

# Compile the paper from alternative branch
@whedon generate pdf from branch custom-branch-name

# Ask Whedon to check the references for missing DOIs
@whedon check references

# Ask Whedon to check repository statistics for the submitted software
@whedon check repository

```

**Comment by jw3126** [comment]
@whedon generate pdf from branch paper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch paper. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #64 with the following error: 

 pandoc: /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-d14a699185fb/resources/jcon/latex.template: openBinaryFile: does not exist (No such file or directory)
Looks like we failed to compile the PDF

**Comment by jw3126** [comment]
@whedon check references

**Comment by jw3126** [comment]
The paper is here: https://github.com/jw3126/Setfield.jl/tree/paper/paper . And I can compile it using https://whedon.theoj.org/ does work. Any ideas?

**Comment by vchuravy** [comment]
@whedon generate pdf from branch paper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch paper. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #64 with the following error: 

 pandoc: /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/resources/jcon/latex.template: openBinaryFile: does not exist (No such file or directory)
Looks like we failed to compile the PDF

**Comment by vchuravy** [comment]
@whedon assign @vchuravy as editor

**Comment by whedon** [comment]
OK, the editor is @vchuravy

**Comment by jw3126** [comment]
Thanks a lot @vchuravy for all your juliacon proceedings work. And especially for looking into this.

**Comment by vchuravy** [comment]
@jw3126 can you take a look at https://juliacon.github.io/proceedings-guide/author/ and https://github.com/JuliaCon/JuliaConSubmission.jl, we currently don't support Markdown submissions can you update the paper branch to be in Latex following the guide/template?

**Comment by jw3126** [comment]
Ah thanks. Yeah I will update

**Comment by vchuravy** [comment]
Let me know once you have done that.

**Comment by vchuravy** [comment]
@whedon remind @jw3126 in one week

**Comment by whedon** [comment]
Sorry, I can't set reminders on PRE-REVIEW issues.

**Comment by jw3126** [comment]
@vchuravy I moved the paper to tex. https://github.com/jw3126/Setfield.jl/tree/paper/paper 
There is one thing that is not yet ideal. Namely, if I cite a Github repo, the URL does not show up in the references sections. What's the best way to change that?

**Comment by vchuravy** [comment]
@whedon help

**Comment by whedon** [comment]
I'm sorry human, I don't understand that. You can see what commands I support by typing:

```
@whedon commands
```

**Comment by vchuravy** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List all of Whedon's capabilities
@whedon commands

# Assign a GitHub user as the sole reviewer of this submission
@whedon assign @username as reviewer

# Add a GitHub user to the reviewers of this submission
@whedon add @username as reviewer

# Re-invite a reviewer (if they can't update checklists)
@whedon re-invite @username as reviewer

# Remove a GitHub user from the reviewers of this submission
@whedon remove @username as reviewer

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

# Change editorial assignment
@whedon assign @username as editor

# Set the software archive DOI at the top of the issue e.g.
@whedon set 10.0000/zenodo.00000 as archive

# Set the software version at the top of the issue e.g.
@whedon set v1.0.1 as version

# Open the review issue
@whedon start review

EDITORIAL TASKS

# All commands can be run on a non-default branch, to do this pass a custom 
# branch name by following the command with `from branch custom-branch-name`.
# For example:

# Compile the paper
@whedon generate pdf

# Compile the paper from alternative branch
@whedon generate pdf from branch custom-branch-name

# Remind an author or reviewer to return to a review after a
# certain period of time (supported units days and weeks)
@whedon remind @reviewer in 2 weeks

# Ask Whedon to do a dry run of accepting the paper and depositing with Crossref
@whedon accept

# Ask Whedon to check the references for missing DOIs
@whedon check references

# Ask Whedon to check repository statistics for the submitted software
@whedon check repository

EiC TASKS

# Invite an editor to edit a submission (sending them an email)
@whedon invite @editor as editor

# Reject a paper
@whedon reject

# Withdraw a paper
@whedon withdraw

# Ask Whedon to actually accept the paper and deposit with Crossref
@whedon accept deposit=true

```

**Comment by vchuravy** [comment]
@whedon generate pdf from branch paper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch paper. Reticulating splines etc...
```

**Comment by vchuravy** [comment]
@whedon check references

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/JuliaCon/proceedings-papers/jcon.00064/jcon.00064/10.21105.jcon.00064.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/JuliaCon/proceedings-papers/blob/jcon.00064/jcon.00064/10.21105.jcon.00064.pdf) :page_facing_up: :point_left:

**Comment by vchuravy** [comment]
> @vchuravy I moved the paper to tex. https://github.com/jw3126/Setfield.jl/tree/paper/paper
> There is one thing that is not yet ideal. Namely, if I cite a Github repo, the URL does not show up in the references sections. What's the best way to change that?

Either a `@misc` with a `howpublished` or `note`.

**Comment by jw3126** [comment]
@vchuravy thanks, I fixed it.

**Comment by vchuravy** [comment]
@whedon generate pdf from branch paper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch paper. Reticulating splines etc...
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/JuliaCon/proceedings-papers/jcon.00064/jcon.00064/10.21105.jcon.00064.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/JuliaCon/proceedings-papers/blob/jcon.00064/jcon.00064/10.21105.jcon.00064.pdf) :page_facing_up: :point_left:

**Comment by luraess** [comment]
Dear author @jw3126, we are in the process of resuming the stalled JuliaCon reviews. If you are still interested in getting your work published, please start addressing the author-action-required items within the coming 3 weeks. If no action is taken within the coming 3 weeks, we will close the submission. Thank you for your understanding.

**Comment by lucaferranti** [comment]
@editorialbot reject
