### ISSUE TITLE
[PRE REVIEW]: ExaPF.jl: A Power Flow Solver for GPUs

### ISSUE THREAD

**Issue by whedon** [JuliaCon/proceedings-review#65]
**Submitting author:** @michel2323 (<a href="http://orcid.org/0000-0002-4164-027X">Michel Schanen</a>)
**Repository:** <a href="https://github.com/exanauts/JuliaCon2020" target ="_blank">https://github.com/exanauts/JuliaCon2020</a>
**Version:** 
**Editor:** @vchuravy
**Reviewers:** @mjamei19
**Managing EiC:** Valentin Churavy

**Author instructions**

Thanks for submitting your paper to JCON @michel2323. **Currently, there isn't an JCON editor assigned** to your paper.

The author's suggestion for the handling editor is @vchuravy.

@michel2323 if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/jcon-reviewers) have already agreed to review for JCON and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JCON submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
PDF failed to compile for issue #65 with the following error: 

 /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `block in find': No such file or directory - 32f0c4319339ddc7325f874b (Errno::ENOENT)
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `collect!'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `find'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-d14a699185fb/lib/whedon/processor.rb:66:in `find_paper_paths'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-d14a699185fb/bin/whedon:53:in `prepare'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-d14a699185fb/bin/whedon:131:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by vchuravy** [comment]
@whedon assign @vchuravy  as editor

**Comment by whedon** [comment]
OK, the editor is @vchuravy

**Comment by vchuravy** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
PDF failed to compile for issue #65 with the following error: 

 Can't find any papers to compile :-(

**Comment by vchuravy** [comment]
@michel2323 are you still interested in submitting?

**Comment by vchuravy** [comment]
@michel2323 It's complaining that https://github.com/exanauts/JuliaCon2020 is no longer available.

Can you take a look at https://juliacon.github.io/proceedings-guide/author/ and https://github.com/JuliaCon/JuliaConSubmission.jl
You probably need to re-submit so that we get Whedon happy.

We recommend that you have a paper branch/folder in ExaPF.jl instead of having a separate repository.

**Comment by michel2323** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
PDF failed to compile for issue #65 with the following error: 

 pandoc: /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/resources/jcon/latex.template: openBinaryFile: does not exist (No such file or directory)
Looks like we failed to compile the PDF

**Comment by michel2323** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List Whedon's capabilities
@whedon commands

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

EDITORIAL TASKS

# Compile the paper
@whedon generate pdf

# Compile the paper from alternative branch
@whedon generate pdf from branch custom-branch-name

# Ask Whedon to check the references for missing DOIs
@whedon check references

# Ask Whedon to check repository statistics for the submitted software
@whedon check repository

```

**Comment by michel2323** [comment]
@vchuravy First, the repository was not public. So it was just sitting there. Sorry about that. Second, it's the first time I read these guidelines. I was following the JOSS submission guidelines. Thus we created a pandoc markdown document.

What I will try to do now is to get a tex from our markdown file, put it in the ExaPF.jl repository as described by the guide and clone that in the repository address linked here to avoid dealing with resubmission and whedon.

**Comment by vchuravy** [comment]
Resubmission should be fairly painless, but whatever works best for you.

>  Second, it's the first time I read these guidelines

Yeah sorry we messed up and accidentally hid the guide for the 2020 conference.

**Comment by michel2323** [comment]
@whedon generate pdf from branch paper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch paper. Reticulating splines etc...
```

**Comment by michel2323** [comment]
@whedon check repository

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.06 s (613.3 files/s, 126543.1 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Julia                           20            505            262           2438
TeX                              8            272            219           2421
Jupyter Notebook                 2              0            845            312
SVG                              1              1              1            274
Markdown                         2             20              0             69
Python                           1             13              3             59
Ruby                             1              8              4             45
YAML                             2              0              1             33
TOML                             1              4              0             32
-------------------------------------------------------------------------------
SUM:                            38            823           1335           5683
-------------------------------------------------------------------------------


Statistical information for the repository '5cf9cd39c5e89b61f3759dd5' was
gathered on 2021/01/29.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Adrian Maldonado                 2            78              3           58.70
Michel Schanen                   1            57              0           41.30

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Adrian Maldonado             75           96.2          0.3                4.00
Michel Schanen               57          100.0          0.0                7.02
```

**Comment by crstnbr** [comment]
@michel2323 You need to drop the `paper.md` file for PDF compilation to work. It clashes with the `paper.tex` file.

**Comment by michel2323** [comment]
@whedon generate pdf from branch paper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch paper. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #65 with the following error: 

 /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon.rb:147:in `check_fields': Paper YAML header is missing expected fields: keywords (RuntimeError)
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon.rb:89:in `initialize'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon/processor.rb:38:in `new'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon/processor.rb:38:in `set_paper'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/bin/whedon:58:in `prepare'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/bin/whedon:131:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `<main>'

**Comment by michel2323** [comment]
@whedon generate pdf from branch paper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch paper. Reticulating splines etc...
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/JuliaCon/proceedings-papers/jcon.00065/jcon.00065/10.21105.jcon.00065.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/JuliaCon/proceedings-papers/blob/jcon.00065/jcon.00065/10.21105.jcon.00065.pdf) :page_facing_up: :point_left:

**Comment by michel2323** [comment]
@crstnbr Thanks for the help. @vchuravy Here we are! Back then we followed the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html) when writing the paper. Not sure that is what you expect. Let us know what you think.

**Comment by vchuravy** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1137/0913035 is OK
- 10.1109/TPDS.2018.2872064 is OK
- 10.1137/130908737 is OK

MISSING DOIs

- 10.1109/tsg.2016.2610863 may be a valid DOI for title: Parallel Dynamics Simulation Using a Krylov-Schwarz Linear Solution Scheme
- 10.1016/j.advengsoft.2019.02.002 may be a valid DOI for title: Rapid software prototyping for heterogeneous and distributed platforms
- 10.1145/3404397.3404470 may be a valid DOI for title: Vector Forward Mode Automatic Differentiation on SIMD/SIMT architectures 
- 10.1007/s10107-004-0559-y may be a valid DOI for title: On the implementation of an interior-point filter line-search algorithm for large-scale nonlinear programming
- 10.1109/tpwrs.2007.901301 may be a valid DOI for title: On Computational Issues of Market-Based Optimal Power Flow

INVALID DOIs

- None
```

**Comment by vchuravy** [comment]
I noticed in the draft on page 2 that two references are not converted in Latex form.

@michel2323 Thanks! You can either decide to keep it this way or extend it to a 6-8 papers :)

**Comment by michel2323** [comment]
@wheadon generate pdf from branch paper

**Comment by michel2323** [comment]
@vchuravy I fixed the references and did a last pass with a few minor beautifications. I added some keywords in `jlcode.sty`. I hope that's okay,

We'd go for short 3 pages and keep it this way.

Wheadon is suspiciously quiet.

**Comment by crstnbr** [comment]
> I added some keywords in `jlcode.sty`. I hope that's okay,

You shouldn't modify the template files. Only `paper.tex`, `ref.bib`, and `paper.yml`.


> @wheadon generate pdf from branch paper

It is "whedon" not "wheadon".

**Comment by michel2323** [comment]
@whedon generate pdf from branch paper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch paper. Reticulating splines etc...
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/JuliaCon/proceedings-papers/jcon.00065/jcon.00065/10.21105.jcon.00065.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/JuliaCon/proceedings-papers/blob/jcon.00065/jcon.00065/10.21105.jcon.00065.pdf) :page_facing_up: :point_left:

**Comment by michel2323** [comment]
@whedon generate pdf from branch paper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch paper. Reticulating splines etc...
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/JuliaCon/proceedings-papers/jcon.00065/jcon.00065/10.21105.jcon.00065.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/JuliaCon/proceedings-papers/blob/jcon.00065/jcon.00065/10.21105.jcon.00065.pdf) :page_facing_up: :point_left:

**Comment by michel2323** [comment]
@whedon generate pdf from branch paper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch paper. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #65 with the following error: 

 /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon.rb:204:in `block in parse_authors': Author (Michel Schanen) is missing affiliation (RuntimeError)
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon.rb:202:in `each'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon.rb:202:in `parse_authors'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon.rb:93:in `initialize'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon/processor.rb:38:in `new'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon/processor.rb:38:in `set_paper'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/bin/whedon:58:in `prepare'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/bin/whedon:131:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `<main>'

**Comment by michel2323** [comment]
@whedon generate pdf from branch paper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch paper. Reticulating splines etc...
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/JuliaCon/proceedings-papers/jcon.00065/jcon.00065/10.21105.jcon.00065.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/JuliaCon/proceedings-papers/blob/jcon.00065/jcon.00065/10.21105.jcon.00065.pdf) :page_facing_up: :point_left:

**Comment by michel2323** [comment]
@vchuravy Done.

**Comment by vchuravy** [comment]
Thanks @michel2323  do you have any suggestions for potential reviewers? We can also discuss that privately on slack.

**Comment by vchuravy** [comment]
@whedon add @lcw as reviewer

**Comment by whedon** [comment]
OK, @lcw is now a reviewer

**Comment by whedon** [comment]
OK, @mjamei19 is now a reviewer

**Comment by vchuravy** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/JuliaCon/proceedings-review/issues/72.
