### ISSUE TITLE
[PRE REVIEW]: Intertwined Economic and Energy Analysis using Julia

### ISSUE THREAD

**Issue by whedon** [JuliaCon/proceedings-review#66]
**Submitting author:** @clhughes (<a href="http://orcid.org/0000-0003-1233-3307">Caroline Hughes</a>)
**Repository:** <a href="https://github.com/NREL/SLiDE" target ="_blank">https://github.com/NREL/SLiDE</a>
**Version:** 
**Editor:** @matbesancon
**Reviewer:** Pending
**Managing EiC:** Valentin Churavy

**Author instructions**

Thanks for submitting your paper to JCON @clhughes. **Currently, there isn't an JCON editor assigned** to your paper.

The author's suggestion for the handling editor is @matbesancon.

@clhughes if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/jcon-reviewers) have already agreed to review for JCON and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JCON submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
PDF failed to compile for issue #66 with the following error: 

 /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `block in find': No such file or directory - 3ed1c49857552798aef2f6cb (Errno::ENOENT)
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `collect!'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `find'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-d14a699185fb/lib/whedon/processor.rb:66:in `find_paper_paths'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-d14a699185fb/bin/whedon:53:in `prepare'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-d14a699185fb/bin/whedon:131:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by matbesancon** [comment]
@whedon help generate

**Comment by whedon** [comment]
I'm sorry human, I don't understand that. You can see what commands I support by typing:

```
@whedon commands
```

**Comment by matbesancon** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List all of Whedon's capabilities
@whedon commands

# Assign a GitHub user as the sole reviewer of this submission
@whedon assign @username as reviewer

# Add a GitHub user to the reviewers of this submission
@whedon add @username as reviewer

# Re-invite a reviewer (if they can't update checklists)
@whedon re-invite @username as reviewer

# Remove a GitHub user from the reviewers of this submission
@whedon remove @username as reviewer

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

# Change editorial assignment
@whedon assign @username as editor

# Set the software archive DOI at the top of the issue e.g.
@whedon set 10.0000/zenodo.00000 as archive

# Set the software version at the top of the issue e.g.
@whedon set v1.0.1 as version

# Open the review issue
@whedon start review

EDITORIAL TASKS

# All commands can be run on a non-default branch, to do this pass a custom 
# branch name by following the command with `from branch custom-branch-name`.
# For example:

# Compile the paper
@whedon generate pdf

# Compile the paper from alternative branch
@whedon generate pdf from branch custom-branch-name

# Remind an author or reviewer to return to a review after a
# certain period of time (supported units days and weeks)
@whedon remind @reviewer in 2 weeks

# Ask Whedon to do a dry run of accepting the paper and depositing with Crossref
@whedon accept

# Ask Whedon to check the references for missing DOIs
@whedon check references

# Ask Whedon to check repository statistics for the submitted software
@whedon check repository

EiC TASKS

# Invite an editor to edit a submission (sending them an email)
@whedon invite @editor as editor

# Reject a paper
@whedon reject

# Withdraw a paper
@whedon withdraw

# Ask Whedon to actually accept the paper and deposit with Crossref
@whedon accept deposit=true

```

**Comment by matbesancon** [comment]
@arfon is there a way to indicate a sub-folder where the paper is located or must it always be "paper"?

**Comment by arfon** [comment]
@matbesancon - the issue here is that the submitted URL can't be cloned by Whedon. 

You can't clone this URL:

`https://github.com/NREL/SLiDE/tree/publications/publications/juliacon2020`

...but you can clone this:

`https://github.com/NREL/SLiDE`

So the issue body at the top of this thread needs editing to have the address `https://github.com/NREL/SLiDE` (which I'll do now).

On JOSS, we've recently started validating the URLs submitted can be cloned _at submission time_ which stops this issue from coming up. I can try and apply that patch to your fork of the codebase too if you like?

**Comment by arfon** [comment]
@whedon generate pdf from branch publications

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch publications. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #66 with the following error: 

 rm: cannot remove '*.aux': No such file or directory
Latexmk: This is Latexmk, John Collins, 17 Jan. 2018, version: 4.55.
Rule 'pdflatex': Rules & subrules not known to be previously run:
   pdflatex
Rule 'pdflatex': The following rules & subrules became out-of-date:
      'pdflatex'
------------
Run number 1 of rule 'pdflatex'
------------
------------
Running 'pdflatex  -recorder  "paper.tex"'
------------
===========Latexmk: Missing input file: 'siunitx.sty' from line
  '! LaTeX Error: File `siunitx.sty' not found.'
Latexmk: Missing input file: 'siunitx.sty' from line
  '! LaTeX Error: File `siunitx.sty' not found.'
Failure to make 'paper.pdf'
Collected error summary (may duplicate other messages):
  pdflatex: Command for 'pdflatex' gave return code 1
      Refer to 'paper.log' for details
Looks like we failed to compile the PDF

**Comment by arfon** [comment]
☝️ looks like Whedon is at least trying to compile this now...

**Comment by matbesancon** [comment]
Thanks @arfon!

> On JOSS, we've recently started validating the URLs submitted can be cloned at submission time which stops this issue from coming up. I can try and apply that patch to your fork of the codebase too if you like?

yes that would be great, I hadn't noticed the URL issue.

**Comment by matbesancon** [comment]
@clhughes it looks like a package is missing. You can download the .sty file and add it to the paper subfolder

**Comment by vchuravy** [comment]
@whedon assign @matbesancon  as editor

**Comment by whedon** [comment]
OK, the editor is @matbesancon

**Comment by matbesancon** [comment]
@whedon generate pdf from branch publications

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch publications. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #66 with the following error: 

 rm: cannot remove '*.aux': No such file or directory
Latexmk: This is Latexmk, John Collins, 17 Jan. 2018, version: 4.55.
Rule 'pdflatex': Rules & subrules not known to be previously run:
   pdflatex
Rule 'pdflatex': The following rules & subrules became out-of-date:
      'pdflatex'
------------
Run number 1 of rule 'pdflatex'
------------
------------
Running 'pdflatex  -recorder  "paper.tex"'
------------
===========Latexmk: Missing input file: 'siunitx.sty' from line
  '! LaTeX Error: File `siunitx.sty' not found.'
Latexmk: Missing input file: 'siunitx.sty' from line
  '! LaTeX Error: File `siunitx.sty' not found.'
Failure to make 'paper.pdf'
Collected error summary (may duplicate other messages):
  pdflatex: Command for 'pdflatex' gave return code 1
      Refer to 'paper.log' for details
Looks like we failed to compile the PDF

**Comment by matbesancon** [comment]
Hi @clhughes, I'm taking over the edition for this proceeding, sorry about the delays we experienced.
Looking at the repo:
https://github.com/NREL/SLiDE/tree/publications/publications/juliacon2020

Could you change the folder of the paper from `/publications/juliacon2020` to `/paper`?

**Comment by matbesancon** [comment]
ping @clhughes

**Comment by matbesancon** [comment]
bump

**Comment by luraess** [comment]
Dear author @clhughes, @arfon, we are in the process of resuming the stalled JuliaCon reviews. If you are still interested in getting your work published, please start addressing the author-action-required items within the coming 3 weeks. If no action is taken within the coming 3 weeks, we will close the submission. Thank you for your understanding.

**Comment by lucaferranti** [comment]
@editorialbot reject
