### ISSUE TITLE
[PRE REVIEW]: Causal.jl: A Modeling and Simulation Framework for Causal Models

### ISSUE THREAD

**Issue by whedon** [JuliaCon/proceedings-review#67]
**Submitting author:** @zekeriyasari (<a href="http://orcid.org/0000-0003-4070-9666">Zekeriya SARI</a>)
**Repository:** <a href="https://github.com/zekeriyasari/Causal.jl" target ="_blank">https://github.com/zekeriyasari/Causal.jl</a>
**Version:** 
**Editor:** @matbesancon
**Reviewers:** @cscherrer, @YingboMa
**Managing EiC:** Valentin Churavy

**Author instructions**

Thanks for submitting your paper to JCON @zekeriyasari. **Currently, there isn't an JCON editor assigned** to your paper.

The author's suggestion for the handling editor is @matbesancon.

@zekeriyasari if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/jcon-reviewers) have already agreed to review for JCON and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JCON submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.39 s (421.4 files/s, 76711.7 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
SVG                             22              0             15          12915
Julia                           69           1310            669           6715
Markdown                        37            277              0           2419
TOML                             6            424              3           1941
TeX                             22            203             71           1397
Jupyter Notebook                 2              0           1076            118
YAML                             5             19              6             92
-------------------------------------------------------------------------------
SUM:                           163           2233           1840          25597
-------------------------------------------------------------------------------


Statistical information for the repository '7397898ff58891c69bce7293' was
gathered on 2020/10/15.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Zekeriya                         3             6             10            0.21
zekeriya.sari                   86          3504           4067           99.79

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
```

**Comment by whedon** [comment]
PDF failed to compile for issue #67 with the following error: 

 Can't find any papers to compile :-(

**Comment by matbesancon** [comment]
@whedon generate pdf from branch juliacon

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch juliacon. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #67 with the following error: 

 Can't find any papers to compile :-(

**Comment by matbesancon** [comment]
@zekeriyasari you will need to rename the subfolder to "paper"

**Comment by zekeriyasari** [comment]
@matbesancon I renamed the subfolder "proceedings" to "paper".

**Comment by zekeriyasari** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
PDF failed to compile for issue #67 with the following error: 

 Can't find any papers to compile :-(

**Comment by zekeriyasari** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
PDF failed to compile for issue #67 with the following error: 

 Can't find any papers to compile :-(

**Comment by zekeriyasari** [comment]
@whedon generate pdf from branch juliacon

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch juliacon. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #67 with the following error: 

 pandoc: /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-d14a699185fb/resources/jcon/latex.template: openBinaryFile: does not exist (No such file or directory)
Looks like we failed to compile the PDF

**Comment by zekeriyasari** [comment]
@whedon generate pdf from branch juliacon

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch juliacon. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #67 with the following error: 

 pandoc: /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-d14a699185fb/resources/jcon/latex.template: openBinaryFile: does not exist (No such file or directory)
Looks like we failed to compile the PDF

**Comment by zekeriyasari** [comment]
@whedon generate pdf from branch juliacon

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch juliacon. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #67 with the following error: 

 pandoc: /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-d14a699185fb/resources/jcon/latex.template: openBinaryFile: does not exist (No such file or directory)
Looks like we failed to compile the PDF

**Comment by zekeriyasari** [comment]
@matbesancon I renamed the subfolder, but could not find out how to resolve the problem.

**Comment by matbesancon** [comment]
@whedon generate pdf from branch juliacon

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch juliacon. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #67 with the following error: 

 pandoc: /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-d14a699185fb/resources/jcon/latex.template: openBinaryFile: does not exist (No such file or directory)
Looks like we failed to compile the PDF

**Comment by matbesancon** [comment]
It seems like you modified the template a lot. Could you keep the paper structure as-is? The compilation phase relies on it.
Also, https://github.com/zekeriyasari/Causal.jl/blob/juliacon/paper/paper.yml#L21
it seems like you are using a different file, Ref.bib, and not refs.bib

**Comment by zekeriyasari** [comment]
@whedon generate pdf from branch juliacon

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch juliacon. Reticulating splines etc...
```

**Comment by zekeriyasari** [comment]
@matbesancon I revised the paper files. It has been 13 minutes and no error has been thrown yet. I think the errors are fixed now.

**Comment by vchuravy** [comment]
@whedon generate pdf from branch juliacon

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch juliacon. Reticulating splines etc...
```

**Comment by vchuravy** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List all of Whedon's capabilities
@whedon commands

# Assign a GitHub user as the sole reviewer of this submission
@whedon assign @username as reviewer

# Add a GitHub user to the reviewers of this submission
@whedon add @username as reviewer

# Re-invite a reviewer (if they can't update checklists)
@whedon re-invite @username as reviewer

# Remove a GitHub user from the reviewers of this submission
@whedon remove @username as reviewer

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

# Change editorial assignment
@whedon assign @username as editor

# Set the software archive DOI at the top of the issue e.g.
@whedon set 10.0000/zenodo.00000 as archive

# Set the software version at the top of the issue e.g.
@whedon set v1.0.1 as version

# Open the review issue
@whedon start review

EDITORIAL TASKS

# All commands can be run on a non-default branch, to do this pass a custom 
# branch name by following the command with `from branch custom-branch-name`.
# For example:

# Compile the paper
@whedon generate pdf

# Compile the paper from alternative branch
@whedon generate pdf from branch custom-branch-name

# Remind an author or reviewer to return to a review after a
# certain period of time (supported units days and weeks)
@whedon remind @reviewer in 2 weeks

# Ask Whedon to do a dry run of accepting the paper and depositing with Crossref
@whedon accept

# Ask Whedon to check the references for missing DOIs
@whedon check references

# Ask Whedon to check repository statistics for the submitted software
@whedon check repository

EiC TASKS

# Invite an editor to edit a submission (sending them an email)
@whedon invite @editor as editor

# Reject a paper
@whedon reject

# Withdraw a paper
@whedon withdraw

# Ask Whedon to actually accept the paper and deposit with Crossref
@whedon accept deposit=true

```

**Comment by vchuravy** [comment]
@whedon assign @matbesancon  as editor

**Comment by whedon** [comment]
OK, the editor is @matbesancon

**Comment by matbesancon** [comment]
@whedon generate pdf from branch juliacon

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch juliacon. Reticulating splines etc...
```

**Comment by matbesancon** [comment]
hi @arfon, I'm not sure what the error can be here

**Comment by arfon** [comment]
@matbesancon - I think the fact that there is a `paper.md` and `paper.tex` is confusing Whedon. Can you delete the `paper.md` file and try again?

**Comment by matbesancon** [comment]
Thanks!
@zekeriyasari sorry we experienced some delays on the editorial side, could you update the repo to remove the paper.md and see whether it builds

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch juliacon. Reticulating splines etc...
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/JuliaCon/proceedings-papers/jcon.00067/jcon.00067/10.21105.jcon.00067.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/JuliaCon/proceedings-papers/blob/jcon.00067/jcon.00067/10.21105.jcon.00067.pdf) :page_facing_up: :point_left:

**Comment by zekeriyasari** [comment]
@matbesancon I removed `paper.md`. Seems like the build is OK.

**Comment by matbesancon** [comment]
perfect thank you

**Comment by matbesancon** [comment]
@whedon set editor @matbesancon

**Comment by whedon** [comment]
I'm sorry human, I don't understand that. You can see what commands I support by typing:

```
@whedon commands
```

**Comment by matbesancon** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List all of Whedon's capabilities
@whedon commands

# Assign a GitHub user as the sole reviewer of this submission
@whedon assign @username as reviewer

# Add a GitHub user to the reviewers of this submission
@whedon add @username as reviewer

# Re-invite a reviewer (if they can't update checklists)
@whedon re-invite @username as reviewer

# Remove a GitHub user from the reviewers of this submission
@whedon remove @username as reviewer

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

# Change editorial assignment
@whedon assign @username as editor

# Set the software archive DOI at the top of the issue e.g.
@whedon set 10.0000/zenodo.00000 as archive

# Set the software version at the top of the issue e.g.
@whedon set v1.0.1 as version

# Open the review issue
@whedon start review

EDITORIAL TASKS

# All commands can be run on a non-default branch, to do this pass a custom 
# branch name by following the command with `from branch custom-branch-name`.
# For example:

# Compile the paper
@whedon generate pdf

# Compile the paper from alternative branch
@whedon generate pdf from branch custom-branch-name

# Remind an author or reviewer to return to a review after a
# certain period of time (supported units days and weeks)
@whedon remind @reviewer in 2 weeks

# Ask Whedon to do a dry run of accepting the paper and depositing with Crossref
@whedon accept

# Ask Whedon to check the references for missing DOIs
@whedon check references

# Ask Whedon to check repository statistics for the submitted software
@whedon check repository

EiC TASKS

# Invite an editor to edit a submission (sending them an email)
@whedon invite @editor as editor

# Reject a paper
@whedon reject

# Withdraw a paper
@whedon withdraw

# Ask Whedon to actually accept the paper and deposit with Crossref
@whedon accept deposit=true

```

**Comment by matbesancon** [comment]
@whedon invite @matbesancon as editor

**Comment by matbesancon** [comment]
@whedon invite @cscherrer as reviewer

**Comment by whedon** [comment]
I'm sorry human, I don't understand that. You can see what commands I support by typing:

```
@whedon commands
```

**Comment by matbesancon** [comment]
@whedon add @cscherrer as reviewer

**Comment by whedon** [comment]
OK, @cscherrer is now a reviewer

**Comment by matbesancon** [comment]
@whedon add @YingboMa as reviewer

**Comment by whedon** [comment]
OK, @YingboMa is now a reviewer

**Comment by matbesancon** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/JuliaCon/proceedings-review/issues/71.
