### ISSUE TITLE
[PRE REVIEW]: UnitTestDesign.jl: Combinatorial design for unit tests

### ISSUE THREAD

**Issue by whedon** [JuliaCon/proceedings-review#74]
**Submitting author:** @adolgert (<a href="http://orcid.org/0000-0002-6477-7981">Andrew Dolgert</a>)
**Repository:** <a href="https://github.com/adolgert/UnitTestDesign.jl" target ="_blank">https://github.com/adolgert/UnitTestDesign.jl</a>
**Version:** 
**Editor:** @matbesancon
**Reviewers:** @odow, @oxinabox
**Managing EiC:** Arfon Smith

**Author instructions**

Thanks for submitting your paper to JCON @adolgert. **Currently, there isn't an JCON editor assigned** to your paper.

@adolgert if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/jcon-reviewers) have already agreed to review for JCON and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JCON submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
PDF failed to compile for issue #74 with the following error: 
```
 Can't find any papers to compile :-(

```

**Comment by adolgert** [comment]
The paper is in `paper/paper.tex`. I don't see whedon commands to debug this. Would it hurt if I resubmitted the paper? I see that the base github link is for a branch, not the actual base.

**Comment by vchuravy** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/JuliaCon/proceedings-papers/jcon.00074/jcon.00074/10.21105.jcon.00074.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/JuliaCon/proceedings-papers/blob/jcon.00074/jcon.00074/10.21105.jcon.00074.pdf) :page_facing_up: :point_left:

**Comment by vchuravy** [comment]
@whedon assign @vchuravy as editor

**Comment by whedon** [comment]
OK, the editor is @vchuravy

**Comment by vchuravy** [comment]
@whedon assign @matbesancon as editor

**Comment by whedon** [comment]
OK, the editor is @matbesancon

**Comment by adolgert** [comment]
I'm unsure of protocol here, but thank you for reading!

**Comment by matbesancon** [comment]
@whedon add @odow as reviewer

**Comment by whedon** [comment]
OK, @odow is now a reviewer

**Comment by matbesancon** [comment]
@whedon add @oxinabox as reviewer

**Comment by whedon** [comment]
OK, @oxinabox is now a reviewer

**Comment by matbesancon** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/JuliaCon/proceedings-review/issues/78.
