### ISSUE TITLE
[PRE REVIEW]: Algorithmic Variants of Nested Sampling

### ISSUE THREAD

**Issue by whedon** [JuliaCon/proceedings-review#83]
**Submitting author:** @SaranjeetKaur (<a href="http://orcid.org/0000-0002-7038-1457">Saranjeet Kaur Bhogal</a>)
**Repository:** <a href="https://github.com/TuringLang/NestedSamplers.jl" target ="_blank">https://github.com/TuringLang/NestedSamplers.jl</a>
**Version:** 
**Editor:** @carstenbauer
**Reviewer:** Pending
**Managing EiC:** Valentin Churavy

**Author instructions**

Thanks for submitting your paper to JCON @SaranjeetKaur. **Currently, there isn't an JCON editor assigned** to your paper.

The author's suggestion for the handling editor is @ranjanan.

@SaranjeetKaur if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/jcon-reviewers) have already agreed to review for JCON and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JCON submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
PDF failed to compile for issue #83 with the following error: 
```
 Can't find any papers to compile :-(

```

**Comment by carstenbauer** [comment]
@whedon assign @carstenbauer as editor

**Comment by whedon** [comment]
OK, the editor is @carstenbauer

**Comment by ranjanan** [comment]
@whedon generate pdf from branch juliason2021-proceedings

**Comment by whedon** [comment]
PDF failed to compile for issue #83 with the following error: 
```
 Can't find any papers to compile :-(

```

**Comment by ranjanan** [comment]
@whedon generate pdf from branch juliacon2021-proceedings

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch juliacon2021-proceedings. Reticulating splines etc...
```

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch juliacon2021-proceedings. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #83 with the following error: 
```
 /app/vendor/ruby-2.6.6/lib/ruby/2.6.0/psych.rb:456:in `parse': (1c15263e371432d3c4aa091a/paper/paper.yml): did not find expected key while parsing a block mapping at line 1 column 1 (Psych::SyntaxError)
	from /app/vendor/ruby-2.6.6/lib/ruby/2.6.0/psych.rb:456:in `parse_stream'
	from /app/vendor/ruby-2.6.6/lib/ruby/2.6.0/psych.rb:390:in `parse'
	from /app/vendor/ruby-2.6.6/lib/ruby/2.6.0/psych.rb:277:in `load'
	from /app/vendor/ruby-2.6.6/lib/ruby/2.6.0/psych.rb:578:in `block in load_file'
	from /app/vendor/ruby-2.6.6/lib/ruby/2.6.0/psych.rb:577:in `open'
	from /app/vendor/ruby-2.6.6/lib/ruby/2.6.0/psych.rb:577:in `load_file'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon.rb:125:in `load_yaml'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon.rb:87:in `initialize'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon/processor.rb:38:in `new'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon/processor.rb:38:in `set_paper'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/bin/whedon:58:in `prepare'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/bin/whedon:131:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `<main>'

```

**Comment by carstenbauer** [comment]
@SaranjeetKaur Can you please fix the paper build? I see the same error als whedon (first line) when I try to compile the paper locally:
```
Traceback (most recent call last):
	7: from ./prep.rb:6:in `<main>'
	6: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/psych.rb:577:in `load_file'
	5: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/psych.rb:577:in `open'
	4: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/psych.rb:578:in `block in load_file'
	3: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/psych.rb:277:in `load'
	2: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/psych.rb:390:in `parse'
	1: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/psych.rb:456:in `parse_stream'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/psych.rb:456:in `parse': (paper.yml): did not find expected key while parsing a block mapping at line 1 column 1 (Psych::SyntaxError)
```

**Comment by SaranjeetKaur** [comment]
Ok, let me check

**Comment by carstenbauer** [comment]
@SaranjeetKaur: Is this still on your radar? :)

**Comment by SaranjeetKaur** [comment]
Yes @carstenbauer! Hopefully, I will get back to you by coming weekend.

**Comment by carstenbauer** [comment]
Bump. @SaranjeetKaur Do you still plan to go ahead with this?

**Comment by SaranjeetKaur** [comment]
Hello @carstenbauer, apologies for the inordinate delay from my side in getting back to this. I will test the compilation very soon.

**Comment by carstenbauer** [comment]
Bump. Would be good to get an update here. Do you still plan to fix this and move on to review stage?

**Comment by carstenbauer** [comment]
Given there hasn't been any response for 9 month, I'm closing this now.

**Comment by lucaferranti** [comment]
@editorialbot reject
