### ISSUE TITLE
[PRE REVIEW]: Computing Reachable Sets of Semi-Discrete Solid Dynamics Equations with ReachabilityAnalysis.jl

### ISSUE THREAD

**Issue by whedon** [JuliaCon/proceedings-review#85]
**Submitting author:** @mforets (<a href="http://orcid.org/0000-0002-9831-7801">Marcelo Forets</a>)
**Repository:** <a href="https://github.com/JuliaReach/SetPropagation-FEM-JuliaCon21" target ="_blank">https://github.com/JuliaReach/SetPropagation-FEM-JuliaCon21</a>
**Version:** 
**Editor:** @carstenbauer
**Reviewers:** @PetrKryslUCSD, @lmiq
**Managing EiC:** Valentin Churavy

**Author instructions**

Thanks for submitting your paper to JCON @mforets. **Currently, there isn't an JCON editor assigned** to your paper.

The author's suggestion for the handling editor is @carstenbauer.

@mforets if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/jcon-reviewers) have already agreed to review for JCON and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JCON submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Checking the BibTeX entries failed with the following error: 

 Failed to parse BibTeX on value "@" (AT) [#<BibTeX::Bibliography data=[8]>, "@", #<BibTeX::Entry >, {:author=>["Colas {Le Guernic} and Antoine Girard"], :title=>["Reachability analysis of linear systems using support functions"], :journal=>["Nonlinear Analysis: Hybrid Systems"], :volume=>["4"], :number=>["2"], :pages=>["250 - 262"], :year=>["2010"], :note=>["IFAC World Congress 2008"]}, ","]

**Comment by whedon** [comment]
Failed to discover a `Statement of need` section in paper

**Comment by whedon** [comment]
Wordcount for `paper.tex` is 535

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.26 s (53.7 files/s, 12593.3 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
TeX                              9            250            217           2398
SVG                              1              1              1            200
Julia                            1             16              7             54
Ruby                             1              8              4             45
Markdown                         1             25              0             31
YAML                             1              2              0             24
-------------------------------------------------------------------------------
SUM:                            14            302            229           2752
-------------------------------------------------------------------------------


Statistical information for the repository 'b4b9ddc0fbe79dbbf1364fe9' was
gathered on 2021/09/30.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
mforets                          1            57              0          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Marcelo Forets               57          100.0          0.0                7.02
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/JuliaCon/proceedings-papers/jcon.00085/jcon.00085/10.21105.jcon.00085.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/JuliaCon/proceedings-papers/blob/jcon.00085/jcon.00085/10.21105.jcon.00085.pdf) :page_facing_up: :point_left:

**Comment by mforets** [comment]
> @mforets if you have any suggestions for potential reviewers then please mention them here

Here is a list of reviewer suggestions (please note that I haven't contacted any of them directly). The github handle is in parentheses.

- Kristoffer Carlsson (KristofferC)
- Fredrik Ekre (fredrikekre)
- Petr Krysl (PetrKryslUCSD)
- Leandro Martínez (lmiq)
- Helios de Rosario (heliosdrm)
- Axel Larsson (?, see [JuliaCon'21 talk](https://pretalx.com/juliacon2021/talk/WWP7DR/))

**Comment by whedon** [comment]
OK, @PetrKryslUCSD is now a reviewer

**Comment by PetrKryslUCSD** [comment]
It seems to me that given this is a contribution to JuliaCon a link to a Julia FEM package should be a priority. Instead of Matlab/Octave...

**Comment by carstenbauer** [comment]
Well, the JuliaCon proceedings pendant of your JOSS link is https://github.com/JuliaCon/proceedings-review/issues. This thread is the Pre-review thread. Once I've found a second reviewer, we can officially move to review stage (this issue will get closed and a new one with `[REVIEW]` will get opened.

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/JuliaCon/proceedings-review/issues/95.
