### ISSUE TITLE
[PRE REVIEW]: ChipSort: a SIMD and cache-aware sorting module

### ISSUE THREAD

**Issue by whedon** [JuliaCon/proceedings-review#9]
**Submitting author:** @nlw0 (<a href="http://orcid.org/0000-0003-0017-5890">Nicolau Werneck</a>)
**Repository:** <a href="https://github.com/nlw0/chipsort-article" target ="_blank">https://github.com/nlw0/chipsort-article</a>
**Editor:** @vchuravy
**Reviewers:** @eschnett

**Author instructions**

Thanks for submitting your paper to JuliaCon @nlw0. The JuliaCon editor @vchuravy, will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@nlw0 if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](http://bit.ly/2V9GSFq) have already agreed to review for JuliaCon and may be suitable for this submission.

**Editor instructions**

The JuliaCon submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @vchuravy it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for the assigned editor (@vchuravy) to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](http://bit.ly/2V9GSFq) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/JuliaCon/proceedings-papers/blob/jcon.00009/jcon.00009/10.21105.jcon.00009.pdf)

**Comment by vchuravy** [comment]
@musm would you be willing to review this?

**Comment by eschnett** [comment]
@vchuravy I'd be happy to review. What is the time line? Do you have a pointer to instructions for reviewers?

**Comment by vchuravy** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List all of Whedon's capabilities
@whedon commands

# Assign a GitHub user as the sole reviewer of this submission
@whedon assign @username as reviewer

# Add a GitHub user to the reviewers of this submission
@whedon add @username as reviewer

# Remove a GitHub user from the reviewers of this submission
@whedon remove @username as reviewer

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

# Change editorial assignment
@whedon assign @username as editor

# Set the software archive DOI at the top of the issue e.g.
@whedon set 10.0000/zenodo.00000 as archive

# Set the software version at the top of the issue e.g.
@whedon set v1.0.1 as version

# Open the review issue
@whedon start review

EDITORIAL TASKS

# Compile the paper
@whedon generate pdf

# Compile the paper from alternative branch
@whedon generate pdf from branch custom-branch-name

# Remind an author or reviewer to return to a review after a
# certain period of time (supported units days and weeks)
@whedon remind @reviewer in 2 weeks

# Ask Whedon to accept the paper and deposit with Crossref
@whedon accept

# Ask Whedon to check the references for missing DOIs
@whedon check references

```

**Comment by vchuravy** [comment]
@whendon assign @eschnett as reviewer

The timeline is until JuliaCon so July 20th, but the earlier the better :)

We have a reviewer guideline at https://proceedings.juliacon.org/guide/reviewers/ and if you have questions both @matbesancon and I are happy to help.

**Comment by eschnett** [comment]
@whedon add @eschnett as reviewer

**Comment by whedon** [comment]
I'm sorry @eschnett, I'm afraid I can't do that. That's something only editors are allowed to do.

**Comment by matbesancon** [comment]
@whedon add @eschnett as reviewer

**Comment by whedon** [comment]
OK, @eschnett is now a reviewer

**Comment by eschnett** [comment]
@nlw0 In section 3.3 of your manuscript you compare against C++. Please add which compiler version from which vendor you are using, and in particular which libstdc++ you are using (I assume the compiler is less relevant than the standard library).

**Comment by eschnett** [comment]
@nlw0 Your manuscript is technical in the sense that it assumes that the reader is familiar with SIMD operations and tis benefits and drawbacks. Since the manuscript is also about sorting, that might not be true. You could add a subsection in the beginning describing SIMD, which operations are fast, and which are slow. Alternatively, maybe there is a good SIMD introduction available (online?) to which you could point.

**Comment by eschnett** [comment]
@nlw0 When sorting, one criterion is always whether the sort is stable or not. You don't discuss this. I assume that your sorting implementation is unstable. What would it take to implement a stable sort?

**Comment by eschnett** [comment]
@nlw0 All examples you show are for 32-bit quantities. What changes for different sizes (e.g. 8 bit, 64 bit, or even 128 bit md5sums)? What would need to change to sort floating point values with their pesky `nan` values? Maybe you want to add a few comments on this in the implementation or benchmark sections.

**Comment by eschnett** [comment]
@nlw0 You refer to "metaprogramming" in the manuscript, but don't explain the term. You could add a pointer, maybe referring to the respective section in the Julia manual.

**Comment by eschnett** [comment]
@vchuravy @nlw0 Overall evaluation: **Minor modification request**. I like this manuscript very much, it is very well written, technically thorough, and easy to read for a non-export. I would accept the manuscript as-is (except for the missing information regarding the C++ implementation), but would like @nlw0 to at least comment on my remarks.

**Comment by nlw0** [comment]
Thanks a lot, @eschnett. These are all excellent remarks and I'll try to address them as well as I can.

**Comment by vchuravy** [comment]
Ah I forgot to actually start the review.

@whedon start review

**Comment by vchuravy** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/JuliaCon/proceedings-review/issues/12. Feel free to close this issue now!

**Comment by vchuravy** [comment]
@nlw0 please let us know when you addressed the comments and then we can proceed in #12
