### ISSUE TITLE
[PRE REVIEW]: ProbabilityBoundsAnalysis.jl: theory and algorithms

### ISSUE THREAD

**Issue by whedon** [JuliaCon/proceedings-review#90]
**Submitting author:** @AnderGray (<a href="http://orcid.org/0000-0002-1585-0900">Ander Gray</a>)
**Repository:** <a href="https://github.com/AnderGray/ProbabilityBoundsAnalysis.jl" target ="_blank">https://github.com/AnderGray/ProbabilityBoundsAnalysis.jl</a>
**Version:** 
**Editor:** @carstenbauer
**Reviewers:** @dpsanders, @baggepinnen
**Managing EiC:** Valentin Churavy

**Author instructions**

Thanks for submitting your paper to JCON @AnderGray. **Currently, there isn't an JCON editor assigned** to your paper.

The author's suggestion for the handling editor is @carstenbauer.

@AnderGray if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/jcon-reviewers) have already agreed to review for JCON and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JCON submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
PDF failed to compile for issue #90 with the following error: 
```
 Can't find any papers to compile :-(

```

**Comment by whedon** [comment]
PDF failed to compile for issue #90 with the following error: 
```
 Can't find any papers to compile :-(

```

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List Whedon's capabilities
@whedon commands

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

EDITORIAL TASKS

# Compile the paper
@whedon generate pdf

# Compile the paper from alternative branch
@whedon generate pdf from branch custom-branch-name

# Ask Whedon to check the references for missing DOIs
@whedon check references

# Ask Whedon to check repository statistics for the submitted software
@whedon check repository

```

**Comment by AnderGray** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch JuliaConPaper. Reticulating splines etc...
```

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch JuliaConPaper. Reticulating splines etc...
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/JuliaCon/proceedings-papers/jcon.00090/jcon.00090/10.21105.jcon.00090.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/JuliaCon/proceedings-papers/blob/jcon.00090/jcon.00090/10.21105.jcon.00090.pdf) :page_facing_up: :point_left:
