### ISSUE TITLE
[REVIEW]: Applied Measure Theory for Probabilistic Modeling

### ISSUE THREAD

**Issue by whedon** [JuliaCon/proceedings-review#92]
**Submitting author:** @mschauer (<a href="http://orcid.org/0000-0003-3310-7915">Moritz Schauer</a>)
**Repository:** <a href="https://github.com/cscherrer/MeasureTheory.jl" target ="_blank">https://github.com/cscherrer/MeasureTheory.jl</a>
**Version:** v0.16.4
**Reviewer:** @ludgerpaehler, @femtomc
**Archive:** <a href="https://doi.org/10.5281/zenodo.6707122" target="_blank">10.5281/zenodo.6707122</a>

[![status](https://proceedings.juliacon.org/papers/7958be3512c592ee211c3a3e8b22165e/status.svg)](https://proceedings.juliacon.org/papers/7958be3512c592ee211c3a3e8b22165e)

Status badge code:

```
HTML: <a href="https://proceedings.juliacon.org/papers/7958be3512c592ee211c3a3e8b22165e"><img src="https://proceedings.juliacon.org/papers/7958be3512c592ee211c3a3e8b22165e/status.svg"></a>
Markdown: [![status](https://proceedings.juliacon.org/papers/7958be3512c592ee211c3a3e8b22165e/status.svg)](https://proceedings.juliacon.org/papers/7958be3512c592ee211c3a3e8b22165e)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/cscherrer/MeasureTheory.jl" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@ludgerpaehler & @femtomc, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @vchuravy know.

✨ **Please start on your review when you are able, and be sure to complete your review in the next six weeks, at the very latest** ✨ 

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JuliaCon conflict of interest policy](https://proceedings.juliacon.org/guide/authors#coi) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JuliaCon code of conduct](https://proceedings.juliacon.org/coc).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/cscherrer/MeasureTheory.jl">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Authorship:** Has the submitting author (@mschauer) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [ ] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [ ] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Paper format

- [x] **Authors:** Does the `paper.tex` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?
- [x] **Page limit:** Is the page limit for full papers respected by the submitted document?

### Content

- [x] **Context:** is the scientific context motivating the work correctly presented?
- [x] **Methodology:** is the approach taken in the work justified, presented with enough details and reference to reproduce it?
- [x] **Results:** are the results presented and compared to approaches with similar goals?
### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JuliaCon conflict of interest policy](https://proceedings.juliacon.org/guide/authors#coi) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JuliaCon code of conduct](https://proceedings.juliacon.org/coc).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/cscherrer/MeasureTheory.jl">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Authorship:** Has the submitting author (@mschauer) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [ ] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Paper format

- [x] **Authors:** Does the `paper.tex` file include a list of authors with their affiliations?
- [ ] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [ ] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?
- [ ] **Page limit:** Is the page limit for full papers respected by the submitted document?

### Content

- [ ] **Context:** is the scientific context motivating the work correctly presented?
- [ ] **Methodology:** is the approach taken in the work justified, presented with enough details and reference to reproduce it?
- [ ] **Results:** are the results presented and compared to approaches with similar goals?

**Comment by ludgerpaehler** [comment]
Really interesting package with a strong necessity for it.

Working through the checklist, there are two points which jumped my eyes:

> Statement of Need: Do the authors clearly state what problems the software is designed to solve (..)?

https://github.com/cscherrer/MeasureTheory.jl/issues/179

> Example Usage: Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).

https://github.com/cscherrer/MeasureTheory.jl/issues/180

**Comment by ludgerpaehler** [comment]
I would furthermore encourage the authors to improve the reading flow of the paper. Two sections that the eye in this respect are 

In "Why Measures?"
> Also, there’s an elegant correspondence between frequentist
and Bayesian methods, where regularization corresponds to a prior.

It is a really good analogy, but reads disconnected from the rest of the paragraph. Integration with the rest of the paragraph would elevate the reading flow greatly.

- "Related Work" just lists the 5 related papers in their own respective paragraphs, without any leading thread between the 5 of them.

**Comment by cscherrer** [comment]
Thank you @ludgerpaehler! I'll discuss with @mschauer; we'll follow up in the issues you added.

**Comment by femtomc** [comment]
@cscherrer 
> Community guidelines: Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

Do you mind adopting a specific set of guidelines for contributions, and placing them in the repository? (e.g. ColPrac, or something else).

**Comment by vchuravy** [comment]
Gentle bump @cscherrer did you address the review points?

**Comment by whedon** [comment]
Reminder set for @cscherrer in two weeks

**Comment by cscherrer** [comment]
Hi, :wave: 

I'd like to thank @vchuravy and our reviewers @ludgerpaehler and @femtomc for helpful feedback and patience. MeasureTheory has grown and matured steadily since our initial submission, so we had an issue of trying to hit a moving target with a paper that will soon be somewhat frozen. I think we're finally in a position to address this more thoroughly.

We have made some modifications to the repository which should now be visible. We've also made some significant edits to the paper, to make it match the current state of the package. These changes are in a separate branch. I expect @mschauer and I can get these pushed to the `paper` branch very soon, likely within the next day or two. After we merge these, the branch will still be available in case you'd like to see details of exactly what has changed.

I'll update again here when the changes are merged.

**Comment by cscherrer** [comment]
Edits are pushed! The `paper` branch is now updated.

**Comment by cscherrer** [comment]
@whedon generate pdf from branch paper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch paper. Reticulating splines etc...
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/JuliaCon/proceedings-papers/jcon.00092/jcon.00092/10.21105.jcon.00092.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/JuliaCon/proceedings-papers/blob/jcon.00092/jcon.00092/10.21105.jcon.00092.pdf) :page_facing_up: :point_left:

**Comment by mschauer** [comment]
@femtomc Do you think #200 addresses your concerns in a way adequate for a small project?

**Comment by femtomc** [comment]
Yes, perfect.

**Comment by cscherrer** [comment]
Up to you of course, but there are quite a few changes. There's a diff here in case that's helpful:
https://github.com/cscherrer/MeasureTheory.jl/pull/201/files#diff-983b58b8186b0a4ed7f280f258cdab3eb0dd7d5136f8ac361ba982a43cfb7136

**Comment by mschauer** [comment]
Sorry, we should have said it: This is our revision.

**Comment by cscherrer** [comment]
@whedon generate pdf from branch paper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch paper. Reticulating splines etc...
```

**Comment by cscherrer** [comment]
(minor updates to the bibliography)

**Comment by vchuravy** [comment]
@whedon help

**Comment by whedon** [comment]
I'm sorry human, I don't understand that. You can see what commands I support by typing:

```
@whedon commands
```

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List all of Whedon's capabilities
@whedon commands

# Assign a GitHub user as the sole reviewer of this submission
@whedon assign @username as reviewer

# Add a GitHub user to the reviewers of this submission
@whedon add @username as reviewer

# Re-invite a reviewer (if they can't update checklists)
@whedon re-invite @username as reviewer

# Remove a GitHub user from the reviewers of this submission
@whedon remove @username as reviewer

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

# Change editorial assignment
@whedon assign @username as editor

# Set the software archive DOI at the top of the issue e.g.
@whedon set 10.0000/zenodo.00000 as archive

# Set the software version at the top of the issue e.g.
@whedon set v1.0.1 as version

# Open the review issue
@whedon start review

EDITORIAL TASKS

# All commands can be run on a non-default branch, to do this pass a custom 
# branch name by following the command with `from branch custom-branch-name`.
# For example:

# Compile the paper
@whedon generate pdf

# Compile the paper from alternative branch
@whedon generate pdf from branch custom-branch-name

# Remind an author or reviewer to return to a review after a
# certain period of time (supported units days and weeks)
@whedon remind @reviewer in 2 weeks

# Ask Whedon to do a dry run of accepting the paper and depositing with Crossref
@whedon recommend-accept

# Ask Whedon to check the references for missing DOIs
@whedon check references

# Ask Whedon to check repository statistics for the submitted software
@whedon check repository

EiC TASKS

# Invite an editor to edit a submission (sending them an email)
@whedon invite @editor as editor

# Reject a paper
@whedon reject

# Withdraw a paper
@whedon withdraw

# Ask Whedon to actually accept the paper and deposit with Crossref
@whedon accept deposit=true

```

**Comment by vchuravy** [comment]
@whedon recommend-accept

**Comment by ludgerpaehler** [comment]
From my side it looks good to publish!

**Comment by cscherrer** [comment]
Thanks @mschauer . I was worried about violating some DOI uniqueness requirements, but I think your point about referring to a specific version makes sense.

**Comment by mschauer** [comment]
No worries, there is no uniqueness requirement for DOIs, I also linked them:

<img width="360" alt="Screen Shot 2022-06-30 at 19 07 21" src="https://user-images.githubusercontent.com/1923437/176736618-90b38ae2-7e50-4fd5-89d1-a6001cd71a6f.png">

**Comment by cscherrer** [comment]
@whedon set 10.5281/zenodo.6784068 as archive

**Comment by whedon** [comment]
I'm sorry @cscherrer, I'm afraid I can't do that. That's something only editors are allowed to do.

**Comment by vchuravy** [comment]
@whedon set 10.5281/zenodo.6784068 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.6784068" target="_blank">10.5281/zenodo.6784068</a> is the archive.

**Comment by vchuravy** [comment]
Sorry folks this should be the DOI to the code-artifacts. Not the DOI to the paper, we will generate that later.

**Comment by vchuravy** [comment]
The JOSS docs are clearer on that:

> We ask that the authors issue a new tagged release of the software (if changed), and archive it (on [Zenodo](https://zenodo.org/), [figshare](https://figshare.com/), or other). The authors then post the version number and archive DOI in the REVIEW issue. The handling editor executes the pre-publication steps, and pings the EiCs for final processing.

**Comment by cscherrer** [comment]
Ok here it is:
[![DOI](https://zenodo.org/badge/233287642.svg)](https://zenodo.org/badge/latestdoi/233287642)
That's for `cscherrer/MeasureTheory.jl: v0.16.4`

**Comment by vchuravy** [comment]
@whedon set 10.5281/zenodo.6707122 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.6707122" target="_blank">10.5281/zenodo.6707122</a> is the archive.

**Comment by whedon** [comment]
OK. v0.16.4 is the version.

**Comment by vchuravy** [comment]
@whedon recommend-accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #92 with the following error: 
```
 Can't find any papers to compile :-(

```

**Comment by vchuravy** [comment]
@whedon recommend-accept from branch paper

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
:wave: @JuliaCon/jcon-eics, this paper is ready to be accepted and published.

 Check final proof :point_right: https://github.com/JuliaCon/proceedings-papers/pull/60

If the paper PDF and Crossref deposit XML look good in https://github.com/JuliaCon/proceedings-papers/pull/60, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true from branch paper 
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1007/978-3-642-17905-1 is OK
- 10.1007/978-1-4757-2539-1 is OK
- 10.5281/ZENODO.1005091 is OK
- 10.5281/ZENODO.3931118 is OK
- 10.18637/jss.v098.i16 is OK
- 10.5281/zenodo.2647458 is OK
- 10.1214/18-AOS1715 is OK
- 10.3389/fphy.2021.663457 is OK
- 10.1007/s11222-021-10008-8 is OK
- 10.48550/ARXIV.2103.08478 is OK
- 10.1016/j.spl.2018.02.021 is OK
- 10.2168/lmcs-9(3:11)2013 is OK
- 10.1145/3374208 is OK
- 10.1214/088342307000000014 is OK
- 10.1007/978-3-319-29604-3_5 is OK
- 10.5281/zenodo.5520061 is OK
- 10.18637/jss.v076.i01 is OK

MISSING DOIs

- 10.1137/141000671 may be a valid DOI for title: Julia: A fresh approach to numerical computing
- 10.1145/503272.503288 may be a valid DOI for title: Stochastic lambda calculus and monads of probability distributions

INVALID DOIs

- https://doi.org/10.1016/j.jmva.2009.04.008 is INVALID because of 'https://doi.org/' prefix
```

**Comment by vchuravy** [comment]
@cscherrer can you fix up the DOI in your references?

**Comment by cscherrer** [comment]
Just the one, right? I've just pushed the fix

**Comment by cscherrer** [comment]
Oh wait I can add the missing ones

**Comment by cscherrer** [comment]
Ok think it's done

**Comment by cscherrer** [comment]
Guess I should ping you now @vchuravy :)

**Comment by vchuravy** [comment]
@whedon recommend-accept from branch paper

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
Checking the BibTeX entries failed with the following error: 

 Failed to parse BibTeX on value "volume" (NAME) [#<BibTeX::Bibliography data=[3]>, "@", #<BibTeX::Entry >, {:title=>["Julia: {A} fresh approach to numerical computing"], :author=>["Bezanson, Jeff and Edelman, Alan and Karpinski, Stefan and Shah, Viral B"], :journal=>["SIAM review"], :doi=>["10.1137/141000671"]}]

**Comment by whedon** [comment]
PDF failed to compile for issue #92 with the following error: 
```
 Latexmk: This is Latexmk, John Collins, 17 Jan. 2018, version: 4.55.
Rule 'pdflatex': Rules & subrules not known to be previously run:
   pdflatex
Rule 'pdflatex': The following rules & subrules became out-of-date:
      'pdflatex'
------------
Run number 1 of rule 'pdflatex'
------------
------------
Running 'pdflatex  -recorder  "paper.tex"'
------------
Collected error summary (may duplicate other messages):
  pdflatex: Command for 'pdflatex' gave return code 1
      Refer to 'paper.log' for details
E, [2022-07-03 17:31:39#45] ERROR -- : Failed to parse BibTeX on value "volume" (NAME) [#<BibTeX::Bibliography data=[3]>, "@", #<BibTeX::Entry >, {:title=>["Julia: {A} fresh approach to numerical computing"], :author=>["Bezanson, Jeff and Edelman, Alan and Karpinski, Stefan and Shah, Viral B"], :journal=>["SIAM review"], :doi=>["10.1137/141000671"]}]
bibtex.y:138:in `on_error': Failed to parse BibTeX on value "volume" (NAME) [#<BibTeX::Bibliography data=[3]>, "@", #<BibTeX::Entry >, {:title=>["Julia: {A} fresh approach to numerical computing"], :author=>["Bezanson, Jeff and Edelman, Alan and Karpinski, Stefan and Shah, Viral B"], :journal=>["SIAM review"], :doi=>["10.1137/141000671"]}] (BibTeX::ParseError)
	from (eval):3:in `_racc_do_parse_c'
	from (eval):3:in `do_parse'
	from bibtex.y:111:in `parse'
	from /app/vendor/bundle/ruby/2.6.0/gems/bibtex-ruby-6.0.0/lib/bibtex/bibliography.rb:67:in `parse'
	from /app/vendor/bundle/ruby/2.6.0/gems/bibtex-ruby-6.0.0/lib/bibtex/bibliography.rb:50:in `open'
	from /app/vendor/bundle/ruby/2.6.0/gems/bibtex-ruby-6.0.0/lib/bibtex/utilities.rb:25:in `open'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon/bibtex_parser.rb:38:in `generate_citations'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon/compilers.rb:202:in `crossref_from_latex'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon/compilers.rb:19:in `generate_crossref'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon/processor.rb:100:in `compile'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/bin/whedon:88:in `compile'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/bin/whedon:131:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `<main>'

```

**Comment by vchuravy** [comment]
@whedon generate pdf from branch paper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch paper. Reticulating splines etc...
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/JuliaCon/proceedings-papers/jcon.00092/jcon.00092/10.21105.jcon.00092.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/JuliaCon/proceedings-papers/blob/jcon.00092/jcon.00092/10.21105.jcon.00092.pdf) :page_facing_up: :point_left:

**Comment by vchuravy** [comment]
@whedon recommend-accept from branch paper

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
Checking the BibTeX entries failed with the following error: 

 Failed to parse BibTeX on value "volume" (NAME) [#<BibTeX::Bibliography data=[3]>, "@", #<BibTeX::Entry >, {:title=>["Julia: {A} fresh approach to numerical computing"], :author=>["Bezanson, Jeff and Edelman, Alan and Karpinski, Stefan and Shah, Viral B"], :journal=>["SIAM review"], :doi=>["10.1137/141000671"]}]

**Comment by whedon** [comment]
PDF failed to compile for issue #92 with the following error: 
```
 Latexmk: This is Latexmk, John Collins, 17 Jan. 2018, version: 4.55.
Rule 'pdflatex': Rules & subrules not known to be previously run:
   pdflatex
Rule 'pdflatex': The following rules & subrules became out-of-date:
      'pdflatex'
------------
Run number 1 of rule 'pdflatex'
------------
------------
Running 'pdflatex  -recorder  "paper.tex"'
------------
Collected error summary (may duplicate other messages):
  pdflatex: Command for 'pdflatex' gave return code 1
      Refer to 'paper.log' for details
E, [2022-07-03 17:35:58#130] ERROR -- : Failed to parse BibTeX on value "volume" (NAME) [#<BibTeX::Bibliography data=[3]>, "@", #<BibTeX::Entry >, {:title=>["Julia: {A} fresh approach to numerical computing"], :author=>["Bezanson, Jeff and Edelman, Alan and Karpinski, Stefan and Shah, Viral B"], :journal=>["SIAM review"], :doi=>["10.1137/141000671"]}]
bibtex.y:138:in `on_error': Failed to parse BibTeX on value "volume" (NAME) [#<BibTeX::Bibliography data=[3]>, "@", #<BibTeX::Entry >, {:title=>["Julia: {A} fresh approach to numerical computing"], :author=>["Bezanson, Jeff and Edelman, Alan and Karpinski, Stefan and Shah, Viral B"], :journal=>["SIAM review"], :doi=>["10.1137/141000671"]}] (BibTeX::ParseError)
	from (eval):3:in `_racc_do_parse_c'
	from (eval):3:in `do_parse'
	from bibtex.y:111:in `parse'
	from /app/vendor/bundle/ruby/2.6.0/gems/bibtex-ruby-6.0.0/lib/bibtex/bibliography.rb:67:in `parse'
	from /app/vendor/bundle/ruby/2.6.0/gems/bibtex-ruby-6.0.0/lib/bibtex/bibliography.rb:50:in `open'
	from /app/vendor/bundle/ruby/2.6.0/gems/bibtex-ruby-6.0.0/lib/bibtex/utilities.rb:25:in `open'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon/bibtex_parser.rb:38:in `generate_citations'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon/compilers.rb:202:in `crossref_from_latex'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon/compilers.rb:19:in `generate_crossref'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon/processor.rb:100:in `compile'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/bin/whedon:88:in `compile'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/bin/whedon:131:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `<main>'

```

**Comment by vchuravy** [comment]
@whedon check references

**Comment by mschauer** [comment]
@cscherrer commata missing in https://github.com/cscherrer/MeasureTheory.jl/commit/1f907a7b8d0f045da4e8be5026b5a2fbdf0aa1d1

**Comment by mschauer** [comment]
@whedon check references

**Comment by mschauer** [comment]
@whedon recommend-accept from branch paper

**Comment by whedon** [comment]
I'm sorry @mschauer, I'm afraid I can't do that. That's something only editors are allowed to do.

**Comment by mschauer** [comment]
@whedon generate pdf from branch paper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch paper. Reticulating splines etc...
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/JuliaCon/proceedings-papers/jcon.00092/jcon.00092/10.21105.jcon.00092.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/JuliaCon/proceedings-papers/blob/jcon.00092/jcon.00092/10.21105.jcon.00092.pdf) :page_facing_up: :point_left:

**Comment by cscherrer** [comment]
Thanks @mschauer , just accepted your changes

**Comment by vchuravy** [comment]
@whedon check references

**Comment by mschauer** [comment]
@whedon check references from branch paper

**Comment by whedon** [comment]
```
Attempting to check references... from custom branch paper
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1007/978-3-642-17905-1 is OK
- 10.1007/978-1-4757-2539-1 is OK
- 10.1137/141000671 is OK
- 10.5281/ZENODO.1005091 is OK
- 10.5281/ZENODO.3931118 is OK
- 10.18637/jss.v098.i16 is OK
- 10.5281/zenodo.2647458 is OK
- 10.1214/18-AOS1715 is OK
- 10.3389/fphy.2021.663457 is OK
- 10.1007/s11222-021-10008-8 is OK
- 10.48550/ARXIV.2103.08478 is OK
- 10.1016/j.spl.2018.02.021 is OK
- 10.2168/lmcs-9(3:11)2013 is OK
- 10.1145/3374208 is OK
- 10.1214/088342307000000014 is OK
- 10.1016/j.jmva.2009.04.008 is OK
- 10.1007/978-3-319-29604-3_5 is OK
- 10.5281/zenodo.5520061 is OK
- 10.18637/jss.v076.i01 is OK
- 10.1145/503272.503288 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by vchuravy** [comment]
@whedon recommend-accept from branch paper

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
:wave: @JuliaCon/jcon-eics, this paper is ready to be accepted and published.

 Check final proof :point_right: https://github.com/JuliaCon/proceedings-papers/pull/61

If the paper PDF and Crossref deposit XML look good in https://github.com/JuliaCon/proceedings-papers/pull/61, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true from branch paper 
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1007/978-3-642-17905-1 is OK
- 10.1007/978-1-4757-2539-1 is OK
- 10.1137/141000671 is OK
- 10.5281/ZENODO.1005091 is OK
- 10.5281/ZENODO.3931118 is OK
- 10.18637/jss.v098.i16 is OK
- 10.5281/zenodo.2647458 is OK
- 10.1214/18-AOS1715 is OK
- 10.3389/fphy.2021.663457 is OK
- 10.1007/s11222-021-10008-8 is OK
- 10.48550/ARXIV.2103.08478 is OK
- 10.1016/j.spl.2018.02.021 is OK
- 10.2168/lmcs-9(3:11)2013 is OK
- 10.1145/3374208 is OK
- 10.1214/088342307000000014 is OK
- 10.1016/j.jmva.2009.04.008 is OK
- 10.1007/978-3-319-29604-3_5 is OK
- 10.5281/zenodo.5520061 is OK
- 10.18637/jss.v076.i01 is OK
- 10.1145/503272.503288 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by vchuravy** [comment]
@whedon accept deposit=true from branch paper

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JCON!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/JuliaCon/proceedings-papers/pull/62
1. Wait a couple of minutes, then verify that the paper DOI resolves [https://doi.org/10.21105/jcon.00092](https://doi.org/10.21105/jcon.00092)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? Notify your editorial technical team...

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://proceedings.juliacon.org/papers/10.21105/jcon.00092/status.svg)](https://doi.org/10.21105/jcon.00092)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/jcon.00092">
  <img src="https://proceedings.juliacon.org/papers/10.21105/jcon.00092/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://proceedings.juliacon.org/papers/10.21105/jcon.00092/status.svg
   :target: https://doi.org/10.21105/jcon.00092
```
This is how it will look in your documentation:

[![DOI](https://proceedings.juliacon.org/papers/10.21105/jcon.00092/status.svg)](https://doi.org/10.21105/jcon.00092)

**We need your help!**

JuliaCon Proceedings is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://forms.gle/yANMe4c9YmuW9MWcA
- Making a small donation to support our running costs here: https://numfocus.salsalabs.org/donate-to-jcon

**Comment by mschauer** [comment]
Thank you for the reviews @femtomc and @ludgerpaehler and the editorial work @vchuravy

**Comment by cscherrer** [comment]
Reviews were very helpful for improving readability and catching some repository issues we had missed. Thank you!
