### ISSUE TITLE
FEM sw linkage

### ISSUE THREAD

**Issue by PetrKryslUCSD** [JuliaCon/proceedings-review#94]
It seems to me that given this is a contribution to JuliaCon a link to a Julia FEM package should be a priority. Instead of Matlab/Octave...

**Comment by whedon** [comment]
:wave: This repository is only for review issues (`pre-review` and `review`) that have been created by our editorial infrastructure, and this issue appears not to be one of these.

As such, this issue will be closed. If you're opening an issue as part of a review, please open a new issue instead in the software repository associated with the submission that you are reviewing.

Many thanks!
